### ISSUE TITLE
Qt 2.6.2 crashes on calculate trade routes

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1]
> btw I checked why it crashes with traderoutes in 2.6.2 it std::sort crashes, 2.6.1 is ok
> I didnt checked why it crashes exactly
> jsut add 1 more city -> click calculate, try again and it will crash at 3,4,5 try
> sooner or later

**Comment by lmoureaux** [comment]
https://github.com/lmoureaux/freeciv/commit/018fa372a830aac3b47cf84feacbf4bd944097f9

**Comment by mir3x** [comment]
I didn't do that ! No idea where it came from.

**Comment by lmoureaux** [comment]
Qt deprecated `qSort` and it was mindlessly replaced with `std::sort` that has different requirements on the comparison function. `std::random_shuffle` is the equivalent in the STL.

**Comment by lmoureaux** [comment]
Fexed in 392a254
