### ISSUE TITLE
Move the Turn Done button to the bottom right and anchor the minimap

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1002]
**Is your feature request related to a problem? Please describe.**

The Turn Done button is currently in the top bar. As the only "action" button in this space, it feels a bit awkward.

**Describe the solution you'd like**

Move the Turn Done button to the bottom right of the screen, sticking to the corner. The minimap would come above, with a default width identical to the Turn Done button. Whether the minimap should be resizeable at all is open for debate.

![image](https://user-images.githubusercontent.com/22327575/166590515-02000819-d282-449f-9a7c-839d0e6981e4.png)

**Describe alternatives you've considered**

None so far

**Comment by jwrober** [comment]
When you say "anchor the mini-map" does that mean you cannot move it? what about turning it off (view menu) and on again? Would turn done be associated with the mini-map or a separate widget? My thinking is it should be associated with the mini-map as other discussions have talked about adding more features to the mini-map.

**Comment by lmoureaux** [comment]
> When you say "anchor the mini-map" does that mean you cannot move it?

Yes

> what about turning it off (view menu) and on again? 

Could do

> Would turn done be associated with the mini-map or a separate widget?

Layout-wise they'd be stuck next to each other, but there would be a visual separation.

**Comment by lmoureaux** [comment]
A more concrete mockup:
![image](https://user-images.githubusercontent.com/22327575/173956904-5f3b0bb3-95cb-4879-9be6-21cdd48a7b84.png)

**Comment by jwrober** [comment]
Closed by PR #1037
