### ISSUE TITLE
Install target fails on Visual Studio on Windows

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1006]
**Describe the bug**
The CMake install target for Windows is built for MSYS2 and has a hard coded path in it for SSL DLLs based on the MSYS2 path and not Visual Studio. When invoking `--target install` then fails when using Visual Studio.

**To Reproduce**
1. Install Visual Studio on Windows
2. Run configure and build commands
3. Run the command to install

**Expected behavior**
We will not support CPack and build a package installer due to licensing issues, however the install target should at least combine everything together for debugging and testing purposes.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Windows
 - Freeciv21 version: 3.0-Beta1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by lmoureaux** [comment]
* Installing the CA certificates might no longer be needed (since the removal of `libcurl`) because Qt should load them from the operating system by default (which is also safer if a cert is revoked). To be tested.
* The OpenSSL libraries could be located with CMake's `find_package(OpenSSL ...)`.
