### ISSUE TITLE
MP GUI does not support libcrypto and libssl v3

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1016]
**Describe the bug**
Visual Studio has a newer v3 of OpenSSL. When `libcrypto-3-x64.dll` and `libssl-3-x64.dll` are included with the install, the Modpack installer GUI will fail to open an `https` URI. However if you grab the v1.1 DLLs from MSYS2, then the program works fine.

**To Reproduce**
1. Build and Install in Visual Studio
2. Go to the install directory and open the modpack installer
3. See error

**Expected behavior**
modpack installer should be work with v1 and v3 libraries

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Windows 10 on Visual Studio
 - Freeciv21 version: e.g. 3.0-beta1
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
None

**Comment by lmoureaux** [comment]
Qt5 [officially supports](https://doc.qt.io/qt-5/ssl.html) "OpenSSL 1.1.1 or later". However, this page was written way before OpenSSL 3.0 was released in September last year. OpenSSL 3 isn't a drop-in replacement: the OpenSSL [migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html) says:

> OpenSSL 3.0 is a major release and consequently any application that currently uses an older version of OpenSSL will at the very least need to be recompiled in order to work with the new version.

vcpkg appears to ship only OpenSSL 3.x. Some Linux distros started shipping 3.0 as well (Ubuntu 22.04 being an example). The [OpenSSL policy](https://www.openssl.org/policies/releasestrat.html) is to support 1.1.1 until 2023-09-11.

Can you check against which version of OpenSSL Qt was built? Hopefully vcpkg stores logs of the build process...

**Comment by jwrober** [comment]
It looks like you can pin a package to a specific version in the vcpkg manifest file. I am going to look at that instead.
