### ISSUE TITLE
Update INSTALL

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#103]
The dependencies are stabilizing and the install procedure is stable. So it's time to look into it.

**Comment by mir3x** [comment]
Wait for new theme? I found also some unused png there, maybe also drop classic theme? No one ever tried to tune it, many ppl forgot how gtk2 looked like. Ill update necrophos to look nice

**Comment by jwrober** [comment]
I can work on this.

**Comment by jwrober** [comment]
in `/doc` directory. There is an `INSTALL.cygwin` and `INSTALL.meson` file. I'm not sure those are applicable anymore and can be removed. I would suggest that in `INSTALL` we work to cover not only Linux (Debian), but also Mac and Windows

**Comment by lmoureaux** [comment]
`INSTALL.meson` should for sure be dropped because the Meson build was removed. `INSTALL.cygwin` doesn't seem to contain a lot of information beyond what typical Linux instructions would have. I think it can also be dropped (otherwise would have to test cygwin, and I'd rather spend time on MSVC build).

**Comment by jwrober** [comment]
Another question - there are localized versions of the `INSTALL` file in `/doc/` as well. We either should A) remove them or B) work to translate them to native language either by Google Translate or a native speaker.

**Comment by lmoureaux** [comment]
Let's remove them. Most users will use ready-made installers/packages and devs speak English. Also, the website is not localized so who would even find them?

**Comment by jwrober** [comment]
This is done.
