### ISSUE TITLE
Chatline Widget cannot be resized

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1056]
**Describe the bug**
The moveable chatline widget can't be make taller. There is no option to drag from the top or the bottom to make it taller to see more rows of data. You can make it wider by grabbing the right side, but not from the left.

**To Reproduce**
1. Attempt to drag the chatline widget from the top, notice you cannot
2. Attempt to drag the chatline widget from the bottom, notice you cannot
3. Attempt to drag the chatline widget from the left, notice you cannot

**Expected behavior**
The chatline is to be moveable around the screen/window and minimized when wanted.
A player should be able to resize the widget from all 4 directions as they see fit.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: All
 - Freeciv21 version: `master` at https://github.com/longturn/freeciv21/commit/7a9a40ca3d14750d325fed25282fadf76f4147b1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by lmoureaux** [comment]
Does #1265 fix this? It makes resizing easier by adding a border around the widget.

**Comment by jwrober** [comment]
> 

Yes it does actually
