### ISSUE TITLE
 Correct end_turn() statistics 

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#1075]
**Describe the bug**
 The calculated stats are not per-player as one would assume from the player name and other player-specific ones. Those stats are zeroed only before iterating the players, not for each player, so they accumulate over players iterated. 

**To Reproduce**
1. End turn
2. See debug info

**Expected behavior**
You see per player stats

**Screenshots**

**Platform and version (please complete the following information):**
master

**Additional context**
Port: https://github.com/freeciv/freeciv/commit/d3d1a9665e5d917768cda936ddc715a8590c558f

**Comment by lmoureaux** [comment]
OSDN https://osdn.net/projects/freeciv/ticket/44879
