### ISSUE TITLE
Esc to deactivate goto doesn't work

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1086]
**Describe the bug**
If you click G to enter goto mode, you can't get out of it by clicking Esc. This has worked in the past

**To Reproduce**
1. Click on a unit
2. Click G to enter goto mode
3. Click Esc
4. Observe you're still in goto mode

**Expected behavior**
Esc should deactivate goto mode (but keep the unit activated)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
Interestingly enough, if you set goto waypoints by clicking G again, clicking Esc does remove those. Only the last step to get out of goto mode doesn't work.

**Comment by lmoureaux** [comment]
Workaround: click on the currently active unit.
