### ISSUE TITLE
Version number in "About Freeciv21" doesn't appear correct

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1087]
**Describe the bug**
There's `$Freeciv21Version` instead of an actual version number

**To Reproduce**
1. Open the "Help > About Freeciv21" window
2. Observe a version number missing

**Expected behavior**
I expect a version number here

**Screenshots**
![freeciv21-client_dy0uQLMciu](https://user-images.githubusercontent.com/7669061/177852344-88248a50-9d97-4183-bea3-fe3ada759e00.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by lmoureaux** [comment]
Works for me, so maybe a Windows-specific issue. The double line endings remind me of an old issue, are you 100% sure this is beta2?

![image](https://user-images.githubusercontent.com/22327575/177852880-a02fe49e-831d-4d9a-9a13-27b84d5492fe.png)

**Comment by daavko** [comment]
99.98% sure, it's the only version I have installed at this time. Installed with the `Freeciv21-v3.0.3755941-Windows-x86_64.exe` from the beta 2 release. The version number in the install folder name matches this as well.

**Comment by lmoureaux** [comment]
ok thanks for checking

**Comment by jwrober** [comment]
The problem is on Visual Studio. I can recreate there. Msys2 build works as expected.

**Comment by lmoureaux** [comment]
@daavko:
> Installed with the Freeciv21-v3.0.3755941-Windows-x86_64.exe from the beta 2 release. The version number in the install folder name matches this as well.

and @jwrober:
> The problem is on Visual Studio. I can recreate there. Msys2 build works as expected.

There's a contradictory information here. If the installer version is working correctly, this is not a priority. Otherwise it becomes more important. Some screenshots in https://discord.com/channels/378908274113904641/1052966382117072906 also seem to indicate that there are double newlines, which is typical of LF/CR LF issues.

**Comment by daavko** [comment]
The installer version does not work correctly. This is from beta 7, installed via the installer:

![freeciv21-client_mKUmJO69cp](https://user-images.githubusercontent.com/7669061/208529624-7f34bdc9-4468-471e-b43d-94c1144a428d.png)

**Comment by jwrober** [comment]
I see the same. If I run the installed version it does not work right, but if I run from inside MSYS2 it works fine.

**Comment by jwrober** [comment]
Looks like the issue is the EOL coding. It seems that `read_a_line()` here https://github.com/longturn/freeciv21/blob/01f85be1a38b0bc6eb3bf290d79fcc1f30c88d05/utility/inputfile.cpp#L447 doesn't handle CRLF appropriately.
