### ISSUE TITLE
Assigning keyboard shortcuts doesn't completely remove the previous ones

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1090]
**Describe the bug**
If you manually change a keyboard shortcut (changing it from the default), then change it again, then change it back, it doesn't work. The client just says "already assigned to \<function\>", even though it's the same function it's being assigned to. As if it remembers past shortcuts somehow.

**To Reproduce**
1. Open shortcuts settings, assign `numpad /` to "zoom in", click "Ok"
2. Open shortcuts settings, assign `numpad +` to "zoom in", click "Ok"
3. Open shortcuts settings, assign `numpad /` to "zoom in", click "Ok"
4. Observe an error message `Num+/ is already assigned to Zoom in`

**Expected behavior**
It shouldn't remember shortcut history and should completely replace the old keyboard shortcut

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by lmoureaux** [comment]
What the code does:

* Look through existing shortcuts to see if it finds a conflict.
* Go through the menu and check for conflicts.
* Rant if a conflict is found
* Update the shortcuts hash

It doesn't seem to ever update the menu bar, hence the issue when setting back to the previous value
