### ISSUE TITLE
Horizontal lines in the research tree aren't completely horizontal

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1091]
**Describe the bug**
They should be straight lines, but they bob up and down by a pixel.

**To Reproduce**
1. Open the research tree
2. Observe non-straight lines

**Expected behavior**
Straight lines

**Screenshots**
In the middle of the magenta rectangle here
![freeciv21-client_P8839TL9fo](https://user-images.githubusercontent.com/7669061/177861591-0acd29d7-c1a8-4e21-849f-66b1cc18c432.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by lmoureaux** [comment]
Confirmed
