### ISSUE TITLE
Helptext popup doesn't show up when changing hovered item in research tree

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1092]
**Describe the bug**
When hovering over a unit/building/wonder (henceforth referred to as "researchable thing" in this issue) in the research tree, if you change to another researchable thing within the same tech, the helptext popup for it doesn't show up.

**To Reproduce**
1. Hover over a researchable thing until the helptext popup shows up
2. Move the cursor over a different researchable thing within that same technology
3. Wait for the helptext popup to show up, but it doesn't

**Expected behavior**
It should open a new helptext popup

**Screenshots**
I recorded a video. I can send it directly if it's not playable in the browser. (the video shows a tech with 5 researchable things, so one might come to the conclusion that this happens for every even item, but the amount doesn't matter)
https://user-images.githubusercontent.com/7669061/177864389-98481c4b-4693-471a-aadd-7ad2aa13870f.mp4

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
If you wait for a couple seconds after the previous helptext popup closes and then move the cursor just a couple pixels, the helptext popup shows up.

**Comment by lmoureaux** [comment]
I'm a bit disturbed by the blinking in your video, I hope it's not our bug :sweat_drops:

**Comment by daavko** [comment]
Oh, I didn't notice that at the time. It does look like that in real life as well, so the recording is accurate. No idea what the cause might be.

**Comment by lmoureaux** [comment]
Does it do the same on standard Qt widgets? For instance, the zoom buttons next to the minimap have tooltips

**Comment by daavko** [comment]
It does, yes. Though it's less pronounced, probably due to the size of the tooltip. Might be a Qt bug.

**Comment by daavko** [comment]
I did a little bit of searching (just a quick Google search for "qt tooltip flicker"), [this Qt bug report](https://bugreports.qt.io/browse/QTBUG-50356) seems to be roughly describing the effect visible in the video. And if I don't move the mouse after the tooltip is scheduled to show (by moving *really slowly* 1px at a time), the flicker does appear to go away. I'd chalk it up to some weirdness between Qt and Windows.
