### ISSUE TITLE
Behaviour of "hide minimap" is broken

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#1096]
**Describe the bug**
Using the hide minimap option from the menu or "ctrl+M" must just hide the minimap, but it causes unintended behaviour

**To Reproduce**
1. Hide minimap from view menu, or Ctrl + M
2. Notice, that the widget is still left in the bottom as a blank space
3. It also disables moving widgets around the screen . You cant move unit-actions, chat window or any widgets around

**Expected behavior**
Just the minimap disappears along with the empty space, and the zoom buttons stay above the turn done button. It shouldnt affect the behaviour of widgets

**Screenshots**
![image](https://user-images.githubusercontent.com/30164619/178108599-cd1f59f0-d297-4a0c-b824-e18ae37b5d70.png)
Notice that the move handle in the corner of widgets have disappeared. 

**Platform and version (please complete the following information):**
 - OS:Linux
 - Freeciv21 version:master

**Comment by lmoureaux** [comment]
I would be in favor of removing the option altogether.

**Comment by pranavtifr** [comment]
I'm ambivalent about this. It is indeed convenient to have the option, but tbh, I dont use it at all in normal usage.
