### ISSUE TITLE
Some tileset sprites have a strange transparency effect applied when city view is open

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1106]
**Describe the bug**
When a city view is open, some sprites (I've noticed this with units, cities, and some tile extras so far) become partially transparent.

**To Reproduce**
1. Observe a unit
2. Open a city view
3. Observe the same unit, now half transparent

**Expected behavior**
They shouldn't be half-transparent

**Screenshots**
Regular view:
![freeciv21-client_QzK8MCIOgm](https://user-images.githubusercontent.com/7669061/178124232-e53ac5d6-253e-4874-a65a-7908a027623d.png)
![freeciv21-client_OF5l18NEfj](https://user-images.githubusercontent.com/7669061/178124235-9cec5c39-45f9-49c1-b639-1c65e5d16d48.png)
![freeciv21-client_3ZJZktjO2N](https://user-images.githubusercontent.com/7669061/178124238-4bffa549-02d1-4422-b397-a9a0d6501c07.png)

With city view open:
![freeciv21-client_zao8Zj5V1E](https://user-images.githubusercontent.com/7669061/178124243-b803006c-1a1e-459c-8024-d932963557a2.png)
![freeciv21-client_AeUgIYj86G](https://user-images.githubusercontent.com/7669061/178124244-f14ad13e-d36c-4920-a386-256fcf46ee0c.png)
![freeciv21-client_R618UwXdOw](https://user-images.githubusercontent.com/7669061/178124245-66f7afd5-69ed-49dc-b4d1-9fd808575054.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
It seems like it applies to units regardless of where they are, but for cities and tile extras only if those are outside of the worked area of the currently opened city.

**Comment by lmoureaux** [comment]
Dimming cities and units is a (maybe bad) feature.

**Comment by Corbeau-1** [comment]
![image](https://user-images.githubusercontent.com/25233743/215897676-6583a035-3dee-401e-bd2e-b17d126482f5.png)
![image](https://user-images.githubusercontent.com/25233743/215897741-c8fdfcb4-4fa5-4aab-aa39-6aba4e27217d.png)
