### ISSUE TITLE
Replace "Ok" and "Cancel" in dialog buttons with something that better describes what will happen

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1110]
**Is your feature request related to a problem? Please describe.**
Current dialogs (didn't check all of them, but I assume they share this behavior) have two buttons: "Ok" and "Cancel" (or variations, such as "Yes" and "No"). Those don't actually describe what will happen when the button is clicked.

**Describe the solution you'd like**
As an example, let's take the "Quit game" dialog. It's current form:
![freeciv21-client_Aa8WlybG0l](https://user-images.githubusercontent.com/7669061/178125756-b5635023-da90-4faf-ae02-44012d1ef2b7.png)
I'd replace "Ok" with "Quit", and "Cancel" with "Keep playing". Same as this with all other dialogs for actions with two outcomes. As another example, the "disband unit" dialog. Replacing "Yes" with "Disband" and "No" with "Cancel" makes it a little clearer IMO.

**Describe alternatives you've considered**
Leaving it as it is, which would probably be fine, but IMO titling dialog buttons better will make the game more polished.

**Additional context**
This was inspired by what Google's Material Design guidelines recommend for alert dialogs: [link to relevant section](https://material.io/components/dialogs#alert-dialog). Apple has [similar guidelines](https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/#buttons).

**Comment by lmoureaux** [comment]
List with most of them:
```
$ grep -r setStandardButtons client/
client/cityrep.cpp:            ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/dialogs.cpp:  msg->setStandardButtons(QMessageBox::Ok);
client/dialogs.cpp:    ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/dialogs.cpp:    impossible->setStandardButtons(QMessageBox::Ok);
client/dialogs.cpp:    ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/dialogs.cpp:    too_much->setStandardButtons(QMessageBox::Ok);
client/dialogs.cpp:    ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/dialogs.cpp:    ask->setStandardButtons(QMessageBox::Ok);
client/dialogs.cpp:    ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/economyreport.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/economyreport.cpp:      result->setStandardButtons(QMessageBox::Ok);
client/economyreport.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/economyreport.cpp:    result->setStandardButtons(QMessageBox::Ok);
client/economyreport.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/economyreport.cpp:    result->setStandardButtons(QMessageBox::Ok);
client/unitreport.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/citydlg.cpp:    ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/citydlg.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/citydlg.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/gui_main.cpp:  ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/mapview.cpp:    ask->setStandardButtons(QMessageBox::Close);
client/menu.cpp:  saved->setStandardButtons(QMessageBox::Ok);
client/menu.cpp:    ask->setStandardButtons(QMessageBox::Cancel | QMessageBox::Ok);
client/shortcuts.cpp:  scinfo->setStandardButtons(QMessageBox::Ok);
```

**Comment by jwrober** [comment]
Added good first issue label. With lmoureaux's grep, should be easy for a new coder to go through and pick better values.
