### ISSUE TITLE
Make "Advanced unit selection" dialog movable

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1111]
**Describe the bug**
Currently it's always-on-top, centered, and not movable. This makes it hard to look at the map while choosing the various options for unit selection.

**To Reproduce**
1. Open the "Advanced unit selection" dialog
2. Observe a center part of the map now blocked by the dialog with no way to move it around

**Expected behavior**
I'd expect it to have a proper title bar to make it movable (also with a close button like other dialogs have)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by jwrober** [comment]
The dialog is also modal, so it stays on top of all windows even if you minimize fc21 client
