### ISSUE TITLE
Hide stack traces by default?

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#112]
They're useless unless for devs. Maybe better require devs to set an env var than every user to do the same.

**Comment by ec429** [comment]
If they weren't so long it'd be arguable, but 100+ lines of stack trace per error quickly pushes the interesting bits out of xterm's scrollback buffer.
At least make them off-by-default if built without debugging symbols; a backtrace full of hex addresses is not at all informative.

**Comment by mir3x** [comment]
I was very happy when those logs caused my tmp to be full so I couldnt even compile again without clearing it.

**Comment by lmoureaux** [comment]
Done in #120.
