### ISSUE TITLE
Applying changes in the "More Game Options" dialog resets it to the default state

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1122]
**Describe the bug**
If you do some changes in the "More Game Options" dialog when starting a new single-player game and apply them, the dialog gets reset to the default state. The changes do actually get applied, as can be seen in the server console in the main window.

**To Reproduce**
1. Click on "Start new game" in the main menu
2. Open the "More Game Options" dialog
3. Do some changes
4. Click "Apply" at the bottom
5. Observe the dialog returning to the default state before you applied anything

**Expected behavior**
The dialog should keep the changes.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by lmoureaux** [comment]
I can reproduce.

**Comment by lmoureaux** [comment]
Turned out it was only for bitwise options, e.g. `topology`.
