### ISSUE TITLE
Switching cities directly from city view leaves behind tile output sprites of previous city

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1123]
**Describe the bug**
When you switch a city from city view by clicking on another city, the previous city's output sprites are left on the map.

**To Reproduce**
1. Create two cities
2. Open a city view of city A
3. Switch to city view of city B by clicking on it on the map (*not* by using the arrows at the top)
4. Close the city view
5. Observe tile output sprites of city A on the map

**Expected behavior**
The tile output sprites shouldn't be there.

**Screenshots**
After doing this with 5 cities:
![freeciv21-client_kBFbE5N7pr](https://user-images.githubusercontent.com/7669061/178778484-9e035188-454b-47ac-afe3-6a4a9e83adcd.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
The "View > City Output" setting is disabled

**Comment by jwrober** [comment]
I can reproduce. Interesting painting issue.
