### ISSUE TITLE
Using the keyboard shortcut for showing/hiding the map while in city view makes the map widget an incorrect size

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1126]
**Describe the bug**
When you show/hide the map while in city view, the containing widget retains the size it had before, instead of resizing correctly.

**To Reproduce**
1. Open any city view
2. Show or hide the map
3. Close the city view
4. Observe the map widget is incorrect size

**Expected behavior**
The widget should size itself according to the current contents

**Screenshots**
Map widget after getting shown when in city view (very vertically squished):
![6Cta0t65XH](https://user-images.githubusercontent.com/7669061/178795817-bc6e5c19-c7a6-4105-a66f-d55859f9541b.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: current master (4c6aee6)
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by jwrober** [comment]
Interesting bug since you can't actually see the mini-map when in city view, but if you use ctrl-m while in city view the bug asserts itself. Seems like an edge case to me.
