### ISSUE TITLE
Zooming causes tile output sprites to appear spontaneously

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1127]
**Describe the bug**
Very strange, but somehow, if you ~~toggle the "View > Scale fonts" option (doesn't matter whichs state it's in), and~~ zoom (in or out, doesn't matter), tile output appears by itself.

**To Reproduce**
1. Create a city
2. ~~Toggle the "View > Scale fonts" option~~
3. Zoom in or out
4. Observe tile output sprites

**Expected behavior**
Tile output shouldn't appear by itself

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by daavko** [comment]
Actually, just zooming is enough to do this. Toggling the "Scale fonts" option seems unrelated. Just create a city and zoom in or out.

**Comment by jwrober** [comment]
I can't recreate this one.

**Comment by lmoureaux** [comment]
Confirmed in beta2, but only after opening the city screen (which creating a city does automatically)

**Comment by lmoureaux** [comment]
Also confirmed in `bugfix/shortcuts-reassign`
