### ISSUE TITLE
In some cases, one of the lines depicting the current view in minimap is slanted

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1128]
**Describe the bug**
Sometimes, when viewing parts of the map that are on the left side of the minimap, the left vertical line depicting the current "area" is slanted. Best seen on the screenshot

**To Reproduce**
1. Start a game
2. Move the map view around on the left side of the minimap

**Expected behavior**
The lines should be perpendicular to each other

**Screenshots**
The left line of the rectangle (though it's not really a rectangle now)
![freeciv21-client_oTVIGW2dc1](https://user-images.githubusercontent.com/7669061/178807614-9a2493ee-af93-46fc-83b2-fd03154127d9.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 2
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by jwrober** [comment]
I can't recreate this one

**Comment by lmoureaux** [comment]
I can sometimes, might depend on the map topology

**Comment by daavko** [comment]
This was an iso map, I believe with map size of 4000 tiles total
