### ISSUE TITLE
Scenarios list not loading on Linux

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1133]
**Describe the bug**
From the start screen, when you click the button to load a scenario game, the list of scenarios is empty.

**To Reproduce**
1. Start the client
2. Click on start scenario game
3. See error

**Expected behavior**
You should get a list of the scenarios installed.

**Screenshots**
This is the issue...
![image](https://user-images.githubusercontent.com/23037938/179097595-c209fccc-1119-4fa1-9ee9-936b5d0153cc.png)

This is what I expect...
![image](https://user-images.githubusercontent.com/23037938/179097620-faa45a13-6641-4188-b797-702276495f81.png)

**Platform and version (please complete the following information):**
 - OS: Linux (Debian and Arch)
 - Freeciv21 version: 3.0-beta2
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
During discord conversation it seems that in `utility/shared.cpp` the `freeciv_storage_dir()` is looking for a writable location, but the out of box scenarios are not installed in a writable location when installed via the package.

**Comment by lmoureaux** [comment]
> During discord conversation it seems that in `utility/shared.cpp` the `freeciv_storage_dir()` is looking for a writable location, but the out of box scenarios are not installed in a writable location when installed via the package.

```cpp
static QStringList default_scenario_path()
{
  return {QStringLiteral("."), QStringLiteral("data/scenarios"),
          freeciv_storage_dir()
              + QStringLiteral("/" DATASUBDIR "/scenarios"),
          freeciv_storage_dir() + QStringLiteral("/scenarios")};
}

QString freeciv_storage_dir()
{
  static QString storage_dir;
  if (storage_dir.isEmpty()) {
    // Make sure that all exe get the same directory.
    auto app_name = QCoreApplication::applicationName();
    QCoreApplication::setApplicationName("freeciv21");
    storage_dir =
        QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);
    QCoreApplication::setApplicationName(app_name);

    qDebug() << _("Storage dir:") << storage_dir;
  }

  return storage_dir;
}
```

We should look in `default_data_path` instead, basically `default_data_path()` with `/scenarios` appended:
```cpp
static QStringList default_data_path()
{
  // Make sure that all executables get the same directory.
  auto app_name = QCoreApplication::applicationName();
  QCoreApplication::setApplicationName("freeciv21");

  auto paths =
      QStringList{QStringLiteral("."), QStringLiteral("data"),
                  freeciv_storage_dir() + QStringLiteral("/" DATASUBDIR),
                  QStringLiteral(FREECIV_INSTALL_DATADIR)}
      + QStandardPaths::standardLocations(QStandardPaths::DataLocation);
  QCoreApplication::setApplicationName(app_name);
  return paths;
}
```
