### ISSUE TITLE
Use Qt::Edges instead of a custom enum for resizing widgets

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#1145]
**Describe the bug**
No bug, but codacy complains about  [MISRA 16.2 ](https://lost-contact.mit.edu/afs/pdc.kth.se/roots/ilse/v0/pdc/vol/matlab/r2016b/help/codeprover/ref/misrac2012rule16.2.html)whenever Qt enums are used. 

**To Reproduce**
Look at #1081 

**Expected behavior**
No problems with codacy ?

**Platform and version (please complete the following information):**
- master

**Additional Context**
Do nothing. Maybe codacy is a false positive.

**Comment by lmoureaux** [comment]
Hoz is this related to Qt::Edges?

**Comment by pranavtifr** [comment]
Idk, you suggested that in the corresponding PR.
