### ISSUE TITLE
Port Longturn patches - commands

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1151]
This is a breakout issue from #503 to track status better.

**Short summary of patches**
New server commands.

**Patches to port**
Commits listed chronologically, beginning from the oldest one.

- longturn/freeciv@12c64874d8 - Add `syncturn` command
- longturn/freeciv@41cc12b401 - Add `/showtimeout` and `/fixtimeout`, fix `/syncturn` to work right

**Comment by lmoureaux** [comment]
I would vote for a single command with subcommands, something like:
```
/timeout set <seconds> # equivalent to /set timeout
/timeout fix <seconds>
/timeout show
```
`/timeoutincrease` needs special consideration.
