### ISSUE TITLE
Port Longturn patches - game mechanics tweaks with server options (diplomacy + intel)

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1154]
This is a breakout issue from #503 to track status better.

This is only for diplomacy and intel mechanics tweaks that have a new server option or a ruleset option associated with them.

**Short summary of patches**
New diplomacy and intel mechanics with server options, see commit messages listed below.

**Patches to port**
Commits listed chronologically, beginning from the oldest one.

- longturn/freeciv@a76a6ce922 - Add server option to make initial diplomatic state Peace instead of War.
- longturn/freeciv@bb271b9714 - Add server option to hide intel on other nations if you have contact
- longturn/freeciv@9ff9c36b2d - Have `contact_intel` only checked on server

**Comment by lmoureaux** [comment]
https://github.com/longturn/freeciv/commit/a76a6ce922: this should be ruleset
https://github.com/longturn/freeciv/commit/bb271b9714: this could be ruleset as well, what do people think? Could even be an effect based on your government or techs
