### ISSUE TITLE
Port Longturn patches - detailed combat info

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1157]
This is a breakout issue from https://github.com/longturn/freeciv21/issues/503 to track status better.

**Short summary of patches**
Detailed combat information sent to client.

**Patches to port**
Commits listed chronologically, beginning from the oldest one.

- longturn/freeciv@6cfa1734e0 - Add detailed combat info server message

**Comment by lmoureaux** [comment]
May want to remove the client-side version of this feature

**Comment by lmoureaux** [comment]
Done in 94f479c556815e6d46a805ddd6a621d1f1a7fbb2.
