### ISSUE TITLE
Messages widget is "below" Chat widget

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1159]
**Describe the bug**
If the moveable chat widget is moved to the upper right corner and the messages widget is shown, the chat is on top of it and hides messages.

**To Reproduce**
1. Open a game (any game)
2. Hide messages widget
3. Move chat widget to upper right corner
4. Show messages
5. See error

**Expected behavior**
Messages should be on top

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/179797357-73efd968-d9ab-454d-a3be-203a32566673.png)

**Platform and version (please complete the following information):**
 - OS: Linux (assume its there on other OS)
 - Freeciv21 version: 3.0-beta3
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by pranavtifr** [comment]
To add to this, it also goes below the map widget. Makes it impossible to see the recent messages sometimes.
