### ISSUE TITLE
Allies only option not styled properly when checked

### ISSUE THREAD

**Issue by psampathkumar** [longturn/freeciv21#1160]
**Describe the bug**
The popup for the allies only checkbox always shows, "allies only". It is confusing given it isnt a check but has a icon change currently. 

**To Reproduce**
1. Open a game. 
2. Hover over allies only checkbox in chat widget

**Expected behavior**
The popup should say "broadcast globally" (or something along those lines), when allies only is enabled, and "allies only" when allies only is disabled. So that the user understands what that option goes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30164619/179822378-3689b3ef-c8e1-4967-b029-e693aad0a667.png)
![image](https://user-images.githubusercontent.com/30164619/179822432-90225e00-c6b0-4381-9175-ea9590e995f1.png)

**Platform and version (please complete the following information):**
- master

**Comment by jwrober** [comment]
> **Expected behavior** The popup should say "broadcast globally" (or something along those lines), when allies only is enabled, and "allies only" when allies only is disabled. So that the user understands what that option goes.
> 
Do you mean to say that when "Allies Only" is enabled the tool tip should say so and when disabled the tool tip would say "broadcast to all" or something?

**Comment by pranavtifr** [comment]
That or the other way around. Both works, like to show, "allies only" is enabled. Or to show, clicking on it *will* change to allies only. I am not really sure which way is better, but it should definitely be one of the two to keep things consistent.

**Comment by lmoureaux** [comment]
It's a checkable button. The issue is that none of the themes implements the appropriate styling.

**Comment by lmoureaux** [comment]
Anyone willing to write some CSS for Classic and Nightstalker?

**Comment by daavko** [comment]
I'd say the tooltip should show the current state, that's how I feel it's usually done. What would appropriate styling be here?

**Comment by lmoureaux** [comment]
It's a checkable button, so it should look raised when unchecked and sunken when checked.
