### ISSUE TITLE
Server crash - Lua _deflua_make_partisans_callback()

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1161]
**Describe the bug**
```
[critical] freeciv21-server (../common/scriptcore/luascript.cpp:453) - T417: lua error:       stack index 2, expected number, received number: not a numeric type that fits exactly an integer (number maybe has significant decimals) (bad argument into 'int(int, int)')
stack traceback:
        [C]: in function 'random'
        data/default/default.lua:191: in function '_deflua_make_partisans_callback'
```

**To Reproduce**
1. Start a game, use a savegame or run an autogame to get up to partisans
2. Build a partisan
3. See error

**Expected behavior**
No server crash on the Lua callback

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux (but assume its everywhere)
 - Freeciv21 version: 3.0-beta3
 - Ruleset/Longturn game (if applicable): classic

**Additional context**
None

**Comment by lmoureaux** [comment]
This line from `default.lua` looks weird:
```lua
  local partisans = random(0, 1 + (city.size + 1) / 2) + 1
```
The upper bound in the `random()` call will be fractional if `city.size` is even. We need to `floor()` it explicitly or disable the check in `sol2`.
