### ISSUE TITLE
Add scrollbar arrows

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1162]
**Is your feature request related to a problem? Please describe.**
The client uses horizontal and vertical scrollbars in many places such as chat widget, messages widget, technology tree screen, etc. 

**Describe the solution you'd like**
This request is to add up/down arrows to edges of vertical bars and left/right arrows to the edges of horizontal ones to make scrolling easier, especially if you don't have a mouse with scroll wheel or something.

**Describe alternatives you've considered**
What we have now does "work", but it could be better.

**Additional context**
None

**Comment by pranavtifr** [comment]
I'm personally not a fan of arrow buttons on scrollbars. Feels very old school to have that. Infact I dont even like scrollbars which dont autohide. So, ya, Is the buttons really needed, if we can grab the bar and drag. If yes, We need to autohide the scrollbars until hovered.

**Comment by lmoureaux** [comment]
> Even modern Linux and Windows still use buttons on scrollbars.

Of the applications I have open, neither of Dolphin, Kate, Konsole, Discord, Skype, Mattermost, Slack, and VS Code have buttons on their scroll bars. Mac OS doesn't have them. It looks like the buttons were removed in Windows 11.

This being said, it's a relatively easy feature if we want it (I don't mind either way, I think the Nightstalker scroll bars are terrible).
