### ISSUE TITLE
Create a Game Manual

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1232]
**What should be documented? Is there something wrong in the documentation?**
With a new client manual soon to be published, we need to do a full documentation of the server and all its commands along with some recipes for usage and running your own.

**Do you have suggestions?**
Add to new `Manuals` section same as with client manual.

**Comment by lmoureaux** [comment]
There's a lot of content on the Freeciv wiki, but it's also often outdated. The license there is CC-BY-SA 3.0, which we can upgrade to CC-BY-SA 4.0 and then into our own GPLv3. The license requires attribution.

Relevant pages:
* https://freeciv.fandom.com/wiki/Server_Manual
* https://freeciv.fandom.com/wiki/Server_command-line_options
* https://freeciv.fandom.com/wiki/Server_commands
* https://freeciv.fandom.com/wiki/Server_options

**Comment by lmoureaux** [comment]
Following the discussion on #1304, here is how I would organize the contents. The idea is to have distinct areas for what the average player sees (someone who doesn't know what the server is) and the more advanced parts aimed at sysadmins. The language used in the first part shouldn't be technical at all, while in the second we can assume some level of technical knowledge such as using the command line or how to edit text files.

Game Commands and Game Options as two pages of the Game Manual which replaces the current Client Manual. They provide the exhaustive list of all commands and options, grouped semantically with the most useful groups coming first. This could go with pages documenting where to find data files, saves, installed modpacks, etc; basically a description of the more technical part of the game (without going into the ruleset and tileset syntax, which lives in yet another place).

We would then have another chapter of the manual dedicated to the server. There isn't much left: an introduction to what the server is, documentation of command line arguments, and authentication support. Eventually information about setting up a  wasm client could be added in the same area. #1304 is more or less an intro to this chapter.
