### ISSUE TITLE
Remove Civilization -> View menu

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1236]
**Is your feature request related to a problem? Please describe.**
We have a redundant menu item that isn't really needed. Civilization -> View is the same as clicking the Map View icon on the top function bar.

**Describe the solution you'd like**
Remove the menu as its no longer needed and redundant.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by daavko** [comment]
The `Units`, `Players`, `Cities`, `Economy`, and `Research` items in that same menu are also redundant, as they can be opened by clicking on the corresponding item on the top function bar

**Comment by lmoureaux** [comment]
`Tax rates` and `Government` are redundant as well. I think we should keep the menu until we can remove the menu bar completely.

**Comment by jwrober** [comment]
Per notes above, closing.
