### ISSUE TITLE
Merge overview and graphics tab in options

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#1241]
**Describe the bug**
There isnt a clear, demarcation between the two tabs, both refer to the appearance in the mapview.  

**To Reproduce**
1. Go to options
2. Get confused as to why some options are hidden in a separate tab.

**Expected behavior**
Each tab has a clear topic it handles. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30164619/184031294-723c75c3-1a33-4542-9959-f0596a1a7fbb.png)
![image](https://user-images.githubusercontent.com/30164619/184031343-0fa4f2d2-a94c-4c0e-9df3-39f8dd2fea06.png)

**Platform and version (please complete the following information):**
- master

**Comment by lmoureaux** [comment]
`Overview` is about the minimap.

**Comment by pranavtifr** [comment]
Ooh. Might make sense to just rename it then ? We need to clarify that Graphics is just about the view mode, and overview is about the minimap.

**Comment by lmoureaux** [comment]
I fully agree that the tabs need work :joy:
