### ISSUE TITLE
Highlight active tab in options window in classic theme

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#1243]
**Describe the bug**
In the classic theme, the active tab isnt highlighted enough

**To Reproduce**
1. Go to options
2. Active tab isn't immediately spottable

**Expected behavior**
You can clearly see the active tab. With maybe a slight brightness shift on the tab colour. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30164619/184031848-3dbc09c0-26a3-4307-ae98-7cd5fa2e4962.png)

**Platform and version (please complete the following information):**
- master

**Comment by lmoureaux** [comment]
I would love if someone could take care of the classic theme
