### ISSUE TITLE
Civ menu -> Space Ship is one word

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1247]
**Describe the bug**
If you look at the Civilization menu, the entry for "Spaceship" is two words, should be one

**To Reproduce**
1. Open a game
2. Click on the Civilization menu
3. Notice misspelled word.

**Expected behavior**
Good spelling :)

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-beta3
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Found in reviewing spelling for the new client manual

**Comment by pranavtifr** [comment]
Hmm, I see only a single word (in the code too).

**Comment by jwrober** [comment]
Ok I must be going blind. When documenting the menus for the client manual I took a note about the misspelled word. Closing...
