### ISSUE TITLE
AutoRevision needs to support stable releases

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1252]
**Is your feature request related to a problem? Please describe.**
When we tag a release, a process call AutoRevision runs to update the Freeciv21 code with the tagged version automatically. Right now we have been tagging unstable Alpha and Beta releases and are close to having a stable release.

**Describe the solution you'd like**
The general rule of a stable release is the tag does not have a dash (`-`) in with a `patch` release text provided.  Today our releases are like this: `v3.0-beta.3` and AutoRevision parses that out a `v3.0.base10(git hash)-beta.3`. We need AutoRev to recognize that if the tag string ends at `.0` and does not have a dash (`-`) with subsequent text that this is a stable release. When that is detected then AutoRevision only gives us a version of `vX.0` with not `base10(git hash)` or anything else.

**Describe alternatives you've considered**
It was discussed to potentially leave the `base10(git hash)` as part of any version, however the developers decided for stable releases we don't want that there, only for unstable point releases.

**Additional context**
We are near a full v3.0!

**Comment by lmoureaux** [comment]
> We need AutoRev to recognize that if the tag string ends at .0 and does not have a dash (-) with subsequent text that this is a stable release.

I don't think the `.0` part is a necessary condition, because we'll have `v3.1` one day
