### ISSUE TITLE
Horizontal borders are not being draw on hex tiles

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1253]
**Describe the bug**
Horizontal borders are not being draw on hex tiles

**To Reproduce**
1. Open client
2. Load or start a game that uses hex tiles
3. See error in screen shot below

**Expected behavior**
All border lines are drawn

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/184434220-7887bd9f-4054-4221-a397-c02be5ddb109.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: Master at a recent hash -- 4634cee5c8813b314c3e99866f159d58d2748753
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
We've made a number of changes to the underlying map drawing code, seem to have introduced a bug

**Comment by lmoureaux** [comment]
This is 4634cee5c8813b314c3e99866f159d58d2748753
