### ISSUE TITLE
Incomprehensible string in helpdata.txt

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1256]
I don't understand the first sentence in this paragraph:
https://github.com/longturn/freeciv21/blob/8854672a801aad805648a8fe45d2c308fccecb39/data/helpdata.txt#L155
The English looks fine, but I have no idea what it's trying to say.

**Comment by lmoureaux** [comment]
This one is also hard to translate: https://github.com/longturn/freeciv21/blob/8854672a801aad805648a8fe45d2c308fccecb39/data/helpdata.txt#L807
In particular, I don't understand what is meant by "are constructed much like city improvements".

**Comment by lmoureaux** [comment]
I also don't understand this: https://github.com/longturn/freeciv21/blob/8854672a801aad805648a8fe45d2c308fccecb39/data/helpdata.txt#L916-L917

**Comment by jwrober** [comment]
I'll have a look when you are done reading :)

**Comment by lmoureaux** [comment]
https://github.com/longturn/freeciv21/blob/8854672a801aad805648a8fe45d2c308fccecb39/data/helpdata.txt#L951

No longer hard-coded, we have `Fortify_Defense_Bonus` now.

**Comment by lmoureaux** [comment]
https://github.com/longturn/freeciv21/blob/8854672a801aad805648a8fe45d2c308fccecb39/data/helpdata.txt#L1374-L1378
Not with Freeciv21.

**Comment by lmoureaux** [comment]
https://github.com/longturn/freeciv21/blob/8854672a801aad805648a8fe45d2c308fccecb39/data/scenarios/tutorial.sav#L102
The button has moved.
