### ISSUE TITLE
Change default fonts to more sane values

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1273]
**Is your feature request related to a problem? Please describe.**
With a fresh install or if you delete the `freeciv-client-rc-3.0` file, the default fonts are a bit ridiculous. Here are the defaults on my Ubuntu KDE Linux laptop:

* `gui_qt_font_chatline="Liberation Mono,20,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_city_names="Liberation Sans,22,-1,5,75,0,0,0,0,0"`
* `gui_qt_font_city_productions="Ubuntu,20,-1,5,75,0,0,0,0,0"`
* `gui_qt_font_default="Liberation Sans,22,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_help_text="Liberation Sans,20,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_notify_label="Liberation Mono,20,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_reqtree_text="Ubuntu,22,-1,5,75,0,0,0,0,0"`

and produces screen shots like these:
![image](https://user-images.githubusercontent.com/23037938/184557669-8fa4e733-b84f-42a7-991b-b820db49a427.png)
![image](https://user-images.githubusercontent.com/23037938/184557674-979cf685-0ee2-4e32-9cbe-b1698c051e03.png)
![image](https://user-images.githubusercontent.com/23037938/184557679-6b9b6de0-0269-40e7-a5da-06a83ac8aa9d.png)
![image](https://user-images.githubusercontent.com/23037938/184557684-2abd4cba-5475-427c-a80e-e19be5b065b5.png)
![image](https://user-images.githubusercontent.com/23037938/184557687-5b78bd38-fb9e-464f-ad62-97fa0dd64081.png)

These fonts are overpowering and way too big.

**Describe the solution you'd like**
I would like to suggest a default set of fonts like this list:

* `gui_qt_font_help_label="Sans Serif,12,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_chatline="Monospace,12,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_city_names="Sans Serif,14,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_city_productions="Sans Serif,14,-1,5,75,1,0,0,0,0"`
* `gui_qt_font_default="Sans Serif,12,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_help_text="Sans Serif,12,-1,5,50,0,0,0,0,0"`
* `gui_qt_font_notify_label="Sans Serif,12,-1,5,75,0,0,0,0,0"`
* `gui_qt_font_reqtree_text="Sans Serif,12,-1,5,50,1,0,0,0,0"`

and produces screen shots like these:
![image](https://user-images.githubusercontent.com/23037938/184557772-8598b3ce-4ae1-4549-ae6f-b807e71d7778.png)
![image](https://user-images.githubusercontent.com/23037938/184557776-c328ae34-2906-4d2d-bcc9-57aa687ad2f7.png)
![image](https://user-images.githubusercontent.com/23037938/184557780-da2126cc-6990-47a6-83a9-2245930787ec.png)
![image](https://user-images.githubusercontent.com/23037938/184557789-d4dec33f-301e-4c36-a6fa-634260d1cc60.png)
![image](https://user-images.githubusercontent.com/23037938/184557796-a2cd005a-1ea3-43fb-887c-a04b8cb55f0f.png)

**Describe alternatives you've considered**
I did spent some time playing around with different fonts and size. These seem to fit the best, don't look horrible and are easy to read. They are a bit simple and definitely not sexy, but better than the current defaults.

**Additional context**
This certainly is contributing to #115

**Comment by lmoureaux** [comment]
Hard-coded defaults:

* Default font, help text, city names:
  ```cpp
  sl << QStringLiteral("Segoe UI") << QStringLiteral("Cousine")
     << QStringLiteral("Liberation Sans") << QStringLiteral("Droid Sans")
     << QStringLiteral("Ubuntu") << QStringLiteral("Noto Sans")
     << QStringLiteral("DejaVu Sans") << QStringLiteral("Luxi Sans")
     << QStringLiteral("Lucida Sans") << QStringLiteral("Trebuchet MS")
     << QStringLiteral("Times New Roman");
  ```
* Notify label, chat line
  ```cpp
  sl << QStringLiteral("Cousine") << QStringLiteral("Liberation Mono")
     << QStringLiteral("Source Code Pro")
     << QStringLiteral("Source Code Pro [ADBO]")
     << QStringLiteral("Noto Mono") << QStringLiteral("Ubuntu Mono")
     << QStringLiteral("Courier New");
  ```
* City production, tech tree
  ```cpp
  sl << QStringLiteral("Arimo") << QStringLiteral("Play")
     << QStringLiteral("Tinos") << QStringLiteral("Ubuntu")
     << QStringLiteral("Times New Roman") << QStringLiteral("Droid Sans")
     << QStringLiteral("Noto Sans");
  ```

The sizes are either 16 or 14, with some DPI scaling. We probably see huge fonts because we're doing the DPI scaling twice (once in Qt internally and once by hand).

This issue would be a good opportunity to choose good fonts and ship them instead of relying on what the system provides. We need at least a monospace font and a sans font.

**Comment by jwrober** [comment]
I suggest these defaults:

- Default -- Sans Serif size 12, normal
- Notify Label -- Sans Serif size 12, bold
- Help Label -- Monospace size 12, italic
- Help Text -- Monospace size 12, normal
- Chatling -- Monospace size 12, normal
- City Names -- Sans Serif, size 14 normal
- City Productions -- Sans Serif, size 14 bold
- Requirements Tree -- Sans Serif, size 12 italic

I went with monospace in the help because I personally think it is easier to read with the way we do formatting with the static text and then the generated text from the ruleset.

**Comment by jwrober** [comment]
Associated with #1292 - Bundle our own fonts
