### ISSUE TITLE
Going from Observe to Take loses buttons on top bar

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1289]
**Describe the bug**
If you open a single player game and do a global observe, you correctly lose access to some buttons on the top bar such as research, economy and tax rates. If you observe 

**To Reproduce**
1. Open a single player game
2. In the chat line do an `/observe`
3. Notice that Research, Economy and Tax Rates disappear -- good
4. In the chat line do an `/observe <player>`
5. Notice that you get back Tax Rates, but not Research or Economy -- bad
6. In the chat line do a `/take <player>`
7. Notice that you don't get back Research or Economy -- bad

The same thing happens if you go from global observe back to `/take`. If I do an `/observe <player>` it works as expected I keep all the buttons on the top bar. So it is something with global observe.

**Expected behavior**
We don't lose buttons into cyberspace.

**Screenshots**
I didn't capture any. You can see it for your self pretty easily.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: Master at https://github.com/longturn/freeciv21/commit/68b506389dd068745363852307bb4f954989acf9
 - Ruleset/Longturn game (if applicable): Classic, but not sure its relevant

**Additional context**
I found it while playing around and testing PR #1287

**Comment by lmoureaux** [comment]
Finally someone notices and files an issue :sweat_smile: (I had seen this before but forgot about it)

**Comment by jwrober** [comment]
The same thing happens between `/take` and does not have to involve `/observe`
