### ISSUE TITLE
When the chat widget is collapsed, resizing the window causes the widget to grow unexpectedly

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1290]
**Describe the bug**
If you have the chat widget bar minimized and then switch themes, the bar gets really huge.

**To Reproduce**
1. Open a game
2. Move the chat widget to someplace you like and then minimize it
3. Open local options and pick another theme

**Expected behavior**

**Screenshots**
On NightStalker before
![image](https://user-images.githubusercontent.com/23037938/184999243-e444e32a-9910-4c70-a20d-01440dbb1a38.png)

On System after
![image](https://user-images.githubusercontent.com/23037938/184999321-f9a8e181-59f4-4961-8d52-6f78e45381fb.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master at https://github.com/longturn/freeciv21/commit/68b506389dd068745363852307bb4f954989acf9
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
I discovered this while testing PR #1287

**Comment by lmoureaux** [comment]
It likely gets resized but not expanded

**Comment by lmoureaux** [comment]
This is happening because the map widget gets resized. One can also trigger it by simply resizing the window.
