### ISSUE TITLE
Change "(b)uild city" command to "(f)ound city" 

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1297]
**Is your feature request related to a problem? Please describe.**
After a lengthy discussion on Discord around the use of the word "build" vs "found" when referencing the creation of a new city, we settled on using the word "found". The documentation in `helpdata.txt` and RTD uses a mix of the two words and the game itself uses "build city" as the command action enabler for a Settler in the Work Menu.

**Describe the solution you'd like**
Change the language in the game interface, rulesets and documentation to consistently use the word "found" when discussing the creation of cities.

**Describe alternatives you've considered**
Could keep things the way they are, has been this way for some time.

**Additional context**
This came up as part of a text review from PR #1284

**Comment by lmoureaux** [comment]
I would favor keeping "b" as the shortcut.

**Comment by jwrober** [comment]
I opened this before we had the Discord discussion about biuld/found. I am ok leaving it as is too.
