### ISSUE TITLE
Crash in while pathfinding in goto

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#1315]
**Describe the bug**
A random crash appeared in the wild and cast confusion on the devs. Devs hurt themselves in confusion. 

**To Reproduce**
A clear way to reproduce the crash hasnt been found yet. Some discussions on discord, point towards the possibility of the source tile being nullptr  in pathfinder_private::attempt_move. It was postulated that having an unknown tile in between the path caused the crash. We were unable to reproduce it. The crash was possibly introduced #1312.  

**Expected behavior**
No crashes, and possibly no pokemon references in the future. 

**Screenshots**
I managed to grab a bt before losing the condition for the crash forever by trying to move another unit. 
![image](https://user-images.githubusercontent.com/30164619/186461232-7a53bada-4a85-4188-9a71-126d01e1d493.png)

**Platform and version (please complete the following information):**
- was seen in the branch of #1312, which is now merged to master. I believe the bug persists in master.

**Comment by lmoureaux** [comment]
> towards the possibility of the source tile being nullptr

Not the source tile, but its terrain. Tiles that were never seen have null terrain.
