### ISSUE TITLE
Auto center units option does not do anything

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1316]
**Describe the bug**
If you have the local option "Auto center on units" checked, the client does not actually auto center on the selected unit.

**To Reproduce**
1. Open a saved game with multiple units available needing moves
2. Ensure the option is checked in your settings
3. Pick a unit and move it or click done on the control bar
4. Notice that another unit has been selected, but the map didn't move

**Expected behavior**
I expect the map to move to center the unit on the screen with this option enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/186518468-36f063dd-4d55-4c76-bb5b-40e580a16263.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-beta3
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by lmoureaux** [comment]
The option works, but gets unexpectedly reset if:
* It is disabled on startup
* You enable it
* You attack a city

**Comment by lmoureaux** [comment]
More detailed analysis: `stored_autocenter` is set to `false` initially, and never updated to something else (at least in the way I tested). When the mouse button is released, `gui_options->auto_center_on_unit` gets updated to the value of `stored_autocenter` and everything is disabled again.
