### ISSUE TITLE
INSTALL is out of date

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1330]
**What should be documented? Is there something wrong in the documentation?**
In the root of the source tree we have a plain text `INSTALL` file. It points to an out of date URL for the RTD version as well as the text is out of date.

**Do you have suggestions?**
Use the RTD `install.rst` to update `INSTALL`

**Comment by lmoureaux** [comment]
What about sending users to the website instead?

**Comment by jwrober** [comment]
I am ok with that as well. The URL in the file is incorrect though.
