### ISSUE TITLE
Assertion pcity->surplus[O_SHIELD]

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#1332]
While playing, I got this:

`Assertion pcity->surplus[O_SHIELD] >= 0 failed`
`Please report this message at https://github.com/longturn/freeciv21/issues`

Savegame and ruleset are attached

(this is actually RAR but Github rejected it so I changed the extension)
[SIM30-fc21.zip](https://github.com/longturn/freeciv21/files/9437462/SIM30-fc21.zip)

(this is a genuine ZIP)
[sim-test.zip](https://github.com/longturn/freeciv21/files/9437465/sim-test.zip)

**Comment by lmoureaux** [comment]
When loading the save in a debug build, I get:
```
[critical] freeciv21-server (/home/louis/Personal/freeciv21/server/sanitycheck.cpp:92) - T022: Assertion pterrain->mining_result == pterrain failed
[critical] freeciv21-server (/home/louis/Personal/freeciv21/server/sanitycheck.cpp:92) - T022: (  46,   27) at "Tundra"
```

Some more details about the assertion reported in the original message:
```
[critical] freeciv21-server (/home/louis/Personal/freeciv21/server/cityturn.cpp:2316) - T022: Assertion pcity->surplus[O_SHIELD] >= 0 failed
```

**Comment by lmoureaux** [comment]
This is caused by two AI cities building `==Building complete==` while producing negative shields.

**Comment by lmoureaux** [comment]
These two cities don't manage to disband their units (doing it manually works). In such a case, normally a citizen gets killed instead (one per shield!), but a bug prevents *that* from happening. And would it happen, the assertion would still occur.

**Comment by lmoureaux** [comment]
The ruleset lacks the [`missing_unit_upkeep`](https://freeciv.fandom.com/wiki/How_to_update_a_ruleset_from_2.6_to_3.0#Missing_unit_upkeep_consequences) section in `units.ruleset`, thus no action is considered when attempting to disband units for upkeep reasons. How was it produced? Is this something missing from `ruleup`?
