### ISSUE TITLE
Move macos/info.plist to dist/info.plist

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1341]
**Is your feature request related to a problem? Please describe.**
We use `macos/info.plist` as part of the macOS packaging process. This file really should be in `dist/` along with the other distribution files.

**Describe the solution you'd like**
Move the file, remove the `macos` directory and update the `build.yaml` file to capture the change.

**Describe alternatives you've considered**
None

**Additional context**
I found this as part of working on #916

**Comment by lmoureaux** [comment]
There's also a related `patches` directory

**Comment by jwrober** [comment]
> There's also a related `patches` directory

Yes that is also true. Where should those go? `dist` or `dependencies`?

**Comment by lmoureaux** [comment]
I think `dist/wasm` would fit better because the patches are specific to wasm
