### ISSUE TITLE
Running server without controlling terminal uses 100% cpu

### ISSUE THREAD

**Issue by keis** [longturn/freeciv21#1342]
**Describe the bug**
Running server without controlling terminal uses 100% cpu

**To Reproduce**
1. Start server without a controlling tty with e.g "build/freeciv21-server < /dev/null"
2. Watch CPU time go brrrrrrr

**Expected behavior**
Not using all the CPU when idle

**Platform and version (please complete the following information):**
 - OS: Fedora Linux 36
 - Freeciv21 version: v3.0-beta.3 
 - Ruleset/Longturn game (if applicable): Not applicable. Loading a game or not makes no difference.

**Additional context**
Not having a terminal attached is a common situation when managing the server with a init-script / systemd unit / docker / etc

**Comment by lmoureaux** [comment]
Thanks for reporting @keis!
