### ISSUE TITLE
Allow easier show/hide units

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#1351]
Currently, in order to hide units (to view terrain) you need to do a lot of clicking. 

Suggestion:
1. Move the feature to the View menu (as it was in GTK)
and/or
2. Create a keyboard shortcut for this

**Comment by lmoureaux** [comment]
Does Gtk have a shortcut?

**Comment by Corbeau-1** [comment]
> Does Gtk have a shortcut?

No.
