### ISSUE TITLE
Not really a bug but... Clumsy screen management

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#1357]
Screenshot below.

Issues:

1. Messages window partially covered by Minimap, neither can be moved. 
2. I recall finding a way to partially minimise the Minimap, but I forgot where it is and something like that should be instantly visible
3. Chat can be mostly minimised, but even like this it keeps getting in the way. I can move it completely off-screen to the right, but doesn't feel thought-through. Ideally, should be switched on and off like Messages window.
4. I don't think the Turn Change button needs to be this big. Also, a more natural place would be next to turn counter (top left corner)

![image](https://user-images.githubusercontent.com/25233743/188426174-1a9a9d57-71a0-4fb4-aa87-04f642d2bac2.png)

**Comment by lmoureaux** [comment]
All fixed in beta4, please upgrade.
