### ISSUE TITLE
Document all game shortcuts

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1359]
**What should be documented? Is there something wrong in the documentation?**
In the game interface, there are a large collection of keyboard shortcuts that player's can use. We need to document the defaults.

**Do you have suggestions?**
There is a client manual that can be used to add this information to. Eventually to be merged into a "game manual".

**Comment by lmoureaux** [comment]
We already have Help > Shortcuts, maybe there are some missing entries? Otherwise I'd close this as a dup of #1264.

**Comment by jwrober** [comment]
I was originally thinking of putting this into the game/client manual. There is also #656 to not keep the defaults static, but to also put in help what a person has set for themselves. So yes, I guess this is a duplicate.
