### ISSUE TITLE
Right-clicking within the Units widget closes it and doesn't change appearance of "Units" button in top bar

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1393]
**Describe the bug**
If you right-click within the Units widget, it closes. It then leaves the "Units" button in the top bar in an "activated" state so you have to click it twice to open the Units widget again

**To Reproduce**
1. Open Units widget by clicking on "Units" button in the top bar
2. Observe the "Units" button has a lighter color, indicating the Units widget is open
3. Right-click within the widget (anywhere except the scrollbar, if visible)
4. Observe the Units widget closes
5. Observe the "Units" button still has a lighter color, as if the Units widget was open

**Expected behavior**
IMO it doesn't make sense to close a widget by right-clicking. Especially the ones opened via the top bar. It should either have a "X" button, or it should be toggled only via the top bar button.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 4
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**

**Comment by jwrober** [comment]
I can reproduce it as well in `master`.
