### ISSUE TITLE
No clear way to close the "which transport do you want the unit to load into" dialog

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1394]
**Describe the bug**
If you have multiple available transports and you attempt to load a unit via the "Load" command, a small dialog opens, listing all available transports. There's no way to close this dialog, other than choosing one of the options.

**To Reproduce**
1. Have 2 or more transports
2. Have a unit that can load onto those transports on the same tile
3. Use the "Load" command on the unit
4. Observe a dialog opens
5. Observe you have no way to close this dialog without choosing one of the options

**Expected behavior**
This dialog needs to be close-able, either via Esc or via a "X" button. Both would be ideal.

**Screenshots**
The dialog in question
![freeciv21-client_EKZhh00zun](https://user-images.githubusercontent.com/7669061/193455983-503d472d-39f2-44b4-af73-5493342f88d6.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 4
 - Ruleset/Longturn game (if applicable): LT73Avi, it's very annoying

**Additional context**
No additional context

**Comment by jwrober** [comment]
I noticed this when I played the first Avi game as well. Thanks for opening an issue.
