### ISSUE TITLE
Giving a command to a unit inside city view activates the unit

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1395]
**Describe the bug**
When you have an active unit, open any city and give a command to any units within the city, a unit gets activated within the city view.

**To Reproduce**
1. Have a city with units in it
2. Have an active unit, doesn't have to be in the city (best tested with multiple units that haven't received a command this turn)
3. Open city view for the city
4. Give any unit a command via the right-click menu for the unit
5. Observe a unit gets activated (most of the time, it's the "next active unit in sequence", but sometimes it's the unit that received the command)

**Expected behavior**
Units shouldn't activate while in city view after receiving a command. The only exception to this should be the "Activate unit" command, which should either mark the unit as active so it can be chosen automatically when cycling through units, or it should close the city view. Best would probably be to have two separate items, "Activate unit" and "Activate unit and close city view".

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 4
 - Ruleset/Longturn game (if applicable): LT73Avi, again it's very annoying

**Additional context**
No additional context

**Comment by jwrober** [comment]
I thought we had an issue for this already, but apparently we don't. Thanks for opening, it is annoying.
