### ISSUE TITLE
Label for "Nations" button in top bar disappears after a diplomatic meeting

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1396]
**Describe the bug**
If a diplomatic meeting gets activated, the "Nations" button changes to reflect this by changing the label. This is fine, working as intended. After the meeting concludes, it doesn't return to its original state and has an empty label. That's the bug.

**To Reproduce**
1. Observe the "Nations" button in top bar has the text "Nations"
2. Activate a diplomatic meeting with another nation
3. Observe the "Nations" button in top bar changes text to the nation's name (working as intended)
4. Conclude the diplomatic meeting by either accepting or rejecting it
5. Observe the "Nations" button in top bar now has no label

**Expected behavior**
The "Nations" button should go back to its original label after all diplomatic meetings are concluded.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 4
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by jwrober** [comment]
I can recreate in `master` as well. Good catch.
