### ISSUE TITLE
/settting dificulty is strange

### ISSUE THREAD

**Issue by mir3x** [longturn/freeciv21#140]
/team "AI*16" "Team 20"'
/team: Player AI*16 set to team Team 20.  ( works)

/hard "AI*16"
/hard: No player by the name of '"AI*16"'. (doesnt work)

/hard AI*16
/hard: Player 'AI*16' now has AI skill level 'Hard'. (work)

If player will be named AA BB it wont be possible to put him on team without ""

**Comment by mir3x** [comment]
something  ate  * (stars) and made text italic :D

**Comment by lmoureaux** [comment]
Closed by #142
