### ISSUE TITLE
data/screenshot.png shows a citybar style we don't include in game

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1413]
**Describe the bug**
The `data/screenshot.jpg` file that we show in `README.md` shows a citybar style that we don't ship with the game.

**To Reproduce**
1. Open any game (new, saved, etc.)
2. Cycle through the available city bar styles from the view menu
3. Notice none of them match what is shown in the image.

**Expected behavior**
I suggest we either show a screenshot of the polished or traditional city bar style.

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: all - n/a
 - Freeciv21 version: n/a
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
None

**Comment by lmoureaux** [comment]
It's a screenshot from 2.6 Gtk using the equivalent of `simple` with production and growth hidden. Should still be reproducible in fc21 (or close enough).

**Comment by lmoureaux** [comment]
> It's a screenshot from 2.6 Gtk using the equivalent of `simple` with production and growth hidden. Should still be reproducible in fc21 (or close enough).

Confirmed
![image](https://user-images.githubusercontent.com/22327575/201543561-166b73bc-b16b-4f58-84f1-9f6e53fe5aec.png)
