### ISSUE TITLE
Get unique sprites for LTT/LTX buildings and wonders

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1417]
**Is your feature request related to a problem? Please describe.**
As we get closer to hosting LT games in freeciv21, would be great if we could have unique sprites for the different buildings and wonders we support in our online games for the tier-1 tilesets Amplio2 and Hexemplio at a minimum

**Describe the solution you'd like**
LTT missing sprites (with the fallback in parenthesis)

* Merchantile Exchange (Bank)
* Amphitheater (Colosseum)
* SDI Defense II (SDI Defense)
* SDI Defense III (SDI Defense)
* Verrocchio's Workshop (Leonardo's Workshop)
* Trade Company (Marco Polo's Embassy)
* Atlantic Telegraph Company (University)
* Mausoleum of Mausolos (Oracle)
* Hal Saflieni Hypogeum (Oracle)

LTX missing sprites

* Academy (University)
* Occupation Government (Barracks I)
* Merchantile Exchange (Bank)
* Amphitheater (Colosseum)
* Workshop (Factory)
* Workshop (Port Facility)
* SDI Defense II (SDI Defense)
* SDI Defense III (SDI Defense)
* Verrocchio's Workshop (Leonardo's Workshop)
* Trade Company (Marco Polo's Embassy)
* Atlantic Telegraph Company (University)
* The Paris Agreement (University)
* Global Emission Union (University)
* Mausoleum of Mausolos (Oracle)
* Terracotta Army (Sun Tzu's War Academy)
* School of Baudhayana Sutras (Oracle)

**Describe alternatives you've considered**
What we have now works, just think we can come up with some unique sprites to enhance the interface.

**Additional context**
Came up as part of working on #941

**Comment by lmoureaux** [comment]
Do all units already have graphics?

**Comment by jwrober** [comment]
That is on my list to review. I think that is probably a diff issue.

**Comment by jwrober** [comment]
PR 1423 got most of them. This is what is left to figure out:

LTT missing sprites (with the fallback in parenthesis)

* SDI Defense II (SDI Defense)
* SDI Defense III (SDI Defense)

LTX missing sprites

* Occupation Government (Barracks I)
* Port of Guangzhou (Port Facility)
* SDI Defense II (SDI Defense)
* SDI Defense III (SDI Defense)
* The Paris Agreement (University)
* Global Emission Union (University)
