### ISSUE TITLE
The quit dialog is decoupled from the client window

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1422]
**Describe the bug**
The quit dialog can get disconnected from the client window

**To Reproduce**
I don't know how to reproduce it at this time. I am on dual-screen so that might have something to do with it. The screenshot taken actually started with the client on one screen and the dialog on the other. I moved the client window over to the same screen to get the picture.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/195951074-a7994f45-95e9-40cd-b192-3fbd3b8ff5a5.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-alpha4+
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by lmoureaux** [comment]
Almost certain it comes from this manual positioning in `hudwidget.cpp`:
```cpp
  p = QPoint((parentWidget()->width() - w) / 2,
             (parentWidget()->height() - h) / 2);
  p = parentWidget()->mapToGlobal(p);
  move(p);
```

**Comment by lmoureaux** [comment]
I don't have a dual-monitor setup atm, but you could try to comment out the `move(p)` line… It doesn't seem to do anything on Linux (KWin Wayland).

**Comment by jwrober** [comment]
That does not help. The issue comes up on a single monitor too. On single monitor set the dialog may go to the center of the screen, but if you click on keep playing and then try to close the app it will move to the upper left corner and stay there.

**Comment by lmoureaux** [comment]
Was able to eventually reproduce by repeatedly opening and closing the dialog (it's a bit random).
