### ISSUE TITLE
Aviation tileset broken in beta.5

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1429]
**Describe the bug**
The Aviation tileset can no longer be loaded in beta.5.

**To Reproduce**
1. Install Aviation from fcmp
2. Try to load it

```
[info] freeciv21-client (/home/louis/freeciv/freeciv21/client/tilespec.cpp:984) - Loading tileset "aviation".
[critical] freeciv21-client (/home/louis/freeciv/freeciv21/client/tilespec.cpp:1015) - Assertion nullptr != tileset failed
[critical] freeciv21-client (/home/louis/freeciv/freeciv21/client/tilespec.cpp:1015) - Please report this message at https://github.com/longturn/freeciv21/issues
```

**Expected behavior**
The tileset loads.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-beta5 + unrelated own commits
 - Ruleset/Longturn game (if applicable): `aviation`

**Additional context**
Likely related to the changes in the folder structure.

**Comment by jwrober** [comment]
Which Aviation on the fcmp? I see two of them there.

**Comment by jwrober** [comment]
I was able to start a local aviation game with the tileset

**Comment by lmoureaux** [comment]
Reproduced on another system.
```
[debug] freeciv21-client (/home/louis/Personal/freeciv21/client/tilespec.cpp:2053) - spec file amplio2/units.spec
[debug] freeciv21-client (/home/louis/Personal/freeciv21/utility/shared.cpp:723) - Could not find readable file "amplio2/units.spec" in data path.
[debug] freeciv21-client (/home/louis/Personal/freeciv21/utility/shared.cpp:723) - Could not find readable file "p񵗛U.tilespec" in data path.
[critical] freeciv21-client (/home/louis/Personal/freeciv21/client/tilespec.cpp:1015) - Assertion nullptr != tileset failed
[critical] freeciv21-client (/home/louis/Personal/freeciv21/client/tilespec.cpp:1015) - Please report this message at https://github.com/longturn/freeciv21/issues
[fatal] freeciv21-client (/home/louis/Personal/freeciv21/client/tilespec.cpp:1015) - Failed to re-read the currently loaded tileset.
```

**Comment by jwrober** [comment]
Ok I can recreate from outside by build env
```
usr/bin/freeciv21-client -t aviation
[critical] freeciv21-client - Can't find spec file "amplio2/units.spec".
[critical] freeciv21-client - Can't load requested tileset aviation!
```

**Comment by jwrober** [comment]
and... This is expected behavior now. With the move of the units to `misc`, we discussed on discord to author a tileset breaking changes readme for tileset authors. SnF will need to update Aviation to work with the new setup. Small change on his part really. I'm inclined to close this issue as won't fix, but document.

**Comment by lmoureaux** [comment]
Could we add a compatibility file? A symlink or a file that merely `*include`s the new one?

**Comment by jwrober** [comment]
That's a good idea. I'll do that and document.
