### ISSUE TITLE
You were rejected from the game: Invalid username 'Hans_Lemurson'

### ISSUE THREAD

**Issue by HansLemurson** [longturn/freeciv21#1466]
**Describe the bug**
When attempting to start a new game, I get the message:

> You were rejected from the game: Invalid username 'Hans_Lemurson'

**To Reproduce**
1. Be an unfortunate soul such as myself
2. Failing that, change your username in the options menu to 'Hans_Lemurson'
3. Attempt to start a new game
4. Have the validity of your existence questioned by an uncaring machine that has a problem with your name.

**Expected behavior**
It should accept me for who I am!
Or at least, not be so stringent about underscores being included in a name string.

**Screenshots**
![image](https://user-images.githubusercontent.com/10428933/201471393-6bd546b3-6b15-49e2-a7ab-2d345c16253e.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0.783381.5-beta
 - Ruleset/Longturn game (if applicable): Not applicable

**Additional context**
On one computer (running Linux), changing my name to "HansLemurson" (no underscore) seems to have made the problem go away.
But on my current computer(Win10), changing the name seems to just cause FC21 to freeze then crash after attempting to start a new game.  I suspect that's a secondary error that is revealed now that a valid name is chosen.

It also doesn't seem to use the new user name unless you save the change to a file.  Simply choosing "apply" or "ok" will still make it reject the old invalid name.  But I think that's also a separate issue.  I'm gonna have to make a lot of issues, aren't I?

**Comment by lmoureaux** [comment]
What an idea to use an underscore where you could have chosen HånsĻémuršỏn

**Comment by HansLemurson** [comment]
It is not worthy of my T̴̂͑͘͜R̵̛͔̳̜̣̹̮̈̌Ừ̷̢͖͚͔̖͖̃͝Ë̸̬̳̼̤́͛̏͛ ̷̮͋̇̇̃͜͝ͅͅN̴̼̱̬͔̄ͅA̵͎̩̲̣͎̰̒M̴͉̪͙͙͔̺͐́̽Ë̶̩͑͠
