### ISSUE TITLE
Can't open load saved game or start scenario game on start menu

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1485]
**Describe the bug**
You can't open the load saved game or the start scenario game dialogs from the main start menu. Instead you go to the start new game dialog all the time.

**To Reproduce**
1. Open Freeciv21
2. Click on Load Saved Game
3. See error

**Expected behavior**
The appropriate dialog appears. This seems to be a recent regression we introduced.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: All (Windows and Linux confirmed)
 - Freeciv21 version: master branch at https://github.com/longturn/freeciv21/commit/c7889e69dc9e9a027a0a9186130de8b02c0e30be is where it was discovered. 
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
I found it while trying to test PR #1483

**Comment by lmoureaux** [comment]
First bad commit found by @psampathkumar 
![image](https://user-images.githubusercontent.com/22327575/202870749-b5915487-a4de-4da5-9988-fa4a843961da.png)
