### ISSUE TITLE
CI failing because clang-format-11 is no longer in Debian sid

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1503]
**Describe the bug**

Our CI started failing because `clang-format-11` has been removed from Debian sid, which is used by the action. We could use the opportunity to upgrade to version 14 present in Ubuntu 22.04 and current Arch Linux.

**Additional context**

Loosely related to #115, #1478

**Comment by jwrober** [comment]
Looks like we need to upgrade. Don't most of the Linux actions run on Ubuntu 22.04?

**Comment by jwrober** [comment]
Went and looked, we ask for `ubuntu-latest` and not a specific version.

**Comment by lmoureaux** [comment]
Looks like the latest versions of the action (≥4.5.0) should support even older versions: <https://github.com/jidicula/clang-format-action/releases/tag/v4.5.0>

> Looks like we need to upgrade. Don't most of the Linux actions run on Ubuntu 22.04?

No, still 20.04 until we get #1478. The `clang-format` action inherits Sid usage from the upstream `clang-format` action.
