### ISSUE TITLE
Low contrast in the chat

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1510]
**Describe the bug**

Default chat colors have low contrast.

**To Reproduce**
1. Start game
2. Send a message to yourself
3. Send a message to your allies
4. Send a message to everyone
5. Try to read what you just sent

**Expected behavior**
Text is readable.

**Screenshots**

![image](https://user-images.githubusercontent.com/22327575/202907852-e0994d3e-1158-4c4c-b4af-0dd916daab4d.png)

**Platform and version (please complete the following information):**
 - OS: Any
 - Freeciv21 version: 3.0-beta5

**Additional context**

[Report on Discord](https://discord.com/channels/378908274113904641/912500712833974322/1043894752111767562)

**Comment by jwrober** [comment]
Solarized was suggested -- https://github.com/altercation/solarized
