### ISSUE TITLE
Colorize/highlight the city growth if its negative

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1511]
**Is your feature request related to a problem? Please describe.**
If your city is consuming more food that is needed, it will lose population when the granary is empty. The counter in the city dialog in this example says 7 turns, but that is 7 turns to a smaller city, not a larger city.

![image](https://user-images.githubusercontent.com/23037938/202909643-df5386dd-e205-4177-94a6-a550053732d6.png)

**Describe the solution you'd like**
Colorize (e.g. make the text red) or highlight the value for `change in` value to bring more attention to it when growth is negative. Might consider doing the same thing for the negative food at the top.

**Describe alternatives you've considered**

**Additional context**
Came up as part of evaluating PR #1494

**Comment by daavko** [comment]
Would it be worth it to colorize negative values for all outputs?

**Comment by lmoureaux** [comment]
What exactly should be colorized: only the number, only the value, or the whole line?

**Comment by jwrober** [comment]
I'm inclined to think that "7 Turns" is in red or some color to bring your eye to it. Maybe the "(-7)" could also be in red so the player can easily identify what is going on?
