### ISSUE TITLE
Various feedback and bug reports from LT75 participants

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1517]
Some feedback from LT75 participants, grouped into an issue so we don't forget about it. No particular order, but I added checkboxes so things can potentially be tracked as completed as necessary. Also provided links to Discord where appropriate in case more context is necessary

- [x] Tech tree should look more like 2.6 GTK when using the Classic theme
  - https://discord.com/channels/378908274113904641/912500712833974322/1042818119481180200
- [x] Online status for players that's visible even if the player has clicked "End Turn"
- [x] State of "Allies Only" button in chat isn't saved between sessions, so you have to remember to click it every time
  - https://discord.com/channels/378908274113904641/912500712833974322/1044700678729240696
- [x] Inside the research button, there could be bulbs/turn and turns needed until the tech is reached. Seems like there's enough space
  - https://discord.com/channels/378908274113904641/1010150995843625040/1042352147024580628
- [x] Clicking "End Turn" doesn't provide enough visual feedback that it has been clicked this turn already
  - https://discord.com/channels/378908274113904641/1010150995843625040/1044708610510434455
- [x] Font for "Notify Label" should be monospace by default (it was monospace before, now it's sans-serif)
  - https://discord.com/channels/378908274113904641/1010150995843625040/1044711318311161979
  - https://github.com/longturn/freeciv21/blob/master/client/fonts.cpp#L179 (where it's set)
  - https://github.com/longturn/freeciv21/commit/20bdecc8e761ed897e95c1efc97f4530df43438f (commit where it was changed)
- [x] Tooltip for "Turn Done" that shows TC date and time in local time and UTC, and time left until TC
- [x] `(network exception)` is shown in the `/list connections` command output next to player names due to `closing_reason` in `connection` objects not being cleared when attaching a connecting player to an existing `connection` object
  - https://discord.com/channels/378908274113904641/912500712833974322/1044278231852908554
  - https://discord.com/channels/378908274113904641/912500712833974322/1044284621535334461
- [ ] It either shouldn't be necessary to `/take` your nation when first connecting to a game, or it should be clearly documented that you need to do so. It causes unnecessary confusion
  - https://discord.com/channels/378908274113904641/1010150995843625040/1042063542406369300

**Comment by lmoureaux** [comment]
> Clicking "End Turn" doesn't provide enough visual feedback that it has been clicked this turn already 

That's a theme issue, it's quite clear with NightStalker.

**Comment by jwrober** [comment]
I marked the "state of allies only button" to complete with PR #1574. While the value isn't saved between sessions, the default is always to be "public" at game start. The tooltip has been modified to tell the player if you are talking to "allies only" or to the "public".

**Comment by lmoureaux** [comment]
With #1595 there will be a single item remaining, it's a bigger one so I propose to open an issue for it and close this one.

**Comment by jwrober** [comment]
The last item is here #1599
