### ISSUE TITLE
CI Deprecation warning Node12 to Node16

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1521]
See this recent action output - https://github.com/longturn/freeciv21/actions/runs/3518390686

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

* actions/checkout@v2
* actions/cache@v2
* actions/upload-artifact@v2
* ilammy/msvc-dev-cmd@v1.10.0
* lukka/run-vcpkg@v10.1
* lukka/run-cmake@v10

Are all impacted

**Comment by lmoureaux** [comment]
Guess we need to bump versions
