### ISSUE TITLE
CI `save-state` and `set-output` commands are deprecated.

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1522]
See this recent action output - https://github.com/longturn/freeciv21/actions/runs/3518390686

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by lmoureaux** [comment]
`set-output` used here: https://github.com/longturn/freeciv21/blob/f43aef25b672125bcf8ab0ce102e31dc2ed5d3a5/.github/workflows/build.yaml#L204

**Comment by jwrober** [comment]
This would be resolved if #1525 is implemented.
