### ISSUE TITLE
Add folder dir to source code tarballs

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1527]
**Describe the bug**

Tarballs should have a folder at the root to avoid expanding in the user's folder.

**To Reproduce**
1. Download the latest source tarball
2. Open it with your favorite package manager
3. See many files at the root

**Expected behavior**

If the tarball is named `foo.tar.gz`, all paths inside the tarball should start with `foo/`

**Platform and version (please complete the following information):**
 - Freeciv21 version: 3.0-beta.5

**Additional context**
#1524

**Comment by jwrober** [comment]
build CI needs this added to the `git archive` commands

```
--prefix=<prefix>/
           Prepend <prefix>/ to each filename in the archive.
```
