### ISSUE TITLE
Set initial placement of national budget widget centered below top bar button

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1544]
**Is your feature request related to a problem? Please describe.**
When you click on the National Budget icon/button on the top bar the National Budget widget appears and what "feels" like a somewhat random placement and it is not where you left the dialog the last time.

**Describe the solution you'd like**
Leave it so that you can move the widget, but when it is first opened place it just below the button and centered to make it look "attached" to the national budget button. Might consider it to act like the messages widget where it is statically placed, but resizeable. If there is a way for it to open like a drawer (unfold?) from the top bar, that would be a nice visible feature to go along with it.

**Describe alternatives you've considered**

**Additional context**

**Comment by lmoureaux** [comment]
I don't think it has to be moveable or resizable, because the contents are static and you always open it from the same button.

**Comment by jwrober** [comment]
Closed via Make the national budget dialog unique #1746
