### ISSUE TITLE
Default display font is still Libertinus

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1548]
**Describe the bug**
We have a Libertinus font set as default
![image](https://user-images.githubusercontent.com/23037938/205448881-6e96b45b-e01c-4981-ad5b-9ad2bdbf53b4.png)

**To Reproduce**
1. Go to Game -> Interface options -> Font tab
2. Click Reset button
3. See error

**Expected behavior**
We have moved to Libertinus font as default set. Change to 
![image](https://user-images.githubusercontent.com/23037938/205448939-0b100e40-0458-40ce-bf34-979c581c2e50.png)

**Screenshots**
See above

**Platform and version (please complete the following information):**
 - OS: Linux, but assume all.
 - Freeciv21 version: 3.0-beta.6
 - Ruleset/Longturn game (if applicable): None

**Additional context**
Discovered while evaluating #1547

**Comment by lmoureaux** [comment]
Probably change this line to `Libertinus Serif Display`
https://github.com/longturn/freeciv21/blob/e968e3783f737cd900b780bf9042235ea311e598/client/fonts.cpp#L196
