### ISSUE TITLE
Remove unmaintained and unused themes

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1556]
**Describe the bug**

The following themes, shipped by default, haven't seen any maintenance work and are in an unknown state usability wise:
* Necrophos
* System
* TheLastLaserMaster
* Web

I would like to drop them all. We already don't ship System on Windows due to recurring issues.

From the bug reports we get, it seems most users use either Nightstalker or Classic.

**To Reproduce**
1. Check the commit log for any of the aforementioned themes
3. See not too many commits

**Expected behavior**
We ship with a selection of good themes.

**Platform and version (please complete the following information):**
 - OS: all
 - Freeciv21 version: master as of 04.12.2022

**Comment by jwrober** [comment]
Do we want to "save" them offline somewhere or just alter `CMakeLists.txt` to only install the two maintained ones? I also think the freecivweb.com uses the Web theme.

**Comment by lmoureaux** [comment]
I think wipe them. Release tarballs and original Freeciv have them if someone wants to dig them out.
We can switch the wasm client to use Classic. The Web theme has some serious issues (no arrows on combo boxes…).
We'll want to check what the client does when trying to load a nonexistent theme.

**Comment by jwrober** [comment]
Tasks

- [ ] Remove Themes
- [ ] Set WASM to use Classic
- [ ] Add a check to the theme loading code to fall back to the new defaults
- [ ] Double check that NightStalker is the default
