### ISSUE TITLE
The tutorial map is too big and has no specials

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1570]
**Describe the bug**
The tutorial comes with only 2 players. The map size is such that it takes a very long time before the players even meet each other. This doesn't make for a fun game.

It also looks like no specials are generated.

**To Reproduce**
1. Play the tutorial
2. Count how many cities you have by the time you meet the AI
3. Too many

**Expected behavior**
The tutorial is a short, condensed game that highlights the main elements of gameplay.

**Screenshots**
Map on T40:
![image](https://user-images.githubusercontent.com/22327575/206591893-0090afa8-e017-418c-9c14-aac7e20a69b4.png)
![image](https://user-images.githubusercontent.com/22327575/206592012-9b73489b-6069-4e64-84c0-f127d0028f6d.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: Roughly 3.0-beta.7
 - Ruleset/Longturn game (if applicable): Tutorial

**Comment by jwrober** [comment]
As a point of note only, the messages to all the way to T100.
