### ISSUE TITLE
Savegame load page different between classic and nightstalker themes

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1582]
**Describe the bug**
The button layout on the savegame selection and load page is different depending on the theme you are using.

![image](https://user-images.githubusercontent.com/23037938/206879467-64aacd42-ea3f-47da-a41c-fd20d8f41e00.png)

**Expected behavior**
Button layout should be consistent between themes.

**Screenshots**
See above.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-beta.7
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
Discord convo  -https://discord.com/channels/378908274113904641/1051156590264320100/1051166178879479868

**Comment by lmoureaux** [comment]
Some notes:

* `QDialogButtonBox` gets the button order from the style with [QDialogButtonBox](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/widgets/qdialogbuttonbox.h.html#QDialogButtonBox)::[ButtonLayout](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/widgets/qdialogbuttonbox.h.html#QDialogButtonBox::ButtonLayout)([q](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/widgets/qdialogbuttonbox.cpp.html#187)->[style](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/kernel/qwidget.cpp.html#_ZNK7QWidget5styleEv)()->[styleHint](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/styles/qstyle.h.html#_ZNK6QStyle9styleHintENS_9StyleHintEPK12QStyleOptionPK7QWidgetP16QStyleHintReturn)([QStyle](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/styles/qstyle.h.html#QStyle)::[SH_DialogButtonLayout](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/styles/qstyle.h.html#QStyle::SH_DialogButtonLayout), 0, [q](https://woboq.com/~codebrowser/qt5/qtbase/src/widgets/widgets/qdialogbuttonbox.cpp.html#187)))
* The first button with `AcceptRole` is considered `AcceptRole`; others are considered `AlternateRole`
* But we use the same widget style (Fusion with style sheets on top)
* The buttons are `QDialogButtonBox::Open`, `::Cancel`, and `::Ok` with roles `AcceptRole`, `RejectRole`, and `AcceptRole`, respectively
* Overall it looks like dark themes have one order and light themes the other... fun

**Comment by lmoureaux** [comment]
`Classic` gets `KdeLayout`, `NightStalker` gets `GnomeLayout`
