### ISSUE TITLE
Citizen Governor does not always update on screen when switching presets

### ISSUE THREAD

**Issue by xarxziux** [longturn/freeciv21#1586]
**Describe the bug**
Occasionally when switching between governor presets on the Governor screen, the governor status switches to disabled, which seems to indicate that it failed, but when i close the city window and re-open it, it has switched to the new presets.

**To Reproduce**
This bug doesn't always occur when changing presets but I do see it quite frequently.  I've recorded a 30-second video of it occurring on a local game which shows that it does not occur at all in one city, but happens reliably with anpther.

**Expected behavior**
That the governor will reliably update immediately when switching, and only drop to "disabled" when it can't.

**Platform and version (please complete the following information):**
MAC OS 12.6
Freecic 21 Beta 7
LT75, local game under both LT75 and default rules

**Comment by lmoureaux** [comment]
I can reproduce on Linux with current master

**Comment by lmoureaux** [comment]
Easy fix, thanks for reporting!
