### ISSUE TITLE
Minimap does not keep geometry after diplomatic meeting

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1597]
**Describe the bug**
If you resize the minimap widget, it will revert to its default geometry after a diplomatic meeting.

**To Reproduce**
1. Open a game (start one, open a saved one, do the tutorial)
2. Resize the minimap to a size of your choice.
3. Initiate a diplomatic meeting with a neighboring nation. Agree or cancel to terms.
4. See error.

**Expected behavior**
If I set it to something I want to stay put!

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-beta.7
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
The problem does not effect the messages widget if it is left open all the time. Also, if you resize the minimap the geometry is not saved between sessions.

**Comment by lmoureaux** [comment]
More context:
* The default size of the minimap depends on size of the map
* It can be resized to a very small size (even null?), hiding the buttons shown in the same panel

**Comment by jwrober** [comment]
More more context: The issue isn't related to the diplomacy screen alone. It happens if you go to any of the other views such as city, economy, nations.
