### ISSUE TITLE
Changes to `docs` only still runs all CI actions

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1601]
**Describe the bug**
We have previously set the build CI to not do a complete run when the only change is in the `/docs` directory. Doesn't seem to be working.

**To Reproduce**
1. Make changes only to the `.rst` or other content inside the `docs` directory of the repo
2. Push a PR
3. See error, all the actions run.

**Expected behavior**
Nothing defined in `build.yaml` should run.

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: n/a
 - Freeciv21 version: n/a
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
Came up as part of review of #1600

**Comment by daavko** [comment]
I'm pretty sure this is because the `pull_request` trigger in build.yaml also needs its own `paths-ignore`. Creating and editing PRs causes the `pull_request` trigger, not the `push` trigger, and they don't inherit settings from each other
