### ISSUE TITLE
Multiple clicks of tax rates button opens many instances of national budget dialog

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1602]
**Describe the bug**
If you click on the tax rates button on the top bar multiple times, many copies of the national budget dialog appear

**To Reproduce**
1. Open any game
2. Click on tax rates
3. Click on tax rates
4. Click on tax rates
5. See error, the dialog boxes may be overlapped.

**Expected behavior**
you can only open one instance of the dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/207455841-0c84d63b-464a-4d35-88a8-5cc9194af7b2.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-beta7
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**

**Comment by xarxziux** [comment]
I'm still seeing this issue in RC2, MacOS.

**Comment by jwrober** [comment]
Bummer, re-opening

**Comment by jwrober** [comment]
> I'm still seeing this issue in RC2, MacOS.

Give us a screenshot?

**Comment by xarxziux** [comment]
<img width="589" alt="Screenshot 2023-01-22 at 03 18 21" src="https://user-images.githubusercontent.com/14932450/213899022-4e45527f-574f-4224-9898-b28895581c5b.png">

Taken from LT75.

**Comment by lmoureaux** [comment]
From #1746:

> Will not be backported due to the patch complexity.

-> The fix is for 3.1 only. I would reconsider if there is a scenario where this makes playing too hard (the behavior is fancy but not broken)

**Comment by jwrober** [comment]
You beat me to this :) I was just reviewing what we put into RC2 and this was not added there. Re-closing after re-opening :/
