### ISSUE TITLE
Dialog Weirdness

### ISSUE THREAD

**Issue by xarxziux** [longturn/freeciv21#1606]
**Describe the bug**
Opening and closing the Nations, Cities, Economy or Research tabs when viewing city production causes the message, chat and minimap windows to re-open, in addition to the city windows.

**To Reproduce**
- Start a new local game using default rules.
- Build one city and click on it to open up the city production windows.
- Observe that the Chat, Messages and Minimap all disappear, to be replaced by three city-specific dialogs.
- Click one one of the Nations, Cities, Economy or Research tabs twice to open and close those windows.
- Observe that the Chat, Messages and Minimap are now visible, in addition to the three city dialogs.

**Expected behavior**
The Chat, Messages and Minimap should not be visible at the same time as the city dialogs.

**Platform and version (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Freeciv21 version: 3.0.836246.7-beta

**Comment by jwrober** [comment]
I can recreate. Interesting bug, thanks for reporting.

**Comment by lmoureaux** [comment]
I hate these bugs related to state management. This is so badly implemented to begin with

**Comment by jwrober** [comment]
is this a refactoring candidate and needs to push out from 3.0 stable?

**Comment by lmoureaux** [comment]
We'll see
