### ISSUE TITLE
Installers don't remove deleted files

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1611]
**Describe the bug**
If we remove files from the repo between releases, the binary installers do not remove them at install time.

**To Reproduce**
1. Install beta.6 (any os)
2. Install beta.7 over beta.6 (any os)
3. notice both libertine and libertinus fonts are still there. (we got rid of libertine for libtertinus between releases).

**Expected behavior**
Installers clean up dead files. The reproduce steps is just one example. We have changed icons/images in the themes and removed files that won't get removed. In the release after beta.7 we are going to get rid of dead themes that won't get removed as intended.

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: Linux .deb, macOS .dmg and Windows .exe
 - Freeciv21 version: 3.0-beta.7
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**

**Comment by lmoureaux** [comment]
I would expect `.deb` to remove files automatically. `.dmg` never get unpacked (only mounted), so I don't think it's a problem there either. This leaves Windows...

**Comment by jwrober** [comment]
I noticed it on my Linux box. Let me research more. Windows is def a problem as the installer just copies files blindly.
