### ISSUE TITLE
"Happy" is not a state in city view or city dialog

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1616]
**Is your feature request related to a problem? Please describe.**
Right now the city dialog and city view give the following city citizen "states": Celebrating, Disorder, Peace. In the city dialog we have "Content" as well. The LT community plays rulesets that need "Happy" for a turn to get to "Celebrating", but that isn't visible anywhere in the game.

**Describe the solution you'd like**
In both the city view and the city dialog we should be able to see when a city goes to "Happy" as a player manipulates the citizens to entertainers to help get a city to "Celebrate". 

**Describe alternatives you've considered**

**Additional context**
Came up as part of a Discord conversation

**Comment by lmoureaux** [comment]
The city dialog does have "Happy"
