### ISSUE TITLE
Combat info 

### ISSUE THREAD

**Issue by Mu-00** [longturn/freeciv21#1627]
Combat info does not show in messages even if activated and player is online.

**Comment by jwrober** [comment]
I can recreate, not sure what broke it. It used to work.

**Comment by lmoureaux** [comment]
Should be sent by the server as messages: https://github.com/longturn/freeciv21/commit/94f479c556815e6d46a805ddd6a621d1f1a7fbb2#diff-476b6a3a4b830286fbcad3954ec722625907f7a44bc049812d8d791b316402f4R4003

**Comment by lmoureaux** [comment]
I want this fixed for LT76 --> top priority

**Comment by Mu-00** [comment]
Regarding the popup, it seems the state is saved in the client between connects, and only lost if the client is closed. It might be it accumulates over turns if the client instance is not closed and in that case the positional info is somehow corrupted.

**Comment by lmoureaux** [comment]
The messages are emitted correctly, they're just disabled by default in Game > Messages
