### ISSUE TITLE
Small wonder luxury bonus not documented in popup text

### ISSUE THREAD

**Issue by xarxziux** [longturn/freeciv21#1656]
**Is your feature request related to a problem? Please describe.**
The General tab of the city production windows show various breakdowns of the stats such as corruption penalties, government bonuses, etc.  One piece of information missing from this is the luxury bonus from small wonders like the Hypogeum or Hanging Gardens.  These bonuses show up in the stats, but not in the tooltip, so there's no explanation of where the luxury bonus comes from.

**Describe the solution you'd like**
Adding data to the tooltip indicating where the luxury bonus comes from would make it clear what is contributing to that bonus.

**Additional context**
This is a screenshot from a local game with the LT75 ruleset of a city with the Hypogeum and Hanging Gardens built.  The luxury value is 10, which is correct, but there's no information in the tooltip saying where this value is coming from.  Logically it should say +6 from the Hypogeum and +4 from the Hanging  Gardens.

<img width="502" alt="Screenshot 2022-12-29 at 15 15 06" src="https://user-images.githubusercontent.com/14932450/209974151-23c369d0-2fae-4cc3-b8d2-f230affbd003.png">

**Comment by jwrober** [comment]
What is shown on the Citizens tab?

**Comment by lmoureaux** [comment]
Hanging Gardens makes citizens content directly, without giving luxury, but the text is also wrong in the Citizens tab
