### ISSUE TITLE
Minimap out of sync

### ISSUE THREAD

**Issue by Mu-00** [longturn/freeciv21#1657]
Clicking on the minimap does not jump you to where you click, and the frame that represents the current view in the minimap also is not where you are.
It happened for me in LT75 and is like that from start in LT76.

**Comment by jwrober** [comment]
Can you provide more details? This is why we have the templates to prompt for more information. Any screenshots, means to reproduce, version of the client? I'm in LT76 with you and am having no issues. I am running current `master` as of today. There are some fixes I think post Beta.7.

**Comment by lmoureaux** [comment]
Confirmed by multiple users, still unable to reproduce on my end. Suggestion that this is caused by device scaling seems contradicted by one affected user not using it.

**Comment by jwrober** [comment]
I turned scaling on my Kubuntu 22.04 laptop to 125% and the minimap is fine for me as well. Definitely need more details to understand this issue. I'm adding untriaged back until we have a way to reproduce.

**Comment by lmoureaux** [comment]
Observed strange results today when zooming the minimap, maybe this is related

**Comment by lmoureaux** [comment]
@wieder-fi says it happens after `/take`. Could also be when switching game (?)

**Comment by lmoureaux** [comment]
@hugomflavio found it's related to switching games. Could reproduce.
