### ISSUE TITLE
Options not saving to rc file correctly

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1658]
**Describe the bug**
There are some issues with how the game is saving varying option to the rc file.

- The rc file seems to be completely re-written at save and is not consistent on where settings are placed in the file (making any kind of diff super hard to figure out)
- If you set a custom username in the network tab, the value is not kept. The logged on user is saved and used instead. If you manually set a user id in the rc file, the game ignores it and still uses the logged on user id.
- If you change the default columns shown on the city view, on save+exit the settings are reverted back to defaults and not kept.

**To Reproduce**
Steps to reproduce the last behavior above:
1. Open any game
2. Click on city view
3. Add and remove some columns on the table
4. Save settings
5. Exit the game and come back in
6. Go back to city view
7. See the issue - all the columns are back to defaults.

**Expected behavior**
The game does what I tell it to [within reason :)]

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: Linux and Windows confirmed, assume macOS is impacted too.
 - Freeciv21 version: 3.0-beta.7
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Discord https://discord.com/channels/378908274113904641/912500712833974322/1057764915831644200

**Comment by lmoureaux** [comment]
I assume this is about `~/.local/share/freeciv21/freeciv-client-rc-3.0` (as opposed to `~/.config/freeciv21-client.ini`).

> The rc file seems to be completely re-written at save and is not consistent on where settings are placed in the file (making any kind of diff super hard to figure out)

Little we can do about this.
