### ISSUE TITLE
The sprite for Terracotta Army is missing part of the frame

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1666]
**Describe the bug**
The sprite for Terracotta Army is missing part of the frame

**To Reproduce**
1. Open a game that has the wonder (lt76teams)
2. Go to Research view and notice the image for Terracotta Army does not have a complete frame like the other wonders do.

**Expected behavior**
Our sprites have a consistent look and feel. All the other wonders are inside a "standard" frame.

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: All
 - Freeciv21 version: 3.0-beta.7+
 - Ruleset/Longturn game (if applicable): LTX mostly

**Additional context**
I made the sprite, so I'll fix it. This is mostly a reminder for me.

**Comment by lmoureaux** [comment]
Noticed a similar issue with the new Yugoslav flag
