### ISSUE TITLE
Map labels disappear in specific scenarios

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1669]
**Describe the bug**
When middle-clicking on a tile or selecting a unit (I assume "whenever a sprite is drawn on top of a tile"?), if the tile or neighboring tiles have a label, the label partially or completely disappears. It then stays that way until that part of the map gets presumably redrawn (for example by scrolling it out of view and back into view). The screenshots probably explain it the best

**To Reproduce**
1. Have a tile with a label
2. Middle-click on it or directly next to it
    - Alternatively, select a unit on it or directly next to it
4. Observe the label has partially or completely disappeared
5. Scroll the map so the label isn't visible anymore
6. Scroll back to the label
7. Observe it's now visible again

**Expected behavior**
The label should always stay where it is

**Screenshots**
Initial state
![freeciv21-client_ETcH7CUxx0](https://user-images.githubusercontent.com/7669061/210155839-9d60e498-c77c-4b45-bf78-cba365d622f9.png)
While middle-clicking
![freeciv21-client_JfkBbXB7my](https://user-images.githubusercontent.com/7669061/210155840-cdcddbc3-b1a8-4d76-a7a6-920293dea801.png)
After middle-clicking
![freeciv21-client_f550SF0102](https://user-images.githubusercontent.com/7669061/210155842-363eee45-4901-45c4-8a3b-039198354066.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: beta 7
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by lmoureaux** [comment]
Thanks for providing a reproducible example, I've seen this way too often when scrolling. I assume we have the same issue for city labels...
