### ISSUE TITLE
Flatpak/snap packaging

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#1674]
**Is your feature request related to a problem? Please describe.**
Our distribution for Linux currently includes only a Debian package for the latest Ubuntu LTS. Other/older distros are left out. We aren't included in any app store.

**Describe the solution you'd like**
Publish an official snap or flatpak on the main platform.

**Describe alternatives you've considered**
Package Freeciv21 for every possible distribution. I got one running (OpenSuse RPM) and we have an PKGBUILD for Arch, but it's a major pain (especially outdated distros). It will also not bring us to the app stores.

**Comment by jwrober** [comment]
So is the idea here to NOT provide a `.deb` package any longer and just do a snap for all Linux distros? I am not familiar with flatpack.

**Comment by lmoureaux** [comment]
It could replace the `.deb`, but we can still support it since it's well in place by now.

**Comment by jwrober** [comment]
https://phoenixnap.com/kb/flatpak-vs-snap-vs-appimage

**Comment by lmoureaux** [comment]
In practice both snap and flatpak are integrated with most modern distros.

**Comment by jwrober** [comment]
I looks like snap is on most of them including Arch, RHEL and Fedora. The last two we don't support since we don't issue an `RPM`. It looks like legacy freeciv has gone the flatpack route.

**Comment by jwrober** [comment]
Closing via #1911, #1912, #1916, and #1918
