### ISSUE TITLE
Temple of Artemis bonus is lost when selecting Citizen Governor preset

### ISSUE THREAD

**Issue by xarxziux** [longturn/freeciv21#1675]
**Describe the bug**
The Temple of Artemis bonus is not applied when selecting a CV preset in LT75.

**To Reproduce**
I can only see this bug in LT75.  I tried to replicate the same issue in a local game with LT75 rules, but it did not appear.

In LT75, with the citizen governor and citizens tabs open, if I have a preset selected I can see that I'm only getting 2 content citizens from buildings in cities with a temple.  Disabling the governor does not fix this, but by manually changing the city workers, the bonus kicks in and buildings now provide 4 content citizens.  Selecting another preset disables this issue again

**Expected behavior**
With a temple and Temple of Artemis in a city, buildings should provide 4 content citizens with the governor preset enabled.

**Screenshots**
As this is an on-going multiplayer game, I will only provide screenshots privately through Discord upon request.

**Platform and version (please complete the following information):**
-  MacOS 12.6
- FC21 Beta 7

**Comment by xarxziux** [comment]
This issue still exists in V3-RC1.

**Comment by xarxziux** [comment]
After some further testing, I have been able to reproduce this in an offline game.  These are screenshots from an offline game using LT75 rules using some manipulation of the save file to save time (hence why I have so much gold).  This city has a temple while the Temple of Artemis has already been built in another city, so I should see four content civilians from buildings.  Note that the bonus from Artemis does not show in the tooltip.  I've raised this as a separate issue.

CG preset selected.  Note that only two citizens are being made content from buildings.
<img width="1792" alt="Screenshot 2023-01-01 at 22 40 50" src="https://user-images.githubusercontent.com/14932450/210186589-92b84728-154f-4bd9-b92a-2d23a6cfe9bc.png">

CG preset disabled.  Still only 2 content.
<img width="1792" alt="Screenshot 2023-01-01 at 22 42 10" src="https://user-images.githubusercontent.com/14932450/210186616-bb18c966-a077-4933-b6e2-1e6ee034825e.png">

Deselecting 1 tile fixes the issue, and it stays fixed after reselecting.  Now we have 4 citizens content from buildings, as expected.
<img width="1792" alt="Screenshot 2023-01-01 at 22 43 19" src="https://user-images.githubusercontent.com/14932450/210186629-cd66a0ad-bc8e-4044-af93-738a09fab72c.png">
<img width="1792" alt="Screenshot 2023-01-01 at 22 47 17" src="https://user-images.githubusercontent.com/14932450/210186715-29ac3e06-102e-42a7-8f85-7feee6e81967.png">

After re-enabling the preset, the bonus is still there. ¯\_(ツ)_/¯
<img width="1792" alt="Screenshot 2023-01-01 at 22 50 58" src="https://user-images.githubusercontent.com/14932450/210186767-c1cc5520-b3ad-4764-adc9-f93da22c3707.png">

But I'm back to two if I disable it.
<img width="1792" alt="Screenshot 2023-01-01 at 22 52 48" src="https://user-images.githubusercontent.com/14932450/210186792-a945ceb6-24b7-432a-bc43-3841f4763545.png">

The four content citizens after re-enabling the governor seems to be a visual glitch.  With this same city, I can manually get +11 food, though I need the Temple of Artemis bonus for public order.
<img width="1792" alt="Screenshot 2023-01-01 at 23 01 05" src="https://user-images.githubusercontent.com/14932450/210186921-fd80623c-a521-452c-9c5f-03a6d3a36f17.png">

But a "max food" preset can only manage +9 food, even though it seems to be applying the bonus.
<img width="1792" alt="Screenshot 2023-01-01 at 23 13 42" src="https://user-images.githubusercontent.com/14932450/210187163-fcd68924-ec97-40c5-8d86-b57b5bc1f7ee.png">

Disabling the preset reverts the visual back to 2 content citizens, but doesn't change the values, showing that the preset wasn't actually applying the bonus.

**Comment by lmoureaux** [comment]
Thanks for the investigation! Could you post the saved game here? It would help ~fixing~ reproducing this strange issue...

**Comment by jwrober** [comment]
Thanks for the extra details. I also notice that at no point do you see Temple of Artemis in the popup. @lmoureaux @wieder-fi is this caused by an issue in the ruleset or something buggy in the game client?

**Comment by xarxziux** [comment]
[Artemis Glitch.sav.gz](https://github.com/longturn/freeciv21/files/10329645/Artemis.Glitch.sav.gz)

**Comment by xarxziux** [comment]
> Thanks for the extra details. I also notice that at no point do you see Temple of Artemis in the popup. @lmoureaux @wieder-fi is this caused by an issue in the ruleset or something buggy in the game client?

I've already raised this as a separate issue: https://github.com/longturn/freeciv21/issues/1656

**Comment by lmoureaux** [comment]
Thanks for the save! I suspect the two issues are related, but we'll see...

**Comment by lmoureaux** [comment]
I can fully reproduce your findings with the latest server.

**Comment by lmoureaux** [comment]
The client doesn't know about Artemis (in some sense; it can see it in the city it's in) and is making wrong deductions when enabling the AI and the server doesn't send new info (because enabling the AI didn't change anything).

**Comment by lmoureaux** [comment]
This is a dup of #1656.
The governor results may be wrong due to this, which calls for a server-side governor eventually.
