### ISSUE TITLE
Create an option to enable/disable the binking Nations and Research view buttons

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1676]
**Is your feature request related to a problem? Please describe.**
There seems to be some disagreement on the effectiveness of the Nations view and Research view buttons that blink/pulse to remind the player that something needs their attention.

**Describe the solution you'd like**
In stead of getting rid of it, since it was asked for - simply add some options. One for each to enable/disable the blinking/pulsing. I would suggest they are enabled by default.

**Describe alternatives you've considered**

**Additional context**
Discord - https://discord.com/channels/378908274113904641/912500712833974322/1059195496238940180

**Comment by lmoureaux** [comment]
I'd rather fix improve UI so as not to use blinking

**Comment by lmoureaux** [comment]
I suggest changing the icon of the Nations button in the same way as the Messages button changes.
