### ISSUE TITLE
Allow pressing <enter> key to select options on main screen

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1685]
**Is your feature request related to a problem? Please describe.**
When the client starts, we can use the arrows to move up and down on the options ("tutorial", "start new game", etc). But pressing "Enter" doesn't select the option, so we end up having to use the mouse anyway. Would be nice if we could have a keyboard-only pathway to connect to a server game. You can press the spacebar and it works, but that does not feel intuitive any longer

**Describe the solution you'd like**
Keep spacebar, but add the enter key as well for selecting the highlighted option.

**Describe alternatives you've considered**

**Additional context**
Discord - https://discord.com/channels/378908274113904641/1059497144874192906/1059497144874192906

**Comment by lmoureaux** [comment]
From the duplicate: https://stackoverflow.com/questions/11887938/how-to-make-a-qpushbutton-pressable-for-enter-key
