### ISSUE TITLE
Help on terrain alterations is not consistent

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1686]
**Describe the bug**
If you look at Help -> Terrain -> Terrain Alterations, there is a table of the number of turns it takes to alter varying types of terrain. This table is generated, not static. You can also see the turns it takes to alter certain terrain types by going to Help -> Terrain -> [Terrain Type] e.g.  Deep Ocean.  In a couple cases, the values in the table are not the same as on the terrain detail page. For example Terrain Alterations table says:

```
Terrain       Irrigation       Mining           Transform
----------------------------------------------------------------
Jungle        36 Plains         -               48 Forest
```

But, if you go to the terrain specific page for Jungle you see this:
![image](https://user-images.githubusercontent.com/23037938/210419054-ebbeb8d5-070f-436f-836e-e9480dec67ff.png)

There is also a discrepancy for Swamp

```
Terrain       Irrigation       Mining           Transform
----------------------------------------------------------------
Swamp          5 Grassland     12 Forest        24 Ocean
```

![image](https://user-images.githubusercontent.com/23037938/210419209-c940ee86-4d69-498d-a4be-ec7af1972df2.png)

The above is from LT76teams, but it is also present in shipped rulesets too (e.g. classic)

**To Reproduce**
1. Open a game
2. Click on help -> terrain -> terrain alterations
3. Compare the table to the details in the terrain specfic page

**Expected behavior**
The two sources should match

**Screenshots**
See above

**Platform and version (please complete the following information):**
 - OS: Linux (but assume others are impacted)
 - Freeciv21 version: 3.0-rc.1
 - Ruleset/Longturn game (if applicable): LT76Team, Classic (at least)

**Additional context**
None

**Comment by lmoureaux** [comment]
Looks like the table mixes Irrigation and Cultivate.
