### ISSUE TITLE
Nation infos with special characters are broken

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1692]
**Describe the bug**
As an example, let's take the Danish, with the capital city of København. The first issue is that the suggested name is "KÃ¸benhavn". This broken version also gets saved to the savefile. It then gets progressively worse on each save-load cycle. For example, after the third time of saving and loading the game, the name is now "KÃƒÆ’Ã‚Â¸benhavn". I assume this will go on until the save is unusable due to length limitations.

Even worse: Even if you manually fix the suggested name (here to København), it gets broken anyway when the game is saved and then loaded.

Looks like the "suggested name is wrong" part only affects local games, in LT76 I was able to build a city with a special character and it auto-suggested correctly. Unsure if the "save and load breaks it more" part affects running LT games, I'm unable to test that.

This seems to apply to leaders as well, leader names with special characters are broken in the pre-game nation selector.

**To Reproduce**
1. Choose the Danish in a new game
2. See that ruler names are broken
3. Build a city
4. See that the suggested name is "KÃ¸benhavn" instead of "København"
5. For bonus points, save and load the game several times (different saves, not overwriting the same one every time)
6. See that the name gets worse and worse every time you load the newest save

**Expected behavior**
I expect the name to stay as-is

**Screenshots**
Initial name suggestion
![freeciv21-client_XnfBI4RfLO](https://user-images.githubusercontent.com/7669061/210477451-6e831c1e-1249-45a9-97d0-b094e51c1c28.png)
Increasingly broken name
![freeciv21-client_63TT6xKo5N](https://user-images.githubusercontent.com/7669061/210477457-deaa8110-f082-435f-b51a-2b8ef64b38d0.png)
![freeciv21-client_FNo4SfBGJu](https://user-images.githubusercontent.com/7669061/210477461-cc92ec05-a7cf-4c54-852d-ea482fb5ab7c.png)
![freeciv21-client_8otZ8QI8o3](https://user-images.githubusercontent.com/7669061/210477466-707efaf7-d758-4a6f-bc3b-69cd0c27b7c8.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0-rc1
 - Ruleset/Longturn game (if applicable): not applicable, probably

**Additional context**
Savefile in question
[kabenhavn.zip](https://github.com/longturn/freeciv21/files/10341190/kabenhavn.zip)

**Comment by lmoureaux** [comment]
Looks like an encoding issue on Windows. Introduced in #1618 ?

**Comment by lmoureaux** [comment]
The UTF-8 encoding of ø is `0x63 0xb8`. `Ã` is U+00C3 and `¸` is U+00B8. You can imagine how this continues through read and write cycles.

**Comment by daavko** [comment]
Looks like it was indeed introduced in #1618. The commit right before it (ec0ecac2) is fine

**Comment by daavko** [comment]
Looks like it's loading the file as ISO-8859-1 (or one of the codepages that have the same mapping) for some reason
