### ISSUE TITLE
Add "center unit" button to units control bar

### ISSUE THREAD

**Issue by Mu-00** [longturn/freeciv21#1709]
The units control bar establishes a mouse-driven alternative to the keyboard-driven  handling of units.
If the player choses to uncheck "auto center unit" in the interface options the unit controls bar is not sufficient for this because the unit has to be centered manually pressing "c".
While centering the unit is no unit action it nevertheless is in this case indispensable.
Combining the use of the control bar with the keyboard is error prone: If the focus is not on the keyboard misclicks happen more frequently.
The question is if a "center unit" button could be added to the bar and if this could and should be done conditionally, e.g. only if the player does not use the "auto center unit" feature.

**Comment by lmoureaux** [comment]
I guess clicking on the unit icon should center on the unit.

**Comment by daavko** [comment]
It already does that

**Comment by lmoureaux** [comment]
Then... let's rephrase this issue as "is it intuitive enough?" I have no answer because I use the keyboard.

**Comment by Mu-00** [comment]
Cool. Let's close the issue.
