### ISSUE TITLE
Integrate snapcraft.yaml with cmake configure_file()

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1735]
**Is your feature request related to a problem? Please describe.**
New `snapcraft.yaml` file is hard coded to a version tag. We want to have the file use the cmake `configure_file()` function going forward.

**Describe the solution you'd like**
Rename `snapcraft.yaml` as `snapcraft.yaml.in` and then update our `CMakeLists.txt` file to configure it correctly in the `build` directory.

**Additional context**
Right now, `snapcraft.yaml` will only work on the `stable` branch. We need to wait until the snap team gets Qt support for Ubuntu 22.04 via `core22`. We have a higher cmake version requirement in `master` branch that breaks the snap capability.

**Comment by lmoureaux** [comment]
I think it would be better to extract the version information from the build environment, maybe using a [scriptlet](https://snapcraft.io/docs/using-external-metadata#meta-scriptlet). This way we don't need to run CMake twice, once inside the build VM then again inside.
