### ISSUE TITLE
Make partially transparent background for widgets optional

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1739]
**Is your feature request related to a problem? Please describe.**
It's a little distracting to see the background behind widgets like Units or Demographics, especially when screenshots of such are shared in team games. It's also not consistent with Messages and Chat widgets, those are completely opaque.

**Describe the solution you'd like**
Best by me would be adding a slider that controls how transparent you want the widgets to be, which would then apply  to *all* the widgets you can open (Units, Demographics, Wonders of the World, Historian reports, Messages, Chat, ...). Then people can just choose how transparent they want the widget to be. Someone might like being able to see the map.

**Describe alternatives you've considered**
Two other alternatives:
- A simple on-off option
  - Probably simpler than variable transparency
- Leaving it as-is
  - Please no

**Additional context**
Short conversation on Discord
https://discord.com/channels/378908274113904641/912500712833974322/1063049102675419136

**Comment by lmoureaux** [comment]
Third alternative:

* Always 100% opaque.

Any particular reason not to suggest this?

**Comment by daavko** [comment]
None other than I forgot about that option
