### ISSUE TITLE
Events E_CITY_AQUEDUCT and E_CITY_AQ_BUILDING don't apply to just Aqueducts

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1740]
**Is your feature request related to a problem? Please describe.**
The two events listed `E_CITY_AQUEDUCT` and `E_CITY_AQ_BUILDING` talk about just Aqueducts, however in the code we support any kind of building that is needed to allow growth and don't limit it to just one building. This is confusing.

**Describe the solution you'd like**
Rename the event and the associated title that displays in the message options dialog box to make it more clear what the message does. A suggested title would be "City: Needs Improvement to Grow"

**Describe alternatives you've considered**

**Additional context**
Came up as part of review of #1726

**Comment by lmoureaux** [comment]
Would be better to keep the settings compatible
