### ISSUE TITLE
MSYS2 is now shipping with SSL v3.0.7 instead of v1.1.1

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1744]
**Describe the bug**
MSYS2 is now shipping with SSL v3.0.7 instead of v1.1.1

**To Reproduce**
https://github.com/longturn/freeciv21/actions/runs/3925180765/jobs/6709967983

**Expected behavior**
We either need to start supporting SSL v3.0, or need a way to get v1.1 working in MSYS2 for Windows packaging. As a reminder, I was able to tell vcpkg to grab v1.1h for macOS and Windows clang, but I'm sure that will not be supported much longer.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Windows MSYS2
 - Freeciv21 version: `master` at https://github.com/longturn/freeciv21/commit/5b04e82ec4a9536e14087a8d074128c4ec35b8d2
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**

**Comment by jwrober** [comment]
This seems to be a problem upstream - https://github.com/msys2/MINGW-packages/issues/15124

**Comment by Biswa96** [comment]
The packages are in queue list now, see https://packages.msys2.org/queue. Those will be updated once the building is finished in CI.

**Comment by jwrober** [comment]
With upstream resolved. This is closed with #1745 on our end.
