### ISSUE TITLE
Include current progress next to research name in nations view

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#1767]
**Is your feature request related to a problem? Please describe.**
not related to a problem

**Describe the solution you'd like**
Currently, the column "Research" only says the name of the research target (e.g. "Pottery"). To know the current progress, one must press the nation and check the detailed information at the bottom of the client. The research column could include the current progress (i.e. "Pottery (3/30)"), becoming essentially identical to the information displayed in the details.

**Comment by jwrober** [comment]
Looks good to me.
