### ISSUE TITLE
A combination of ruleset, map generator, start positions and server settings crashes the game at start

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#1770]
The combination of Sim ruleset (attached) and mapgen settings (attached) crashes the game.

The same starting settings do not cause crash at start with "default" ruleset.

Also, Sim ruleset and **isometric non-hex** map topology also does **not** cause the crash.

So, in short: Sim, non-iso, hex causes a crash.

![image](https://user-images.githubusercontent.com/25233743/213943206-b1f66293-89ec-4a45-9587-b6cb5378b6c1.png)
[SIM30-fc21.zip](https://github.com/longturn/freeciv21/files/10475644/SIM30-fc21.zip)

**Comment by lmoureaux** [comment]
This is caused by a missing sprite in the default non-iso Hex tileset:
```
[fatal] freeciv21-client (/home/louis/freeciv/freeciv21/client/tilespec.cpp:402) - Missing Resort building activity sprite for tags "unit.resort" and alternatives "unit.buoy" and "-".
```

**Comment by Corbeau-1** [comment]
Thanks. As far as I'm concerned, you can close it.

I think I tried running it in safe mode (I think) but didn't get this.
