### ISSUE TITLE
Unit names aren't shown to other players

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1782]
**Describe the bug**
If you rename a unit, other players can't see the new name if they're connected at the time. They have to reconnect to see it.

**To Reproduce**
1. Connect with player A
2. Connect with player B
3. Rename one of player A's units
4. Observe player B can't see the name until they reconnect

**Expected behavior**
The name should be visible right away

**Screenshots**
No screenshots

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: rc2
 - Ruleset/Longturn game (if applicable): LT76

**Additional context**
No additional context

**Comment by lmoureaux** [comment]
The names are actually sent, just not shown to other players.
