### ISSUE TITLE
Improve the UI for transport ships with loaded units in city view

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1836]
**Is your feature request related to a problem? Please describe.**
If you have more than one transporter (e.g. a Caravel) inside of a city and that ship also has units loaded on it, it is impossible to tell what unit is on which ship. This is in the present units widget in the city dialog.

**Describe the solution you'd like**
With the new city dialog using much more screen real estate, maybe we can expand the widget in some fashion. The first "row" is units stationed in the city, such as defenders. If this scenario arises, then have a second row that shows the transporter to the left and then the units loaded on it to the right with some visual effect so you can easily see who is loaded where. I don't envision a third row for a second transporter, just append it to the right in a pattern and only go to another row when the max width is reached

**Describe alternatives you've considered**
Could also leave things alone, but add some kind of embellishment/indicator on the transporter and the loaded units. Such as put a `1` on the Caravel and the loaded units for the first ship and a `2` on the second and so forth.

**Additional context**
Recent teams game is giving us lots of ideas :)

**Comment by lmoureaux** [comment]
This problem was previously solved in #707 but the solution was broken afterwards. It also affects the unit chooser popup for stacks.
