### ISSUE TITLE
Rush buying a unit shows complete in 2 turns

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1848]
**Describe the bug**
Not always, there is some condition that occurs that when you rush buy a unit the client will show 2 turns to finish and zero gold. The unit is finished at turn change as expected, but the city dialog shows an incorrect value.

**To Reproduce**
1. Open a game
2. Open a city building a unit such as a Caravan
3. Rush buy the unit
4. See error -- note that it does not happen at all times

**Expected behavior**
The city dialog shows correct values

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/222819542-e99928b5-a2c6-4fcb-a17a-c5f46a7e6e09.png)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-dev, and in 3.0-rc.2
 - Ruleset/Longturn game (if applicable): Discovered in LTX LT76Teams, so don't know if its a rules thing or a client thing for sure.

**Additional context**

**Comment by lmoureaux** [comment]
To be more specific, it shows the number of turns to completion before buying, as if the client was unaware of the gold it spent.
