### ISSUE TITLE
Pillaging doesn't start when using shortcut or unit actions widget button

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1849]
**Describe the bug**
When using the Shift+P shortcut or clicking the "Pillage" button in the unit actions widget at the bottom, nothing happens. Pillaging only works when clicking Combat > Pillage.

**To Reproduce**
1. Have a unit that can pillage on a tile where there's something to pillage
2. Use the Shift+P shortcut
3. Observe nothing happens
4. Click the "Pillage" button in the unit actions widget at the bottom
5. Observe nothing happens
6. Use Combat > Pillage
7. Observe unit starts to pillage

**Expected behavior**
All ways to pillage should work

**Screenshots**
No screenshots

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: rc2 and latest master
 - Ruleset/Longturn game (if applicable): LT76

**Additional context**
No additional context

**Comment by jwrober** [comment]
I can recreate
