### ISSUE TITLE
Supported units that cause unhappiness not shown in city dialog

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1859]
**Describe the bug**
If you have units in enemy territory that cause unhappiness to the city that is supporting them, the city dialog does not show which unit(s) is causing the unhappiness. There doesn't seem to be any way to see that.

**To Reproduce**
1. Open a game
2. Get some units from a known city into enemy territory or an area that would cause unhappiness
3. Open the city dialog for the city the unit is supported by

**Expected behavior**
There is tileset feature to show an angry face / angry citizen embellishment next to the unit just like we have for gold, shield and food upkeep.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0-rc.3
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Noticed while playing LT76Team game

**Comment by jwrober** [comment]
Also noticed that the tooltip in the citizens tab is also incorrect. Assume they are related.

**Comment by lmoureaux** [comment]
> Also noticed that the tooltip in the citizens tab is also incorrect. Assume they are related.

Different issue after all
