### ISSUE TITLE
Game -> Messages menu should be Game -> Message Options

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1869]
**Is your feature request related to a problem? Please describe.**
We have Interface Options and Game Options menu items to note those open an options dialog. 

**Describe the solution you'd like**
Do the same for Message

**Describe alternatives you've considered**

**Additional context**
While at it, should do the same thing for Shortcut on Game menu

**Comment by cgalik** [comment]
Thanks! :)
