### ISSUE TITLE
Missing dependency readline-devel

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#1893]
**Describe the bug**
When installing on fedora, you are missing the readline-devel dependency 

**To Reproduce**
1. Install documented dependencies
2. Download freeciv21 w/ git
3. Run `cmake . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/freeciv21`

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find Readline (missing: READLINE_LIBRARIES READLINE_INCLUDE_DIRS)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindReadline.cmake:8 (find_package_handle_standard_args)
>   cmake/FreecivDependencies.cmake:28 (find_package)
>   CMakeLists.txt:82 (include)

**Expected behavior**
No error

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: Fedora 37
 - Freeciv21 version: 3.1.dev
 - Ruleset/Longturn game (if applicable): NA

**Additional context**
Though this dependency might be pulled in with other packages on other distros, it is probably better that it is listed.

**Comment by jwrober** [comment]
I think you are our first Fedora user! Thanks for the report. Mind commenting back the names of the packages you installed with `yum` or whatever package manager Fedora uses these days? Please include what you put in #1895. Thanks

**Comment by lmoureaux** [comment]
@jwrober I think #1894 has the complete list

**Comment by jwrober** [comment]
Oh it sure does. cool. I didn't see that one.
