### ISSUE TITLE
Add line required dependencies for Fedora like distros

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#1894]
**What should be documented? Is there something wrong in the documentation?**
Add support for easy installation of required build dependencies for fedora like systems

**Do you have suggestions?**
Here is the line to install required dependencies on Fedora like distros

`sudo dnf install cmake ninja-build g++ python gettext qt5-qtbase-devel qt5-qtsvg-devel kf5-karchive-devel lua-devel sqlite-devel SDL2_mixer-devel readline-devel zlib-devel libunwind-devel`

**Comment by lmoureaux** [comment]
Looks like `zlib-devel` is missing from the list

**Comment by 3dsf** [comment]
`libunwind-devel` could probably be added too.  

_Original comment above updated_
