### ISSUE TITLE
Build error - Incompatible lua dependency though matches required

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#1895]
**Describe the bug**
Documentation state lua 5.3 or lua 5.4 should be compatible, though build fails

**To Reproduce**
1. Follow install procedures on git page
2. `cmake --build build`
**Errors that look like this**

> [7/295] Building CXX object common/scriptcore/CMakeFiles/scriptcore.dir/luascript.cpp.o
> FAILED: common/scriptcore/CMakeFiles/scriptcore.dir/luascript.cpp.o 
> /usr/bin/c++ -DLUA_LIB -DPUBLIC -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x051500 -DQT_NETWORK_LIB -DQT_NO_DEBUG -DSOL_ALL_SAFETIES_ON=1 -DSOL_NO_CHECK_NUMBER_PRECISION=1 -I/home/3dsf/git/freeciv21/common/scriptcore -I/home/3dsf/git/freeciv21/build/common/scriptcore -I/home/3dsf/git/freeciv21/common -I/home/3dsf/git/freeciv21/build/common -I/home/3dsf/git/freeciv21/common/aicore -I/home/3dsf/git/freeciv21/common/networking -I/home/3dsf/git/freeciv21/utility -I/home/3dsf/git/freeciv21/build/utility -I/home/3dsf/git/freeciv21/dependencies/tolua-5.2/include -I/home/3dsf/git/freeciv21/dependencies/sol2 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -std=gnu++17 -Wall -Wno-sign-compare -Warray-bounds -Wdelete-incomplete -Wint-in-bool-context -Wreturn-type -Wsequence-point -Wswitch -Wunused-value -Wmaybe-uninitialized -Wstringop-truncation -fPIC -MD -MT common/scriptcore/CMakeFiles/scriptcore.dir/luascript.cpp.o -MF common/scriptcore/CMakeFiles/scriptcore.dir/luascript.cpp.o.d -o common/scriptcore/CMakeFiles/scriptcore.dir/luascript.cpp.o -c /home/3dsf/git/freeciv21/common/scriptcore/luascript.cpp
> In file included from /home/3dsf/git/freeciv21/common/scriptcore/luascript.cpp:26:
> /home/3dsf/git/freeciv21/dependencies/sol2/sol/sol.hpp:3110:177: error: operator '!=' has no left operand
>  3110 |         **#if (SOL_LUA_VERSION_I_ == 502) || (defined(LUA_COMPAT_BITLIB) && (LUA_COMPAT_BITLIB != 0)) || (SOL_LUA_VERSION_I_ < 504 && (defined(LUA_COMPAT_5_2) && (LUA_COMPAT_5_2 != 0)))**
>       |                                                                                                                                                                                 ^~
> 

**Expected behavior**
Build to complete as required dependency is installed
`lua-devel-5.4.4-9.fc37.x86_64 `

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: Fedora 37
 - Freeciv21 version: 3.1-dev
 - Ruleset/Longturn game (if applicable): NA

**Additional context**

**Comment by lmoureaux** [comment]
Building against Lua 5.4 is known to work on Windows and Arch Linux, and building against Lua 5.3 is known to work on Ubuntu. This issue looks a bit more complicated, I'll spin off a Fedora Docker image and take a look.

**Comment by lmoureaux** [comment]
This is https://github.com/ThePhD/sol2/issues/1461

**Comment by lmoureaux** [comment]
Thanks for taking the time to write a report! #1896 should solve the issue for fc21, I'll send a fix upstream as well

**Comment by 3dsf** [comment]
@lmoureaux 
Thanks, my head is spinning how quickly got to this : )  

It resolves the build issue but I also noticed this in my initial build report 
(See bolded line in next section)

---
---
`cmake . -B build -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/freeciv21`

> -- Found Git: /usr/bin/git (found version "2.39.2") 
> -- Git commit hash: (hex) 039b9 and (dec) 14777
> -- Version tag: v3.1-dev
> -- The C compiler identification is GNU 12.2.1
> -- The CXX compiler identification is GNU 12.2.1
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for at_quick_exit
> -- Looking for at_quick_exit - found
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.11.2", minimum required is "3") 
> -- Found Readline: /usr/lib64/libreadline.so  
> -- Looking for rl_completion_suppress_append
> -- Looking for rl_completion_suppress_append - not found
> -- Found Intl: built in to C library  
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
> -- Found Threads: TRUE  
> -- Found Lua: /usr/lib64/liblua-5.4.so;/usr/lib64/libm.so (found suitable version "5.4.4", minimum required is "5.3") 
> **-- Could NOT find ToLuaProgram (missing: TOLUA_PROGRAM)** 
> -- Found Lua: /usr/lib64/liblua-5.4.so;/usr/lib64/libm.so (found version "5.4.4") 
> -- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
> -- Checking for one of the modules 'libunwind'
> -- Looking for execinfo.h
> -- Looking for execinfo.h - found
> -- Looking for backtrace
> -- Looking for backtrace - found
> -- Using backtrace() for stack unwinding. Install libunwind and pkg-config for better results.
> -- Checking for one of the modules 'libdw'
> -- Using libdw to retrieve stack symbols. This is the preferred option.
> -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.12")  
> -- Found SQLite3: /usr/include (found version "3.40.0") 
> -- Performing Test FREECIV_C_COMPILER_HAS_-WNO-TAUTOLOGICAL-CONSTANT-OUT-OF-RANGE-COMPARE
> -- Performing Test FREECIV_C_COMPILER_HAS_-WNO-TAUTOLOGICAL-CONSTANT-OUT-OF-RANGE-COMPARE - Failed
> -- Performing Test FREECIV_CXX_COMPILER_HAS_-WNO-TAUTOLOGICAL-CONSTANT-OUT-OF-RANGE-COMPARE
> -- Performing Test FREECIV_CXX_COMPILER_HAS_-WNO-TAUTOLOGICAL-CONSTANT-OUT-OF-RANGE-COMPARE - Failed
> -- Found Sphinx: /usr/bin/sphinx-build  
> -- Downloading Libertinus Font Package
> -- Including CPack
> -- Configuring done (1.5s)
> -- Generating done (0.1s)
> -- Build files have been written to: /home/3dsf/freeciv21/build

**Comment by jwrober** [comment]
We like to leave issues open until a PR is closed associated. That bolded item is ok. We inlcude a tolua in `dependencies`
