### ISSUE TITLE
New user -- Username Issues 

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#1898]
**Describe the bug**
Username required to start all games.  Issue not reported on console but at bottom of GUI.  Seen post from an unfortunate soul, #1466, which told me I could update it in the options menu.  After updating the username in the Options menu (**Apply** and **Save**) and trying to start a game, resulted in continued games not starting.  Closed and reopened client, then the username was respected   

**To Reproduce**
1. Start Client
2. Click 'Start new Game'  -- Game does not start
3. Update name in 'Options', Apply, Save
4. Click 'Start new Game'  -- Game does not start
5. Close and reopen client
6. Click 'Start new Game'  -- Game starts

**Expected behavior**
Game to start on first start of game press or maybe an add name dialog

**Platform and version (please complete the following information):**
 - OS: Fedora 37
 - Freeciv21 version: 3.1 dev
 - Ruleset/Longturn game (if applicable): NA

**Additional context**
I think this is a bug, but might also be an enhancement request for an enter name dialog if the username is empty.  
I'm happy you have decided not to auto-populate the computers users login name.

**Comment by lmoureaux** [comment]
It *should* have picked your login name by default (doesn't really matter for local games, and you can always change it as you found out)... this is indeed a bug.
