### ISSUE TITLE
Tile info popup overflows the window when city has too many visible improvements

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#1901]
**Describe the bug**
If a city has many visible improvements (wonders or things like city walls, coastal defense, etc.) and you middle-click it to open the tile information popup, it overflows the window. This makes any tile information unreadable since the popup gets centered, so the information is pushed beyond the left window border.

**To Reproduce**
1. Build a city
2. Build many visible improvements (wonders or things like city walls, coastal defense, etc.) in it
3. Middle-click on the city to open the tile information popup
4. See that it overflows the window

**Expected behavior**
The list of visible buildings should wrap when it becomes too large for the window. Ideally this would also not take the complete window width, but reasonable percentage of it (say, max 50% of window width) so it stays readable and isn't just a super long noodle.

**Screenshots**
Confidential, sent to a place where the devs can see them

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0 rc3 (almost certainly present in newest `stable` and `master` as well, there have been no changes to this popup for a long time)
 - Ruleset/Longturn game (if applicable): not applicable

**Additional context**
No additional context

**Comment by jwrober** [comment]
I can recreate
