### ISSUE TITLE
Could not find freeciv21/database.lua

### ISSUE THREAD

**Issue by buxx** [longturn/freeciv21#1909]
Hello,

I installed freeciv21_3.0_amd64.deb on an Ubuntu 22.04. Created a fc_auth.conf file containing : 

    ubuntu@vps-d6e581e9:~$ cat fc_auth.conf 
    [fcdb]
      backend="sqlite"
      database="./freeciv.sqlite"

When starting server :

```
ubuntu@vps-d6e581e9:~$ freeciv21-server --Database fc_auth.conf --auth --Newusers
This is the server for Freeciv21 version 3.0
You can learn a lot about Freeciv21 at https://longturn.readthedocs.io/en/latest/
[info] freeciv21-server - Server attempting to listen on :5556
[critical] freeciv21-server - Could not find freeciv21/database.lua in the following directories: ("/home/ubuntu/.config", "/etc/xdg")
```

After manually database.lua in /home/ubuntu/.config/freeciv21 : 

    ubuntu@vps-d6e581e9:~$ freeciv21-server --Database fc_auth.conf --auth --Newusers
    This is the server for Freeciv21 version 3.0
    You can learn a lot about Freeciv21 at https://longturn.readthedocs.io/en/latest/
    [info] freeciv21-server - Server attempting to listen on :5556
    [critical] freeciv21-server - /home/ubuntu/.config/freeciv21/database.lua:83: attempt to index a nil value (global 'ls_sqlite3')
    stack traceback:
    	/home/ubuntu/.config/freeciv21/database.lua:83: in function </home/ubuntu/.config/freeciv21/database.lua:78>
    	(...tail calls...)
    [critical] freeciv21-server - Error connecting to the database

Any idea of the situation ?

**Comment by jwrober** [comment]
Resolved via #1919
