### ISSUE TITLE
AutoRev is not picking up v3.1.x releases on master branch

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1922]
**Describe the bug**
AutoRev is not picking up v3.1.x releases on `master` branch

**To Reproduce**
1. Tag a release on `master` branch
2. Notice that the compiled binaries show incorrect version.

https://github.com/longturn/freeciv21/actions/runs/4779208059/jobs/8496507906

**Expected behavior**
AutoRev properly grabs the tag

**Screenshots**
![image](https://user-images.githubusercontent.com/23037938/233854109-809d2454-47aa-4a77-99c0-c619c20e5477.png)

![image](https://user-images.githubusercontent.com/23037938/233854082-e3a5b593-f8ec-4b6d-a5b0-240d50a4b00f.png)

**Platform and version (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Freeciv21 version: v3.1-alpha.1
 - Ruleset/Longturn game (if applicable): [e.g. `classic` or `LTEx24`]

**Additional context**

**Comment by lmoureaux** [comment]
Related to https://github.com/longturn/freeciv21/issues/1825

**Comment by lmoureaux** [comment]
This is the caveat noted in #1820, it works properly now.

**Comment by jwrober** [comment]
I am not sure this is an issue any longer. Recent runs in both stable and master branches show the correct tag. We can watch to see what happens when we push 3.1-alpha.6

**Comment by lmoureaux** [comment]
Quoting from #1820:
> Caveat: When creating the v3.1-alpha.1 tag on top of a v3.1-dev, the version will stay at v3.1-dev until the AutoRevision PR gets merged. Even after it is merged, someone doing a git checkout of v3.1-alpha.1 will get the v3.1-dev tag.

So it will happen again for 3.2-alpha.1

**Comment by jwrober** [comment]
Ok this is still an issue - https://github.com/longturn/freeciv21/actions/runs/8500499168/job/23282414079

**Comment by jwrober** [comment]
I wonder if we can have "release" workflow happen after "build" completes and then we can add a `git fetch` to "release"
