### ISSUE TITLE
Didn't find 'freeciv-client-rc-3.1' option file, loading from 'freeciv-client-rc-3.0' instead

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1930]
**Describe the bug**
Didn't find '/home/[user]/.local/share/freeciv21/freeciv-client-rc-3.1' option file, loading from '/home/[user]/.local/share/freeciv21/freeciv-client-rc-3.0' instead.

**To Reproduce**
1. Start client from command line
2. See error

**Expected behavior**
I guess we need some kind of migration from 3.0 rc file to 3.1?

**Screenshots**
n/a

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-alpha.1
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**
None

**Comment by lmoureaux** [comment]
What you're seeing is the migration happening.
```
$ ls ~/.local/share/freeciv21
3.0
freeciv-client-rc-3.0
freeciv-client-rc-3.1
freeciv-server_history
saves
scenarios
```

**Comment by jwrober** [comment]
I get the message repeatedly and there isn't a 3.1 file on my local. Reopening until we get a better conclusion.

**Comment by jwrober** [comment]
Turns out my issue is I had `save_options_on_exit` set to `FALSE`. Duh. Reclosing.
