### ISSUE TITLE
ec_info option does not show turn and timestamp

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1942]
**Describe the bug**
The server option `ec_info` is supposed to show the turn number and timestamp of messages in the chatline widget, but it doesn't.

**To Reproduce**
1. Open a game with the option enabled (LT78 is a good recent example)
2. Click on the server/chatline widget
3. See error

**Expected behavior**
There should be a turn number and server timestamp before each message line in the chatline when connecting to the game to show past messages.

**Screenshots**
![image](https://github.com/longturn/freeciv21/assets/23037938/b5ba299d-9e92-4e43-b440-e7351afb3766)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-alpha.1 and 3.0-stable
 - Ruleset/Longturn game (if applicable): n/a

**Additional context**

**Comment by lmoureaux** [comment]
What does the string sent by the server look like?

**Comment by jwrober** [comment]
`(T31 - 17:21:34) Player 'Juan Vicente Gómez' now has AI skill level 'Easy'.`
