### ISSUE TITLE
freeciv21-manual does not get images needed

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#1974]
**Describe the bug**
If you call `freeciv21-manual` for a ruleset, it will write out the proper files. However it does not get the images needed for terrain, buildings, and wonders.

**To Reproduce**
1. Open a command terminal
2. run `freeciv21-manual -r civ1`
3. Open `civ13.html` and notice missing terrain icons. Same with `civ14.html`, and `civ15.html`.

**Expected behavior**
Image files are copied to an images directory and properly referenced.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-alpha.1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
There isn't a "--tileset" option, so a default terrain would need to be set (such as Amplio2)

**Comment by lmoureaux** [comment]
How much do we want to support `-manual` vs `pyciv`'s approach?

**Comment by jwrober** [comment]
`-manual` requires no other dependency and is shipped with the game. Maybe it should just be image-free in the HTML output? I don't want to get rid of it altogether I don't think.

**Comment by jwrober** [comment]
Coming back to this... I think an edit to `freeciv21-manual` to not attempt any images and just generate plain HTML is a easy approach and then we let `pyciv` do the bigger more "sexy" effort of getting images and generating the RST we need for docs.
