### ISSUE TITLE
Message window and minimap covering each other

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#1993]
... and the problem is I can move neither nor minimize minimap.

![image](https://github.com/longturn/freeciv21/assets/25233743/305b3ba0-8b5a-4e9d-9c96-1687c6be2b10)

**Comment by lmoureaux** [comment]
To resize the minimap or the messages window, make sure Display > Lock Interface is not checked and grab their sides.

**Comment by Corbeau-1** [comment]
I know about resizing. But it is not very practical. For the record, this is not a priority issue, more of a nuisance, but it is mildly annoying. Allowing complete minimap minimizing and/or moving the message window would make the whole experience better.

**Comment by Corbeau-1** [comment]
There is no "potential improvement" category so i filed it as "bug".

Request (or, rather, a suggestion): allow minimap to be minimized and/or message window and/or minimap to be moved.

**Comment by lmoureaux** [comment]
>  allow minimap to be minimized

This is already available: Display > Minimap or Ctrl+M.

The message window and minimap being fixed in their corners is a design decision (you may remember that they could be moved before). I currently don't see a reason to revisit it: the same overlap issues would be present.

**Comment by Corbeau-1** [comment]
Damn... Ok, next time I'll ask on Discord first. Sorry for wasted time.

**Comment by lmoureaux** [comment]
No problem, we can point people to this issue in the future :D
