### ISSUE TITLE
The client cannot find its window icon

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#2019]
**Describe the bug**

```
[critical] freeciv21-client (.../freeciv21/client/tileset/tilespec.cpp:1208) - Could not load gfx file "misc/freeciv21-client".
```
and the window icon is missing.

**To Reproduce**
1. Start Freeciv21
2. Look at the icon in the task manager
3. A generic icon is used

**Expected behavior**

A shiny Freeciv21 icon is shown.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master

**Additional context**

The window icon doesn't work on Wayland for other reasons.
Solving #984 would also fix this issue.

**Comment by jwrober** [comment]
This is fixed with this commit - https://github.com/longturn/freeciv21/commit/fd9f828ead2bb0c79c856701c14380ed427a1139

**Comment by lmoureaux** [comment]
Only if you install. If you run from the source folder without installing it doesn't have the file.
