### ISSUE TITLE
Vessel and units disbanded after converting sea to swamp immediately before time change, unitwaittime

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#2029]
**Describe the bug**
Vessel and units disbanded after converting sea to swamp immediately before time change; related to unitwaittime.

**To Reproduce**
1. Immediately before tc, move vessel containing engineers to new sea tile and covert to swamp

**Expected behavior**
Units to move to next closest sea tile.  See second screenshot for behaviour. 

**Screenshots**
- https://discord.com/channels/378908274113904641/1080919938044280913/1146327983381037147 
- https://discord.com/channels/378908274113904641/1080919938044280913/1146328075592802304

**Platform and version (please complete the following information):**
 - OS: android
 - Freeciv21 version: freeciv21-client 3.1.392482.2-alpha
 - Ruleset/Longturn game (if applicable): LT78

**Additional context**

**Comment by lmoureaux** [comment]
Related: #1515

**Comment by 3dsf** [comment]
note: 
transport was not sentried

**Comment by lmoureaux** [comment]
Fixed in #2052
