### ISSUE TITLE
Wonder sprites missing from RoundSquare

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#2033]
**Describe the bug**

The RoundSquare tileset that we ship in the modpack installer doesn't seem to have wonder sprites (including the palace).

**To Reproduce**
1. Use RoundSquare
3. Build your first city
5. Check that you have a palace sprite (actually the game just crashes at the moment...)

**Expected behavior**
The Palace sprite is there. Backward compatibility isn't broken.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: master
 - Ruleset/Longturn game (if applicable): classic

**Additional context**
Maybe this was broken when the "small" wonder sprites started being used in Trident?

**Comment by lmoureaux** [comment]
I can confirm that this is caused by the split of wonders off `misc/buildings.spec` into `misc/wonders.spec`. I can't see an easy way to provide backward compatibility for this, apart from reverting the split.
@jwrober what do you think?

**Comment by jwrober** [comment]
I would prefer to keep the sprites separate, but maybe remove the `wonder*.spec` files and move the sprite calls back to `building*.spec`?

OR alternately, the RoundSquare tileset could be altered to use the new file. This is honestly my most preferred option.

**Comment by jwrober** [comment]
Another thought, we change stable to include dummy `spec` files for the wonders

**Comment by lmoureaux** [comment]
Maybe we could keep a compatibility `buildings.spec` that `*includes` the new `buildings.spec` and `wonders.spec`?

FWIW RoundSquare is also compatible with 2.6 and Freeciv.

**Comment by jwrober** [comment]
If I moved the wonder sprite "calls" back into the `buildings.spec` file (and remove `wonders.spec`) will that bring back compatibility? I'd be in favor of that and still keep the sprites in separate directories.

**Comment by lmoureaux** [comment]
I wanted to propose a file like this for `buildings.spec`:
```ini
; This file is kept for backward compatibility and will be removed in a future
; version.

*include "tilesets/buildings.spec"
*include "tilesets/wonders.spec"
```
Unfortunately this doesn't work because the `sprites` table in `wonders.spec` overrides the one in `buildings.spec` (at least partially).

What you propose sounds like the best solution.
