### ISSUE TITLE
Assertion (action_prob_is_signal(chance) || chance.min >= ACTPROB_VAL_MIN) failed

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#2035]
**Describe the bug**
`[critical] freeciv21-client - Assertion (action_prob_is_signal(chance) || chance.min >= ACTPROB_VAL_MIN) failed
[critical] freeciv21-client - Please report this message at https://github.com/longturn/freeciv21/issues`
_it filled my terminal window with these errors_

**To Reproduce**
1. Not sure what I was doing; I was playing around with turning on and off governors 

**Expected behavior**

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: linux
 - Freeciv21 version: freeciv21-client 3.1.787087.3-alpha
 - Ruleset/Longturn game (if applicable): LT78

**Additional context**
Didn't notice anything abnormal besides this comp going slow because it is low end hardware and I was playing with governors and all my cities (most medium to large)

**Comment by lmoureaux** [comment]
If there are so many it's most likely coming from goto. Could this have been the case? Any idea what kind of unit going where?

**Comment by 3dsf** [comment]
Sorry, missed this in my email.  It is possible I could have been moving units, but I think I was just doing a "maintenance login" when this happened.  I'll try and be more vigilant in the future.

**Comment by lmoureaux** [comment]
The function generating these assertions is `action_prob` (in `common/actions.cpp`). This doesn't seem to be called from the path finding code.
