### ISSUE TITLE
Government shouldn't be chosen randomly when losing a tech

### ISSUE THREAD

**Issue by daavko** [longturn/freeciv21#2047]
**Is your feature request related to a problem? Please describe.**
When a player loses a tech that causes them to lose access to a government, the game currently chooses a random available government. This may be surprising behavior to players, considering other situations that cause spontaneous government change would go directly to Anarchy instead.

**Describe the solution you'd like**
The game should go to Anarchy instead of randomly choosing.

**Describe alternatives you've considered**
Leaving it as-is, which is not great. Also considered leaving it up to ruleset author, but that'd be complicated since they'd have to make sure the player can go to the configured government in any situation where they'd lose a tech.

**Additional context**
Discord discussion https://discord.com/channels/378908274113904641/402213035865014272/1165650726400294932

**Comment by lmoureaux** [comment]
Since you've obviously researched this, would you have a link to the code location?

**Comment by daavko** [comment]
Here: https://github.com/longturn/freeciv21/blob/master/server/techtools.cpp#L871

**Comment by lmoureaux** [comment]
Thanks!
