### ISSUE TITLE
Units getting disbanded when terrain is changed

### ISSUE THREAD

**Issue by wieder-fi** [longturn/freeciv21#2048]
**Describe the bug**
The units involved (like a ship with engineers) are disbanded If an engineer is terrafoorming ocean into land and the terraforming started so late that the unit still has unitwaittime left when the terrain is changed. Disbanding includes any units on the tile if there is unitwaittime left. The same issue applies to globalwarming changing terrain into ocean. The units with unitwaittime left are disbanded if there are any on a tile that is converted into ocean by global warming.

**To Reproduce**
1. Set the game to have unitwaittime
2. Make the units to change terrain in one turn and move the units there when the units will have unitwaittime left at the turn change
3. Wait for the turn to change'
4. See the messages about units getting disbanded 

**Expected behavior**
The units are allowed to move (because of the changing terrain) like the unitwaittime never existed and the actual unitwaittime (if any left) only applies when the terrain changes (global warming, transforming terrain) have been processed. The game may have a feature allowing the terrain to be changed mid turn so the same effect should apply even mid turn if that happens.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
https://cdn.discordapp.com/attachments/784087796657815644/1166027854077776024/image.png

**Platform and version (please complete the following information):**
LTT and LTX, rulesets

**Comment by lmoureaux** [comment]
The proposed behavior allows bypassing UWT in some cases. For instance a battleship in the stack could be moved to a strategic tile as a result of the terraforming. I think setting `unitwaittime_style` to `Activities` would be a more elegant solution to this problem.

**Comment by lmoureaux** [comment]
UWT Activities has its own problems: if you start terraforming *then* add military units, the military will be disbanded.

**Comment by lmoureaux** [comment]
Fixed in #2052
