### ISSUE TITLE
The sorting order in Nations tab Team column should be natural, not alphabetical

### ISSUE THREAD

**Issue by wsfsbvchr** [longturn/freeciv21#2050]
**Describe the bug**
The team numbers of nations are sorted alphabetically.

**To Reproduce**
1. Open a game with 10+ teams
2. Click on the Team column in the Nations tab
3. See the teams sorted alphabetically

**Expected behavior**
The teams numbers should be sorted naturally.

**Screenshots**
![fc21-teams](https://github.com/longturn/freeciv21/assets/61580558/ea3981cb-cd72-4b1e-9849-0ca22e59b3c7)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.0.102624.1-patch

**Comment by jwrober** [comment]
Thanks for the submission.

**Comment by lmoureaux** [comment]
`QCollator supports this`
