### ISSUE TITLE
release.yaml i686 msys broken

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2108]
**Describe the bug**
When we released 3.1-alpha.4, the release process ended in an error due to a bad package name. Seems that msys2 is changing some names around

**To Reproduce**
1. Tag a release like this https://github.com/longturn/freeciv21/actions/runs/7371145800/job/20058230354

**Expected behavior**
We get an i686 windows package

**Comment by lmoureaux** [comment]
We should add a weekly test for this platform as well.

**Comment by jwrober** [comment]
Closed via #2120
