### ISSUE TITLE
Sphinx: Unable to disable making man pages

### ISSUE THREAD

**Issue by psampathkumar** [longturn/freeciv21#2155]
**Describe the bug**
When people compile the code for themselves in master, they should be able to disable making the RTD man pages, or ignore it when there is a error. 

**To Reproduce**
1. Compile without `sphinx_rtd_theme` in system. 
2. See Error
3. Set `-DFREECIV_ENABLE_MANPAGES` flag to `OFF` in CMake
4. Still See error

**Expected behavior**
Man pages are skipped with the flag. 

**Screenshots**
![image](https://github.com/longturn/freeciv21/assets/30164619/467b4d35-0408-44a2-ac7a-b824e804f3c2)

**Platform and version (please complete the following information):**
 - OS: Arch Linux
 - Freeciv21 version: [e.g. 3.1-alpha.4]

**Additional context**
It works in stable without this error, with the same PKGBUILD on arch.

**Comment by blabber** [comment]
Of course, `FREECIV_ENABLE_MANPAGES` should be taken into account during the build.
But this issue raises another question: Why is sphinx_rtd_theme even needed to render a manpage?

**Comment by jwrober** [comment]
Is part of our requirements file - https://github.com/longturn/freeciv21/blob/master/docs/requirements.txt

**Comment by psampathkumar** [comment]
>  Why is sphinx_rtd_theme even needed to render a manpage?
It is for the readthedocs website (https://longturn.readthedocs.io/en/latest/index.html). The end user mostly doesnt need that build unless for some reason they want to have a local copy of that website. They'll get all the information from text files without the manpage compile..
