### ISSUE TITLE
Release workflow: Wrong version in AutoRevision.txt for v3.0-patch.3

### ISSUE THREAD

**Issue by blabber** [longturn/freeciv21#2179]
**Describe the bug**
The [release source archive](https://github.com/longturn/freeciv21/releases/download/v3.0-patch.3/Freeciv21-v3.0-patch.3.tar.gz) for `v3.0-patch.3` contains the following:

```sh
cat Freeciv21-v3.0-patch.3/cmake/AutoRevision.txt
f5eab4
v3.0-patch.2
```

**To Reproduce**
- Dowload and inspect the [release source archive](https://github.com/longturn/freeciv21/releases/download/v3.0-patch.3/Freeciv21-v3.0-patch.3.tar.gz)
- Inspect the tag for `v3.0-patch.3` which also contains the wrong version info in [`AutoRevision.txt`](https://github.com/longturn/freeciv21/blob/v3.0-patch.3/cmake/AutoRevision.txt#L2)

**Expected behavior**
`AutoRevision.txt` should contain the correct information, like the file content committed in [4c161dc](https://github.com/longturn/freeciv21/commit/4c161dc8a1cc4b7cbcd505e8be4653bb58a12b66):
```
e5a21
v3.0-patch.3
```

**Platform and version (please complete the following information):**
 - OS: FreeBSD 14.0
 - Freeciv21 version: 3.0-patch.3

**Comment by jwrober** [comment]
The code that does this work is here - https://github.com/longturn/freeciv21/blob/master/.github/workflows/release.yaml

**Comment by blabber** [comment]
The debug output of the workflow action displays the correct file contents (check step "Run cat cmake/AutoRevision.txt"). That makes this issue even more mysterious.

https://github.com/longturn/freeciv21/actions/runs/7602889261/job/20703953195

**Comment by lmoureaux** [comment]
This is because we run `git archive` without committing the new AutoRevision file:
```
git archive --format=tar.gz --prefix=Freeciv21-v3.0-patch.3/ -o $PWD/build/Freeciv21-v3.0-patch.3.tar.gz HEAD
```
