### ISSUE TITLE
The server sent an invalid or unknown requirement.  

### ISSUE THREAD

**Issue by 3dsf** [longturn/freeciv21#2197]
**Describe the bug**
> **[warning] freeciv21-client - The server sent an invalid or unknown requirement.
> [warning] freeciv21-client - The server sent an invalid or unknown requirement.**

**To Reproduce**
1. Normal use of program

**Expected behavior**
No warning

**Screenshots**

**Platform and version (please complete the following information):**
 - OS: Linux 64bit
 - Freeciv21 version: freeciv21-client 3.1.765794.5-alpha
 - Ruleset/Longturn game (if applicable): LeagueA5

**Additional context**

**Comment by lmoureaux** [comment]
This is because the server sends effects before nation groups, and effects can refer nation groups. The warnings are about effects affecting only barbarian nations.
