### ISSUE TITLE
Create confirmation dialogue when disbanding units

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#2201]
Simple "Are you sure (Y/N)?" or, if you want, "We assume you are not senile like Corbeau, but let's ask, just in case: are you sure? (Y/N)"

I mean, it can be a critical irreversible thing. There is a confirmation dialogue when upgrading units so it would make sense to have it when removing them.

Thank you.

**Comment by lmoureaux** [comment]
Agreed with the first version. I think it's a usability issue so I reclassify as a bug.

**Comment by blabber** [comment]
I took a look at the code (`latest`) and disbanding units from the unit menu, the corresponding shortcut and the units view all seem to have a confirmation dialog.

I guess there is another way to disband units I am not aware of, so @Corbeau-1, could you describe how you disbanded your units without a confirmation dialog?

**Comment by jwrober** [comment]
You can disband in the city view

**Comment by blabber** [comment]
> You can disband in the city view

You mean right click on unit and select "You're fired"? This also has a confirmation dialog.

But I guess there is always one more way to disband your units - and I don't know the client too well yet.

**Comment by Corbeau-1** [comment]
I pressed Shift-X to select all units of the same type and then Ctrl-D.

*BUT*... I now did the same and *got* the confirmation dialogue... Damn!

**Comment by lmoureaux** [comment]
Can we close this then? Or are you sure you didn't get it the first time?

**Comment by Corbeau-1** [comment]
We can close it. It was either a glitch in the client or a glitch in my brain. Looking at previous history, the latter is far more probable. I apologise to everyone for wasting their time.
