### ISSUE TITLE
select client button with enter key

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#2228]
**Is your feature request related to a problem? Please describe.**
Most apps nowadays accept enter as the selector for a button/option choice

**Describe the solution you'd like**
Update client to accept enter as a selection

**Additional context**

https://stackoverflow.com/questions/11887938/how-to-make-a-qpushbutton-pressable-for-enter-key

**Comment by lmoureaux** [comment]
Duplicate of #1685
