### ISSUE TITLE
Change river/road/rail/maglev shape depending on terrain class

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#2232]
Related to #786, but not quite the same.

**Comment by hugomflavio** [comment]
1) Change loop:  https://github.com/longturn/freeciv21/blob/3f3be589df3526e5aaf4f168be5df0d0c7c52ab2/client/tileset/tilespec.cpp#L3362-L3371

2) Fix structure: https://github.com/longturn/freeciv21/blob/3f3be589df3526e5aaf4f168be5df0d0c7c52ab2/client/tileset/tilespec.cpp#L229-L248

3) Fix drawing: https://github.com/longturn/freeciv21/blob/master/client/tileset/tilespec.cpp#L3790

**Comment by hugomflavio** [comment]
While working on point 1, we decided to remake the tile_setup_road function. It is gone now. Instead, there will be `tile_setup_crossing_separate`, `tile_setup_crossing_parity`, `tile_setup_crossing_combined`, and `tile_setup_river`

**Comment by hugomflavio** [comment]
the `SET_SPRITE` family of macros was replaced with the new `assign_sprite` function. We should look into `load_sprite`, `sprite_vector_init`, and `sprite_vector_append`. It might make sense to at minimum rename the last one to `assign_sprite_vector`.

**Comment by lmoureaux** [comment]
> We should look into `load_sprite`, `sprite_vector_init`, and `sprite_vector_append`. It might make sense to at minimum rename the last one to `assign_sprite_vector`.

Or just use `std::vector`/`std::list` instead of a custom vector...

**Comment by jwrober** [comment]
Discord Convo: https://discord.com/channels/378908274113904641/1221168847109882046/1221168847109882046

**Comment by jwrober** [comment]
PR #2241 is associated with this issue.
