### ISSUE TITLE
Touchpad Scroll on Wayland not working

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2236]
**Describe the bug**
The touchpad scroll only works left/right, up/down and not diagonally on Wayland. Is also laggy/slow. Works fine on X11

**To Reproduce**
1. Set your Linux to use Wayland instead of X11
2. Open a game
3. See error

**Expected behavior**
Mouse events work same on Wayland as on X11

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-alpha.5
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
https://discord.com/channels/378908274113904641/1109113177779732550/1215113440033636464

**Comment by jwrober** [comment]
I'm also on KWin and can reproduce there.

**Comment by lmoureaux** [comment]
But is it related to KWin or does Gnome give the same?

**Comment by blabber** [comment]
FWIW, I can't reproduce this on FreeBSD running sway

**Comment by lmoureaux** [comment]
Works like a charm when using the `xcb` backend with `QT_QPA_PLATFORM=xcb` (so going through XWayland).

**Comment by lmoureaux** [comment]
Scrolling events come in two modes, pixel-based and angle-based. On we get deltas of the form `pixel=QPoint(0,0) angle=QPoint(0,21)` and use the angle ones. On `wayland` we get deltas like `pixel=QPoint(0,-4) angle=QPoint(0,-58)`, and use the pixel ones.
From the documentation:
> Wheel events are generated for both mouse wheels and trackpad scroll gestures. There are two ways to read the wheel event delta: [angleDelta](https://doc.qt.io/qt-5/qwheelevent.html#angleDelta)() returns the deltas in wheel degrees. These values are always provided. [pixelDelta](https://doc.qt.io/qt-5/qwheelevent.html#pixelDelta)() returns the deltas in screen pixels, and is available on platforms that have high-resolution trackpads, such as macOS. If that is the case, [source](https://doc.qt.io/qt-5/qwheelevent.html#source)() will return [Qt::MouseEventSynthesizedBySystem](https://doc.qt.io/qt-5/qt.html#MouseEventSource-enum).

Events on Wayland have `Qt::MouseEventSynthesizedBySystem`, events on XCB have `Qt::MouseEventNotSynthesized`.

--> How are we supposed to use the pixel deltas in the first place? They don't feel like pixel differences at all.

**Comment by lmoureaux** [comment]
> --> How are we supposed to use the pixel deltas in the first place? They don't feel like pixel differences at all.

Qt itself uses `angleDelta` everywhere. Will follow suit
