### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [longturn/freeciv21#2262]
**What should be documented? Is there something wrong in the documentation?**
Even though the flatpak is official, it still shows up as unverified on Flathub, so people who find it through there don't know it's official

**Do you have suggestions?**
You can verify the app a few different ways. Here's a link to Flathub's verification documentation for developers https://docs.flathub.org/docs/for-app-authors/verification

**Comment by jwrober** [comment]
Closed via https://github.com/longturn/www/pull/43
