### ISSUE TITLE
Vision bug

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#2290]
**Describe the bug**
AquaBlueMind reported a weird vision-related bug privately on Discord. Opening this issue to keep track of it

**To Reproduce**
1. Unknown as of yet

**Platform and version (please complete the following information):**
 - OS: unknown
 - Freeciv21 version: 3.0.x
 - Ruleset/Longturn game (if applicable): LeagueA5

**Comment by jwrober** [comment]
Uh.. That is about as non-descriptive as you can get. Anything more avail to work from?

**Comment by lmoureaux** [comment]
Yes - privately because it's about a running game.

**Comment by lmoureaux** [comment]
> It was my city but Vlad conquered it serval turns ago. Then a few turns ago it suddenly showed up to me like this, I hadn't touched the city. Vlad says that it still shows as his city.

![image](https://github.com/longturn/freeciv21/assets/22327575/fd6e4cc5-309c-4918-a543-0432d00970f7)
![image](https://github.com/longturn/freeciv21/assets/22327575/de7c5084-e011-43ae-ba1b-b85d4f299acf)

Visible on T112, started around T104

**Comment by lmoureaux** [comment]
I couldn't reproduce from the saves, unfortunately. Will reopen if we can reproduce...
