### ISSUE TITLE
Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2293]
**Describe the bug**

```
Wayland does not support QWindow::requestActivate()
```

**To Reproduce**
1. Start a Linux session on Wayland (not X11)
2. Start client from command-line
3. See error

**Expected behavior**
We support Wayland with no errors

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-beta.1]
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Found while testing PR 2288, but don't think its releated.

**Comment by lmoureaux** [comment]
It's a Qt limitation, `requestActivate` is meant to bring the window to the front but Wayland doesn't allow that (or Qt doesn't know how to do it). I don't think there's anything we can do about it, it's a standard Qt API that we do want to use on platforms that support it.

**Comment by lmoureaux** [comment]
Closing since there isn't much we can do about this.
