### ISSUE TITLE
KLocalizedString: Using an empty domain

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2294]
**Describe the bug**

```
[warning] freeciv21-client - KLocalizedString: Using an empty domain, fix the code. msgid: "&Yes" msgid_plural: "" msgctxt: "@action:button"
[warning] freeciv21-client - KLocalizedString: Using an empty domain, fix the code. msgid: "&No" msgid_plural: "" msgctxt: "@action:button"
[warning] freeciv21-client - KLocalizedString: Using an empty domain, fix the code. msgid: "&Yes" msgid_plural: "" msgctxt: "@action:button"
[warning] freeciv21-client - KLocalizedString: Using an empty domain, fix the code. msgid: "&No" msgid_plural: "" msgctxt: "@action:button"
```

**To Reproduce**
1. Start client from command line
3. See error

**Expected behavior**
No localized string errors

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux -- KDE Neon running Qt 6
 - Freeciv21 version: 3.1-beta.1
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
Found while testing PR 2288, but don't think its related. I am running on KDE Neon w/ Qt6, however compiling like normal on Qt5. Don't know if its related, but thought I'd mention it.

**Comment by lmoureaux** [comment]
Looks like a bug in the latest Kde platform plugin.

**Comment by lmoureaux** [comment]
`KLocalizedString` is part of Ki18n, which we do not use. So it's not our bug. More context about this warning in [this blog post](https://blog.martin-graesslin.com/blog/2014/06/how-to-test-and-fix-translations-for-frameworks-5-applications/)
