### ISSUE TITLE
Angry citizens not working

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#2299]
please fix

**Comment by lmoureaux** [comment]
What does "not working" mean?

**Comment by Corbeau-1** [comment]
The way I understand it, they simply don't appear when they are supposed to (when unhappiness increases and all citizens are already unhappy). I didn't experience it myself, but other people reported it, the last information about it was "not fixed" and I didn't see any claim that it *was* fixed. Also, no mention of it anywhere on Github so my assumption, based on all available info, is that the bug is still on.

**Comment by hugomflavio** [comment]
Can confirm citizens do get angry if one tries hard enough :grin: 

![image](https://github.com/longturn/freeciv21/assets/40389021/0f22354b-c3f7-4268-9f40-d226f55912d2)

**Comment by lmoureaux** [comment]
The above is LTX, seems to work fine there. Note that angry citizens have to be enabled explicitly in `cities.ruleset` (`parameters.angry_citizens = TRUE`).
