### ISSUE TITLE
Can't scroll through the units present in a city when spying

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#2302]
**Describe the bug**
Can't scroll through the units present in a city when spying. Only the first row is visible.

**To Reproduce**
1. Spy a city with ~ 20 units inside
2. Try to scroll down on the units list
3. Profit

**Expected behavior**
The units list should scroll down.

**Screenshots**
![image](https://github.com/longturn/freeciv21/assets/40389021/57d8bbcd-7edb-499d-a3e5-9c6e96bb8589)
(the scroll bar is there, but neither scrolling nor clicking and dragging worked)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 3.1-beta.1
 - Ruleset/Longturn game (if applicable): LT83

**Comment by lmoureaux** [comment]
Related to #2286
