### ISSUE TITLE
Not a bug but hurtful behaviour: Don't move unit right away when X is pressed

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#2303]
**Describe the bug**
Accidentally pressing X with a unit selected will send that unit running away immediately.

**Preferred behavior**
Since X is not commonly used, changing the behaviour so there's a pop-up to confirm, or so that the X unit only moves at the end of the turn (like auto-workers do), would give the player time to correct the order in the event of a mistake.

**Comment by lmoureaux** [comment]
Went for the much easier fix of changing the default shortcut to Shift+X

**Comment by hugomflavio** [comment]
Oooh that's actually awesome! Nice!
