### ISSUE TITLE
Opening city dialog from city list (F4) doesnt work

### ISSUE THREAD

**Issue by mir3x** [longturn/freeciv21#232]
Somethign strange popups in background

**Comment by lmoureaux** [comment]
screenshot?

**Comment by mir3x** [comment]
![image](https://user-images.githubusercontent.com/43116166/103444578-b9f43b00-4c69-11eb-95a1-d7d269f2c4f0.png)

**Comment by lmoureaux** [comment]
So:

* [ ] Need to switch to the game tab (and closing the city screen should switch back?)
* [ ] Need to make sure the layout is correct
