### ISSUE TITLE
QT Win32 mode prevents log to stdout

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2324]
**Describe the bug**
We had a player using fc21 on windows that was trying to debug something. We asked him to start the game from a command prompt expecting to see log to `stdout` just like you get on Linux. Turns out its broken on Windows for the client and other pure GUI apps (game/client, modpack, ruledit)

**To Reproduce**
1. Open command prompt to the folder that fc21 is installed in
2. Run fc21 from the command line such as `freeciv21-client.exe --debug info`
3. Notice no log to `stdout`
4. Try the same with the server such as `freeciv21-server.exe --debug info`
5. Notice log to `stdout`

**Expected behavior**
Should log to `stdout` when run from command line

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Windows
 - Freeciv21 version: 3.1-beta.1 and older
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
This setting removes the capability. It also removes an annoying command window that opens when running the game from a shortcut or double-click on the exe. 

https://github.com/longturn/freeciv21/blob/master/cmake/FreecivDependencies.cmake#L139

**Comment by lmoureaux** [comment]
This is actually a feature of the Windows operating system, see https://stackoverflow.com/a/113032.
