### ISSUE TITLE
Research view loses scroll position 

### ISSUE THREAD

**Issue by blabber** [longturn/freeciv21#2329]
**Describe the bug**
Reported in Discord: 
> In the 3.1.beta.1 I notice that whenever I open the tech tab it starts at the far left/beginning of the tech screen even through if I had just opened it a sec ago and moved the bar over so far. As I recall it would remember where I moved the bar in the stable release?

I confirmed that the older versions did not lose the scroll position.

**To Reproduce**
1. Open research view
2. Scroll somewhere in the tree
3. Return to map and reopen research view
4. See that the research view is scrolled back to origin

**Expected behavior**
When the research view is reopened, the tree should be scrolled to the position where you left the view. 

**Platform and version (please complete the following information):**
 - OS: FreeBSD FreeBSD 14.1-RELEASE-p2
 - Freeciv21 version: 3.1-beta.1

**Comment by blabber** [comment]
All views are losing their state (scroll positions etc.), tracking and restoring them is possible, but I think we should take our time to check if we could restore the old behavior from stable (not destroying the instances).

**Comment by lmoureaux** [comment]
Regarding the research tab, it would also be good to autoscroll to make the current tech visible.
