### ISSUE TITLE
Release: AutoRev not able to create a pull request

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2370]
https://github.com/longturn/freeciv21/actions/runs/10763923007/job/29846017502

**Comment by jwrober** [comment]
Maybe we just need to add a `git stash` to the command set

**Comment by lmoureaux** [comment]
Git stash won't do. It's this nasty commit we have in the tree and prevents you from switching branches unless you try really hard...

**Comment by jwrober** [comment]
Recent PR didn't resolve this issue.
