### ISSUE TITLE
Allow ESC to close build window

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#2383]
![300168893-4d2d67c5-8d2a-4226-970b-7f778b221f3e](https://github.com/user-attachments/assets/358cbbca-d181-4421-8b15-031df6942b2d)

This window (widget?) is somewhat tricky to close. ESC doesn't close it, I need to click _somewhere else_, but there is a possibility that clicking _somewhere else_ may activate _something else_. So, basically, ESC would do.

**Comment by lmoureaux** [comment]
This will be added in the next version. As a workaround, you can use right click or the "Cancel" button at the end of the list.

**Comment by Corbeau-1** [comment]
Wait, you could close it with right-click?

_facepalm_

**Comment by lmoureaux** [comment]
Yeah it's one of those "features" one can only discover by reading the code

**Comment by Corbeau-1** [comment]
I mean, to be honest, rightclick is for me even more convenient thatn ESC.

In cases like this it would probably be cool just to put up a note in a visible place, something like this:
![image](https://github.com/user-attachments/assets/e34bcab7-a133-4fd7-b50d-fe58798bc372)
