### ISSUE TITLE
"You're Fired" action is confusing

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2392]
**Is your feature request related to a problem? Please describe.**
We have a unit action called "You're Fired" that allows a player to disband a unit inside a city to recoup some shields. The term "You're Fired" is confusion.

**Describe the solution you'd like**
Replace with "Disband Unit" or something more clear.

**Describe alternatives you've considered**
None

**Additional context**
Came up on Discord: https://discord.com/channels/378908274113904641/912500712833974322/1285687494247055422

**Comment by lmoureaux** [comment]
Freeciv renamed this, I think we should use the same name.
