### ISSUE TITLE
Error message: Assertion order_sub_tgt == -1 failed

### ISSUE THREAD

**Issue by shoilf** [longturn/freeciv21#2394]
**Describe the bug**
Error message: Assertion order_sub_tgt == -1 failed

**To Reproduce**
I loaded to !9 save file and saw the error message:
[!9.sav.gz](https://github.com/user-attachments/files/17114078/9.sav.gz)
Next save after a few turns didn't have the error message when loading in or playing.

**Expected behavior**
An error message appears but doesn't seem to do anything.

**Screenshots**
![image](https://github.com/user-attachments/assets/11dd58da-fb74-4716-8ffb-aa014be8ae3f)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: Version 3.1-beta 2
 - Ruleset: LT85

**Additional context**
Single-player game with cheating AI, freights do not also work.

**Comment by lmoureaux** [comment]
Thanks for the report! Upon investigation the orders in the file are all for paratroopers with ACTION_PARADROP in their goto path. The warning is harmless.
We completely ignore the `sub_order` field in the goto code, which is likely why it doesn't have the expected value of -1.
