### ISSUE TITLE
Science dialog not refreshed when getting a tech from a hut

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#2405]
**Describe the bug**
When getting at tech from a hut, the science dialog and the top bar are not refreshed properly

**To Reproduce**
1. Load [hut-bug.tar.gz](https://github.com/user-attachments/files/17386509/hut-bug.tar.gz)
2. Take Goyaalé
3. Use the knight to enter the hut at 74,113 (in Japanese territory)
4. You get Leadership for free
5. Check the science report

**Expected behavior**
The science shows that you got Leadership

**Screenshots**
![image](https://github.com/user-attachments/assets/2f8439e7-c9a3-4454-b989-50b8a65fa10f)

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: 7d1b0fc55c73d32eda67434103b332ab424d3de8
 - Ruleset/Longturn game (if applicable): `classic`

**Additional context**

**Comment by blabber** [comment]
Entering the hut yields a random result. Apply this patch to make sure that you get the tech on entering the hut:

``` patch
diff --git a/data/default/default.lua b/data/default/default.lua
index f5cfc7f433..0e0532de82 100644
--- a/data/default/default.lua
+++ b/data/default/default.lua
@@ -126,30 +126,7 @@ end
 
 -- Randomly choose a hut event
 function _deflua_hut_enter_callback(unit)
-  local chance = random(0, 11)
-  local alive = true
-
-  if chance == 0 then
-    _deflua_hut_get_gold(unit, 25)
-  elseif chance == 1 or chance == 2 or chance == 3 then
-    _deflua_hut_get_gold(unit, 50)
-  elseif chance == 4 then
-    _deflua_hut_get_gold(unit, 100)
-  elseif chance == 5 or chance == 6 or chance == 7 then
-    _deflua_hut_get_tech(unit)
-  elseif chance == 8 or chance == 9 then
-    if not _deflua_hut_get_mercenaries(unit) then
-      _deflua_hut_consolation_prize(unit)
-    end
-  elseif chance == 10 then
-    alive = _deflua_hut_get_barbarians(unit)
-  elseif chance == 11 then
-    if not _deflua_hut_get_city(unit) then
-      _deflua_hut_consolation_prize(unit)
-    end
-  end
-
-  -- continue processing if unit is alive
+   _deflua_hut_get_tech(unit)
   return (not alive)
 end
 
```

**Comment by blabber** [comment]
Just a note: I suspected that this was another regression introduced by 24e44b9fda37df40cd76b78546657861615c9df8, but according to my tests this isn't true.

**Comment by lmoureaux** [comment]
Oh, we may need to override the Lua random to make this reproducible.

In my test it was also happening with techs from treaties, which is easier to test.

**Comment by blabber** [comment]
This reproducible in v3.0-patch.4 too.

**Comment by lmoureaux** [comment]
The server sends an update with Leadership completed and the current research still set to Leadership. It should be `A_UNSET` instead.
