### ISSUE TITLE
Select by fortified/sentried

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#2410]
**Is your feature request related to a problem? Please describe.**
There is no mechanism to select units based on their status fortified or sentry

**Describe the solution you'd like**
The unit selection dialog could use options to be able to select all sentried or fortified units as criteria

**Describe alternatives you've considered**
None

**Additional context**
Came up on Discord via a QnA

**Comment by lmoureaux** [comment]
This seems to exist in the Advanced Unit Selection dialog (Ctrl+E).

**Comment by jwrober** [comment]
Yep, you are correct
![image](https://github.com/user-attachments/assets/f3506542-390d-4b5f-855b-0fb49ad1cc8a)
