### ISSUE TITLE
Output_Waste_by_Distance units are not correct

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#2434]
**Describe the bug**

![image](https://github.com/user-attachments/assets/d9aa0212-d8f9-4fc5-921a-7e1897f13d0e)

This is 100x too much.

**To Reproduce**
1. Play Sim06

**Expected behavior**

The easiest solution seems to be `%/100 tiles`

**Platform and version (please complete the following information):**
 - OS: [e.g. Windows 10 / Linux / macOS]
 - Freeciv21 version: 3.1-beta.2
 - Ruleset/Longturn game (if applicable): Sim06

**Additional context**

**Comment by lmoureaux** [comment]
For anyone interested: `effects.cpp:1171`

**Comment by blabber** [comment]
I have a change in my local, that changes the help dialog to show effects alphabetically sorted. While I am already there, I will take care of this issue.
