### ISSUE TITLE
Remove limitation [15, 85] for landmass

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#2444]
Currently it is impossible to generate map that would contain 0% or 100% land. The limit is set to 15% and 85%. Please remove it.

I presume there may be generator crashes, however, this is up to the ruleset maker to solve, that is, to not set up such numbers to cause the crash.

Reason: creating some exotic tile/rulesets that require some more flexibility.

**Comment by lmoureaux** [comment]
The limits are indeed there to protect the map generators from running into infinite loops. [Some mapgens](https://longturn.readthedocs.io/en/latest/Coding/mapgen.html#island-based-generators) have their own hard-coded limits.

Which limit is annoying you the most?

**Comment by Corbeau-1** [comment]
Ideally, I'd like 100% land, 0% water. But if it creates problems, I could live with a small percentage of water, the smaller the better.

Mapgen is irrelevant. Do whatever is easier. I only need one to work.

If you want, you can grab these for testing, I weeded out surplus stuff so there are less terrain types. When testing, just paste them into a ruleset, other files may remain the same. I took it from Royale.

Additional problem: I have set hills (steepness) and temperature to **zero** and wetness to **100** and I'm still getting a lot of hills and deserts. I'd like some, but not this much. I smell a hidden threshold. Can anything be done about it?

[exotic-ruleset.zip](https://github.com/user-attachments/files/17933271/exotic-ruleset.zip)

**Comment by lmoureaux** [comment]
Just tried RANDOM with landmass 100, worked perfectly. I expect FRACTAL and FRACTURE to work as well. The merge request linked above lifts the limitation.

**Comment by Corbeau-1** [comment]
Thank you!

Did you look into this?

(Ok, maybe I should have made two separate issues...)

> Additional problem: I have set hills (steepness) and temperature to **zero** and wetness to **100** and I'm still getting a lot of hills and deserts. I'd like some, but not this much. I smell a hidden threshold. Can anything be done about it?
> 
> [exotic-ruleset.zip](https://github.com/user-attachments/files/17933271/exotic-ruleset.zip)

**Comment by lmoureaux** [comment]
Yes, different issue... Which generator?
