### ISSUE TITLE
How upload new flag(nations)

### ISSUE THREAD

**Issue by TAWKEHT** [longturn/freeciv21#247]
I write and draw new (real)nations with flags, but how add it? i see: 

"**Uploads are disabled**.
File uploads require push access to this repository."

**Comment by lmoureaux** [comment]
Hi @TAWKEHT ! 

The step to add a nation are as follows:

* Add flags to `data/flags`
* Add nation `ruleset` files to `data/nation`
* Reference your ruleset files in `data/default/nationlist.ruleset`

The typical Github workflow is to make changes in your own fork (I see you have already created one) and then create a pull request to this repository. If you can't figure it out, just upload your files to this issue and I'll add them.

**Comment by TAWKEHT** [comment]
thx

**Comment by lmoureaux** [comment]
Now documented on the Wiki: [Adding a nation](https://github.com/longturn/freeciv21/wiki/Adding-a-nation).
