### ISSUE TITLE
Units in ships can be upgraded even if the ship can't carry the upgraded unit

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#248]
Seen in an LT game with a Leo upgrade. Horses in a caravel can be upgraded to armors.

**Comment by ilkkachu** [comment]
Fixed here for stock Freeciv here: https://www.hostedredmine.com/issues/921691

Probably needs similar one-line fix here-ish(??):
https://github.com/longturn/freeciv21/blob/master/common/unit.cpp#L1872

**Comment by lmoureaux** [comment]
Thanks for the link! Will definitely copy the fix.
