### ISSUE TITLE
ChangeLog and NEWS no longer needed?

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#268]
These are holdovers from freeciv.  News could be changed to point to a WiKi page where updates are shared. Not sure if a ChangeLog file is needed any more.

**Comment by jwrober** [comment]
Just noticed doc/fetchnews.pl. So definitely think having a WiKi News page and then need to figure out if it makes sense to alter the file (or create a new python file) to fetch and create local text file.

**Comment by lmoureaux** [comment]
The change log appears to be merely a dump of `git log`, maybe hand-edited. News are best located in tag notes/Github release notes. I would remove both of them.
