### ISSUE TITLE
The city dialog should display how many citizens can be made content with existing buildings

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#269]
Currently, the citizens made content by buildings are shown, but one can't see how much the city can grow before the first unhappy citizen appears. This makes celebration harder.

Initial proposal is to add it to the relevant tooltip in the Happiness tab. In the long run some more graphical depiction could be added.

**Comment by pranavtifr** [comment]
Lol. I just saw this. Anyways, relevant thing I did with the city-report tab

https://github.com/pranavtifr/freeciv/commit/ea17ba086b7602472d8b364dd92bf9ad0fc9b308
