### ISSUE TITLE
Zooming artifacts

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#295]
Seen with hexamplio (notice how hex edges are visible):

![image](https://user-images.githubusercontent.com/22327575/108613242-57f5bd80-73f0-11eb-8e00-95de4da6c9c6.png)

**Comment by mir3x** [comment]
Find algorithm which scales hex to perfect hex 
or scale to bigger hexes and see other artifacts.

**Comment by lmoureaux** [comment]
Postponing for when we make a better thought renderer.
