### ISSUE TITLE
Build errors following INSTALL instructions

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#297]
If you follow the directions in the current INSTALL file, it doesn't work.

**Comment by lmoureaux** [comment]
How does it break?

**Comment by jwrober** [comment]
In Debian section the `sudo apt install build-dep-freeciv` is invalid for starters. It should be `sudo apt build-dep freeciv` and then `sudo apt install <packages>`. And then also the next section of deps to be installed has a number of duplicates.

Also testing build on a fresh install of Debian produces some other issues, which might need to be captured elsewhere.

**Comment by lmoureaux** [comment]
This works for Ubuntu 20.04: [windows/Dockerfile](https://github.com/longturn/freeciv21/blob/master/windows/Dockerfile)

**Comment by lmoureaux** [comment]
@jwrober did #302 fix everything reported here?

**Comment by jwrober** [comment]
Yes I believe so. Other issues are potential build related per environment so probably handled in other issues.
