### ISSUE TITLE
Hide the warning: Unused entry: "spec.artists"

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#298]
Shipped sprite spec files have an "artists" field documenting who drew the tiles. This key isn't known by the tileset loader and hence generates warnings. The tileset loader should be made to ignore the field by issuing the appropriate `secfile_lookup_str()` call.

The tileset loading code is in `client/tilespec.cpp`.

**Comment by DobbyK** [comment]
Instead we should actually add a spec file for the tilesets so we can give credit to the artists.

**Comment by lmoureaux** [comment]
> Instead we should actually add a spec file for the tilesets so we can give credit to the artists.

Each tileset does have a spec file.

**Comment by lmoureaux** [comment]
Turns out this was already done but shipped tilesets were "buggy".
