### ISSUE TITLE
Use JSON for the modpack installer

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#308]
The modpack installer is backed by Freeciv's old INI-like file format. JSON is ubiquitous on the Internet and Qt has built-in support for it. It is a safer (no custom parser) and better supported format.

Since there isn't a lot of FCMP content in the wild and the files are usually small, changing the format won't impose too much of a burden on content makers. Hopefully it will also help setting up a Longturn-backed FCMP server.

**Comment by lmoureaux** [comment]
I currently have this JSON format for the index file:
```json
{
  "info": {
    "options": "+Freeciv-modlist-Devel-3.1-2019.Jul.15",
    "message": "Hello!!"
  },
  "modpacks": [
    {
      "name": "test",
      "version": "abc",
      "license": "WTFPL 1.0",
      "type": "Group",
      "url": "https://longturn.net/",
      "notes": "Fails to install"
    }
  ]
}
```

It's a direct translation of the existing section file-based format. @jwrober since you've played with this, do you see something to improve?

**Comment by jwrober** [comment]
In the `modpacks` section, the URL is the "base" URL for the files. Not sure what the `url` parameter notes in the sample. We will need a `files` section as well to list the files to grab. Current FCMP allows you to grab the source and then change the destination. Modpacks do have "types", not sure what group is. There is Scenario, TileSet, SoundSet and MusicSet currently IIRC. The current application lists this in the GUI and if we want to host our own server I think it important to notate the different types.

**Comment by lmoureaux** [comment]
Sorry I was unclear. The snippet above is an example index file: each entry is an individual modpack and the `url` points to the modpack control file (not sure how to call them?).

The existing modpack types are defined [here](https://github.com/longturn/freeciv21/blob/master/tools/fcmp/modinst.h#L41-L55). I should create a wiki page about this.
