### ISSUE TITLE
Forbid buying a settler at size 1 then using the shields

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#310]
> you can buy the setller with 30/40 shields, which is cheapier then buy, let say a caravan for 30/50 shields

This can be fixed by forcing a loss of half/all the built shields when changing production.

**Comment by ilkkachu** [comment]
Another possibility would be to check the city size when buying, and prevent the buy if size <= pop cost. Advantage, wouldn't need to go back next turn and recalculate stuff.

Disadvantage: city disband flag: if we allow buying when size == pop cost, the player can
then prevent disbanding (possibly flipping the flag back), and get the buy as before.
If we disallow buying when size == pop cost, it slows down disbanding cities when you actually want it.

A possible solution might be to lock the disband flag if you have bought that turn.
(or if have bought && producing unit && unit has nonzero pop cost)
