### ISSUE TITLE
Generate .desktop and AppStream files

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#331]
These are required to show menu entries in Linux and BSD desktop environments. One can start from the Freeciv ones still found in the `bootstrap` folder (I find this folder name meaningless so bonus point if you take them out).

The CMake function [`file(GENERATE OUTPUT ...)`](https://cmake.org/cmake/help/latest/command/file.html#generate) or [`file(CONFIGURE OUTPUT ...)`](https://cmake.org/cmake/help/latest/command/file.html#configure) can be used to fill in paths with absolute paths from [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) paths. This should only be done if the target is neither Windows nor Mac (nor Android).

**Comment by lmoureaux** [comment]
Here's the [AppStream spec](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps). Freeciv recently renamed their files to something like `org.freeciv.freeciv.desktop` to avoid being kicked out from distros, we should do the same with `net.longturn`.

**Comment by jwrober** [comment]
I am using the following IDs. I actually found that Spec from Debian's website on my own yesterday ;)
```
net.longturn.freeciv_modpack_qt
net.longturn.freeciv_qt
net.longturn.freeciv_ruledit
net.longturn.freeciv_server
```
I don't think we need AddStream files for ruleup and the CLI Modpack Installer. Those are more special purpose for experts that would know they are there to be used.

**Comment by jwrober** [comment]
Closed
