### ISSUE TITLE
Windows/Msys2 - i18n files not installed

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#335]
This is I think due to the way we do translations on Windows/Msys2. There is no `install()` in the `CMakeLists.txt files`. They should end up in the `$Install_Dir/share/locale` directory at package creation time and populate the `translations` component.

This issue should cover two tasks

- [ ] Get the i18n files to install for Windows/Msys2
- [ ] The files should be copied and compiled as part of the translations component for the NSIS installer

**Comment by lmoureaux** [comment]
Are they installed properly on Linux?

**Comment by jwrober** [comment]
Yes I think so. On my system I install to `~/Install`. There is `share/locale` directory with the files copied over. Don't get that on Windows/Msys2.

![image](https://user-images.githubusercontent.com/23037938/111052684-a7913d00-8422-11eb-945d-526b69d61e63.png)

**Comment by lmoureaux** [comment]
`LOCALEDIR` is probably wrong on MSYS?

https://github.com/longturn/freeciv21/blob/36b583c2d75c7e1d9229adb985ccfbba78ff6fe7/cmake/GettextTranslate.cmake#L288-L291

**Comment by jwrober** [comment]
Not sure, but that `install()` function definitely doesn't do anything on Msys2.
