### ISSUE TITLE
Windows/Msys2 - freeciv-server when called from freeciv-qt "gets stuck"

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#341]
Debug console code shown

```
[info] freeciv-qt (unknown:0) - Starting freeciv-server at C:/Program Files/Freeciv21 v3.1.0/freeciv-server.exe
[debug] freeciv-qt (unknown:0) - sending packet type=PACKET_SERVER_JOIN_REQ(4) len=46 to server
[debug] freeciv-qt (unknown:0) - sending request 1
```

@lmoureaux is aware.  If you open a command prompt and run the server by itself it starts fine.

![image](https://user-images.githubusercontent.com/23037938/110970213-2309c600-831f-11eb-8a5d-4fc650e8bdc1.png)

**Comment by mir3x** [comment]
Server seems to be alive and running but client seems to be not connected to it.

**Comment by mir3x** [comment]
Reopen, It didnt fixed :D
