### ISSUE TITLE
Change city view to show Present Units all across the bottom

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#342]
Right now you see a single unit in a vertical scroll. Seems that expanding the windows horizontally to show more units present in the site would make it easier to manage units in city, especially in late game when a city can have tons of units inside.

![image](https://user-images.githubusercontent.com/23037938/111015694-caaee480-836f-11eb-8909-fef465a787b3.png)

**Comment by lmoureaux** [comment]
Actually this list should already be expanding horizontally. Maybe it's due to the theme?

**Comment by jwrober** [comment]
I would think the window would size out horizontally and only get a second row when the width gets to be the same as the city dialog. Some examples of what is occurring now.

4 Units
![image](https://user-images.githubusercontent.com/23037938/111916272-159fba80-8a48-11eb-826a-f13e1463c09f.png)

3 Units
![image](https://user-images.githubusercontent.com/23037938/111916287-2819f400-8a48-11eb-96b9-18a40a8d1740.png)

2 Units
![image](https://user-images.githubusercontent.com/23037938/111916300-3bc55a80-8a48-11eb-9306-9a287d176c45.png)

**Comment by lmoureaux** [comment]
Hexamplio: 2 units
![image](https://user-images.githubusercontent.com/22327575/111916602-020e4700-8a7c-11eb-9240-cf512d92523b.png)

3 units:
![image](https://user-images.githubusercontent.com/22327575/111916631-20744280-8a7c-11eb-8720-977ec0457fd9.png)

4 units:
![image](https://user-images.githubusercontent.com/22327575/111916651-31bd4f00-8a7c-11eb-8f02-b625ed29be75.png)

**Comment by lmoureaux** [comment]
Maybe this is related?

![image](https://user-images.githubusercontent.com/22327575/114315295-a2e1a680-9afe-11eb-85ec-954e7fa3a4b3.png)

**Comment by jwrober** [comment]
Master as of today

2 Units - not good
![image](https://user-images.githubusercontent.com/23037938/134981878-149eeb05-2ca9-4567-adcf-1b21cfe3b4f1.png)

3 units - good
![image](https://user-images.githubusercontent.com/23037938/134981963-6f34af9e-e2f5-4c00-83c4-17cbc6578b27.png)

**Comment by jwrober** [comment]
I'm using Aviation Tileset and using NightStalker Theme. Here are my font settings.
![image](https://user-images.githubusercontent.com/23037938/135175472-368e241c-01ef-427e-a140-c96f0be3215c.png)

The problem for 2 units goes away if I switch to the system theme, but persists with the others. The problem also persists for the following tilesets: amplio, amplio2, cimpletoon, and hexemplio. It goes away for the really small tilesets.

I am using OOB stuff. My general thought is the box should never wrap to a second line until the box width would get bigger than the whole city dialog width.

**Comment by lmoureaux** [comment]
I'm not seeing this problem with the same fonts, tileset, and theme. However your fonts are larger than mine (I counted the pixels). Do you use a display-wide scaling factor? What's your default Sans Serif font (System Settings > Fonts)?

**Comment by lmoureaux** [comment]
Postponing because I can't figure out how to reproduce.

**Comment by jwrober** [comment]
I can no longer recreate this. I've tried different font settings. I've tried multi-monitor vs single monitor. I've tried video scaling (e.g. 125% scaling on monitors). So somewhere we "fixed" this I think. Closing.
