### ISSUE TITLE
The client clips the output values for tileset at 9

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#345]
We need to fix this because in LTT we go beyond 9 in some cases.

**Comment by lmoureaux** [comment]
I think you had a link to the problematic line? cazfi's granularity project might lead to improvements in the area.

**Comment by pranavtifr** [comment]
Ya. It is this constant value. 
```#define NUM_TILES_DIGITS 10```
https://github.com/freeciv/freeciv/blob/0b29e0ff39ed0aef887f3222ca37d281b71b8b9b/client/tilespec.c#L112

It is clipped at that value to avoid the issue at higher values gracefully. 
```      food = CLIP(0, food / game.info.granularity, NUM_TILES_DIGITS - 1);```
https://github.com/freeciv/freeciv/blob/0b29e0ff39ed0aef887f3222ca37d281b71b8b9b/client/tilespec.c#L4818

The proper way to do this is probably to allow the tileset to decide on the max value.
