### ISSUE TITLE
Generate a better "late game" screenshot for inclusion in the AppStream Files

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#355]
I created a real quick and dirty screenshot

https://github.com/longturn/freeciv21/blob/master/dist/freeciv-screenshot-2048x1112.png

I think it would be better to have a well staged late game screenshot in 16:9 resolution as an ehancement.

**Comment by lmoureaux** [comment]
Maybe from [this save](https://github.com/longturn/freeciv21/files/6178114/t1.sav.gz) I've been using for testing? Though I'd prefer an iso topology.

Another option is the same game as in the README, but I'd have to find it… from 2017 IIRC…

**Comment by jwrober** [comment]
I'll give the save link a whirl. Worst case I will play an AI game to get to what we want. Something like the README is what I was thinking too.

**Comment by lmoureaux** [comment]
[Here](https://cdn.discordapp.com/attachments/748498672752263204/785982720093847603/freeciv-T0337-Y01883-auto.sav.bz2) is the save for the home page.

**Comment by mir3x** [comment]
jwrober if u like that classic theme, you can update it as you like. You just edit that resources.qss file in Classic folder and then reload theme with ctrl+shift + f5

**Comment by jwrober** [comment]
@lmoureaux @mir3x Any thoughts to what we want to see in a staged screenshot? I've got an AI game I am playing that is working  late into the tech tree. I can build Cruiser, Destroyer, Cavalry, Rifle and Marines right now.  Was thinking of getting into advanced flight and staging an attack on an enemy capital city.

**Comment by lmoureaux** [comment]
Yes, something like that -- advanced era units besieging a city. I used Mech. Inf. in the screenshot on the Github home page. Maybe some proof of combat would be nice (units with incomplete HP, enemy units out of cities, ruins…)
