### ISSUE TITLE
Change the default topology back to isometric

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#357]
The commercial games use hex, freeciv uses hex… let's be different!

**Comment by jwrober** [comment]
Should we make our own Isometric Tileset to go along with this?

**Comment by lmoureaux** [comment]
This issue is more about the technical change (just a one liner IIRC). Anyway…

If you know skilled artists who have time to dedicate to this task, new art is always welcome! There are some old tilesets [here](https://freeciv.fandom.com/wiki/Tileset_Downloads) that could be revived, be it only for the modpack installer. And of course [amplioLT](https://github.com/hugomflavio/amplioLT) and [RoundSquare](https://github.com/HansLemurson/RoundSquare/).
