### ISSUE TITLE
Investigate City crashes the server

### ISSUE THREAD

**Issue by ec429** [longturn/freeciv21#362]
In a test game with my Aviation ruleset, I attempted to Investigate an enemy city with a scouting unit.  The server emitted several exceptions like `[critical] freeciv-server (unknown:0) - T049: Trying to put 1919251245 into 8 bits; it will result 45 at receiving side.`, and then segfaulted.

Unfortunately, the backtraces aren't useful, as they have only hex addresses.  (From a quick poke with gdb, it appears the built freeciv-server has no debugging symbols.  What runes do I have to give cmake to get a debug build?)

**Comment by lmoureaux** [comment]
Can't reproduce with a spy in the `civ2civ3` ruleset. It would be useful if you could share a save.

To enable debug symbols, you can either set the standard `CXXFLAGS` environment variable or pass `-DCMAKE_BUILD_TYPE=Debug` to CMake at configure time.

**Comment by ec429** [comment]
[two21_investigate_city_bug.sav.gz](https://github.com/longturn/freeciv21/files/6191565/two21_investigate_city_bug.sav.gz)
I can reliably crash the server by moving the Zeppelin Scout at (38, 13) north and investigating Glesga.

I rebuilt with `cmake . -B build -DFREECIV_ENABLE_RULEDIT=OFF -DFREECIV_ENABLE_RULEUP=OFF -DCMAKE_BUILD_TYPE=Debug`; `cmake --build build` but `freeciv-server` still has no debug symbols :(

**Comment by lmoureaux** [comment]
No crash on my side:
![image](https://user-images.githubusercontent.com/22327575/112198312-45e48600-8c0d-11eb-925a-fed2293cf2e5.png)

`fc-aviation` commit is:
```
commit b00e01174a8485c79bdd32fd1fdd842aceb0dc09 (HEAD, origin/fc21)
Author: ...
Date:   Mon Mar 22 09:04:58 2021 +0000

    Make building Aircraft Slipways require a coastal city
    
    It just seems weird for an inland city to be a seaplane-making hub.
```

`freeciv21` commit is:
```
commit 849c55487bf5375e1dcff92929e4954376a72f66 (HEAD -> bugfix/investigate-server-crash, origin/master)
Author: ...
Date:   Mon Mar 22 03:01:09 2021 +0100

    Point the modpack installer to the Longturn list
    
    Points to:
    
        https://github.com/longturn/modpacks
    
    See #350
```

Built using GCC 10.2.0 on Arch Linux with Qt 5.15.2.

**Comment by mir3x** [comment]
Maybe you use wrong binary? Like from /usr or /usr/local from previous installations ?

Good idea is to uninstall and never install and use only from main directory:

**Comment by ec429** [comment]
Huh, that's interesting.

The build process used to put a copy of each binary from `build/` into the top level of the repo, and I was running that, not realising that it hadn't been updated for months.

With the up-to-date binary, this now works fine.  Closing.
