### ISSUE TITLE
Merge Freeciv 2.6.x Music commits to Freeciv21 Master

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#375]
Need to evaluate this commit to overall function of music play in fc21

https://github.com/longturn/freeciv21/commit/a2a215fe9dd41aacac869e767dba5f6e813f9b59

The following commits from legacy freeciv will make music play work much better in freeciv21

https://github.com/freeciv/freeciv/commit/a9d4a4dd054d5320bc1afa44b913fd7e3c82a66b
https://github.com/freeciv/freeciv/commit/e355db22740839b9048a4e6648965a71a7651442
https://github.com/freeciv/freeciv/commit/6b50a5b0bc6650d4c03992aa1fa71643c26fb5ed
https://github.com/freeciv/freeciv/commit/2b24adcae463e4c646c804b82a1f7610008288d0
https://github.com/freeciv/freeciv/commit/ff2462fa627cb48cf8ee34d0736381065c941fb4

**Comment by lmoureaux** [comment]
The bug that triggered this issue is that only the intro music is ever played. The game fails to switch to anything else.
