### ISSUE TITLE
New city dialog doesnt handle going to a different tab well

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#377]
This is the new city dialog in all its glory. 
![image](https://user-images.githubusercontent.com/30164619/112657388-aadced80-8e52-11eb-87dc-6bd148e32ba3.png)

Now, after going to "cities", "nations" or "research" (whatever goes away from the view window and back, 
It ends up looking like this. 
![image](https://user-images.githubusercontent.com/30164619/112657529-cfd16080-8e52-11eb-9985-b3ef36087075.png)

**Comment by lmoureaux** [comment]
Dup of #232 (even if slightly more general).
