### ISSUE TITLE
Linux, BSD, etc: Install .desktop and .appstream.xml

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#402]
For desktop environments to find them, the `.desktop` files need be installed to `share/applications`. The AppStream XML files go to `share/metainfo` (and not `share/appdata` like Freeciv 2.6 does :facepalm:). This should be done on Linux & friends, let's say any UNIX that is not :apple:.

(`share` is `${CMAKE_INSTALL_DATAROOTDIR}`)

**Comment by jwrober** [comment]
On a recent Linux compile and install I got these files in my local share directory along with the binaries and other files.

![image](https://user-images.githubusercontent.com/23037938/116479721-bce0f000-a845-11eb-8463-294ffddaacde.png)

So I think this is fixed/closed but can't seem to find the commit that changed install behavior. Could use someone else to test and see if they get similar behavior.

**Comment by lmoureaux** [comment]
> On a recent Linux compile and install I got these files in my local share directory along with the binaries and other files.

Sorry I missed this comment for too long. Installing the `.in` files is certainly not correct, the paths inside should be substituted first.
