### ISSUE TITLE
Freeciv21 goals

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#403]
This issue is there to discuss the goals of the project. They should be included in the `README` at some point.

Here are some general directions in no particular order:

:bookmark: **Improve the client experience.** Redo the worst parts and iron out the rest. For instance:
* Improve the option windows by grouping the settings and laying them out according to their importance.
* Make it less cumbersome to join a multiplayer game. Ideally one should just click a link in the browser.

:bookmark: **Document** the game rules through the built-in help system :book:. Remove hard to guess "tricks" that give an advantage. The game should be about city management :cityscape:, buildings :building_construction:, terrain :deciduous_tree:  and units :crossed_swords:.

:bookmark: **Promote user-made content** (rulesets, tilesets…) through the user interface. Give reasonable flexibility to artists :heart:.

:bookmark: **Modernize the code** and lower the bar to contribute. Use standard formats and delegate to external libraries when possible.

:bookmark: **Make it easier to host games** while respecting the privacy of the users and GDPR-like laws :policeman:. This is more for `longturn.net` but other websites could benefit from this work.

**Comment by jwrober** [comment]
I personally would like to see ways to improve the "richness" of the client - in similar manner as Wesnoth (they have an extremely rich client). I know this would require more graphics designers. I know we recently went isometric for default tileset, but I personally like overhead. The position of N feels more natural that way. The graphics are dated and honestly feel old. For me, the number one goal is this issue. Really want to modernize the client, make it look and feel more modern.  It is not just gameplay any longer.

I like the current theme options in the client. Would need to determine which is "default / first class" vs the others and make major investments there. Goes back to richness of the client. Can a theme "ask" for a musicset or a tileset?

I also like the idea of documentation. Really need to improve the in-game help so that it includes everything in the ruleset so that a player does not have to know how to read a ruleset to understand the entirely of the rules of the game they are playing. I think we should be able to include links to more documentation on the github wiki as well in the client.

I like the "make it easier to host games" so others can do games with family and friends on their own.

**Comment by lmoureaux** [comment]
One of the great things about Freeciv is its support for very different rules. This allows Classic, LTT, Warciv, Aviation and Alio to be all powered by the same engine. But it's also something that's very hard: the difference between classic and civ2civ3 is thin, and even completely different rules like Ancients end up not feeling *that* different vs the AI. From the gameplay perspective, maybe we should focus on providing a diversity of presets and scenarios. Make it take longer to "finish" the game -- not just one game, the whole Freeciv.

Wesnoth is a very good reference that clearly promotes user-made content, but one has to keep in mind that it's also different since most of the game (terrain, combat system, core units) is fixed. Apart from a few full-scale universes with dozens of new units, much of the depth comes from the storytelling capabilities of the engine, which I don't think should be a priority for Freeciv. Something we could aim for is support for "add-ons" that add a few units, improvements or terrains on top of standard rules. Having just a few of those would open up the number of possible games dramatically. It would also be much easier to contribute two units and their graphics than another complete ruleset.

**Comment by pranavtifr** [comment]
>  The graphics are dated and honestly feel old
I agree. To me, handing these things via modpack will help the graphics designers. We previously discussed this on discord, but putting it out here for posterity. We should strive to keep everypart which doesnt have an explicit cpp code in it be modpack installable, and on top of that try to refactor such that even interface elements could be just changed easily by installing a theme. Having addon support for interface elements too is probably a good step in this direction and is a reasonable longterm goal. In short, extend usermade content to the client interface too. 

Regarding documentation, I obviously agree to make it as transparent as possible. But I would just like to pitch in a wild idea on top of that, how about exposing the ruleset to the user via the client ? Having the help show the corresponding and relevant ruleset entry will also expose more players to the underlying workings of the game. 

I am a proponent of exposing underlying mechanics on top of documentation. By making it easier to find, we give a starting point for curious people to atleast initiate discussion and learn.
 For eg.. Very few beginners know about unit ID. But if it shows up in the message.. It is no longer hidden and curious people would understand the mechanics of the game involving that. Same with city IDs.. Most people dont know how to use that to determine the age of the city. But if it shows up SOMEWHERE. Curious people would incorporate it into their game.

**Comment by lmoureaux** [comment]
Re documentation: I just created a tag `document-me` to collect PRs worth documenting in a change log. I assigned it to [6 PRs so far](https://github.com/longturn/freeciv21/pulls?q=is%3Apr+label%3Adocument-me), but didn't go though the complete list.

**Comment by jwrober** [comment]
What format you thinking for a change log? Is it a collection of Wiki pages with a tag or something?

**Comment by lmoureaux** [comment]
I'm not sure how I'll do the change log, probably as a Wiki page linked from a Github release (and with the main items also in the release text). The versioning/release process isn't defined yet…

The changelog will probably be divided into changes for players, ruleset editors, artists and a misc category for server operators etc. Many PRs are bug fixes or infrastructure changes without an effect on the game and should be fully transparent.

**Comment by lmoureaux** [comment]
> What format you thinking for a change log? Is it a collection of Wiki pages with a tag or something? What criteria did you use to determine which PRs needed documentation? I could argue that most should have some kind of change log entry associated with them.

I added notes to the [first release](https://github.com/longturn/freeciv21/releases/tag/v3.0-alpha.1) based of the PRs tagged `document-me`. Suggestions and :bulb: welcome

**Comment by lmoureaux** [comment]
I don't think keeping this issue open is useful since there is no clear way of resolving it. Closing.
