### ISSUE TITLE
Add city size and unhappy to general tab

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#438]
Classic freeciv GTK 3 client shows it under info section. Makes it super easy to see how large a city is while working in the city dialog.

![image](https://user-images.githubusercontent.com/23037938/115077624-fd468280-9ec3-11eb-940a-2216610d6d61.png)

**Comment by lmoureaux** [comment]
What's "unhappy"? The number of unhappy citizens?

**Comment by jwrober** [comment]
> What's "unhappy"? The number of unhappy citizens?

Yes, exactly. 

I wonder if it makes sense to show total size, # content, # happy, and # unhappy. For us color blind folks its not always clear using the color coded citizens in the top of the city dialog. That extra work is probably another issue though. Don't want to pile on here.
