### ISSUE TITLE
Modpack installer for Windows TLS initialization failed

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#443]
The Linux compiled version works as expected. Top picture is Windows, bottom is Linux

![image](https://user-images.githubusercontent.com/23037938/115166266-e0eb4700-a077-11eb-8e65-b4ffadfaf5aa.png)

**Comment by jwrober** [comment]
This might be part of the problem

```[warning] freeciv21-modpack-qt - QSslSocket::connectToHostEncrypted: TLS initialization failed```

**Comment by lmoureaux** [comment]
Need to install the CA certificates.

**Comment by jwrober** [comment]
With the NSIS or is this a Windows thing?

**Comment by jwrober** [comment]
Classic FC installs `/ssl/certs/ca-bundle.crt`. I see a similar file in MSys2 at `/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt`. Need to figure out how to inlcude in CPack.

**Comment by lmoureaux** [comment]
It seems that we'll also need some supporting code to load the certificates into the [`QSslConfiguration`](https://doc.qt.io/qt-5/qsslconfiguration.html).
