### ISSUE TITLE
Freeciv Server QProcess::CrashExit

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#445]
I'm playing AI based game on pretty current code. I am getting the above error at TC. Attached is save game and debug output.

[freeciv-T0214-Y01565-auto.sav.zip](https://github.com/longturn/freeciv21/files/6354189/freeciv-T0214-Y01565-auto.sav.zip)
[freeciv21-debug.log.zip](https://github.com/longturn/freeciv21/files/6354192/freeciv21-debug.log.zip)

**Comment by jwrober** [comment]
Update, if you don't do any attacking of the Pirate city or move any of the other units you can go to the next turn.

**Comment by lmoureaux** [comment]
Probably unrelated, but this AI thinks Cruisers will defend his cities well:
```
T214: Iroquois Skohare(37,100) (s2) {d800 u0 g0}  m_a_c_d urgency=0 danger=100 num_def=0 our_def=0
T214: Kaintwakon::Guerilla Warfare (want 78.000000, dist 10)  + 25 for Partisan to defend Skohare
T214: Kaintwakon::Tactics (want 338.000000, dist 5)  + 88 for Alpine Troops to defend Skohare
T214: Kaintwakon::Conscription (want 228.000000, dist 2)  + 73 for Riflemen to defend Skohare
T214: Kaintwakon::Amphibious Warfare (want 793.000000, dist 6)  + 12 for Marines to defend Skohare
T214: Kaintwakon::Combined Arms (want 3.000000, dist 24)  + 1 for Paratroopers to defend Skohare
T214: Kaintwakon::Labor Union (want 197.000000, dist 21)  + 63 for Mech. Inf. to defend Skohare
T214: Kaintwakon::Steel (want 56.000000, dist 6)  + 18 for Cruiser to defend Skohare
T214: Kaintwakon::Rocketry (want 2414.750000, dist 23)  + 136 for AEGIS Cruiser to defend Skohare
T214: Iroquois Skohare(37,100) (s2) {d800 u0 g0}  m_a_c_d wants first defender with 200.000000
```

**Comment by lmoureaux** [comment]
No crash for me on Linux with the latest `master`. Can you be more specific about what units I need to move (or maybe save just before TC if you can reproduce from there).

**Comment by jwrober** [comment]
I compiled 80d2c15. I followed these steps and then clicked check to end turn and got a crash.

- Attack Lodz w/ Cavalry at 23,60 twice
- Move 1x Calvary from stack at 23,61 to 23,60 + fortify all
- Move destroyer from 26,58 to 23,58
- Attack Lodz w/ Destroyer at 23,58 3x times
- Load Calvary from Gdansk to Transport at 20,67
- Load Calvary from Warszawa to Transport at 20,67
- Engineer build road at 15,75
- Move Destroyer at 18,15 to 24,91 (straight down)
- Engineer irrigate at 28,71
- Move Transport w/ loaded Explorer at 77,19 along coast to 82,15

Besides the first 4 moves, the rest are done as the game progresses through the next unit needing something done with it.

**Comment by lmoureaux** [comment]
Reproduced, floating point exception. Going to run though the debugger now.

**Comment by lmoureaux** [comment]
```
Program received signal SIGFPE, Arithmetic exception.
0x0000555555787333 in military_advisor_choose_build (ait=0x555555d051e0 <ai_types>, pplayer=0x5555573040a0, pcity=0x555557f5a6f0, mamap=0x555555d22000 <wld>, ul_cb=0x0)
    at ../ai/default/daimilitary.cpp:1544
1544          danger = 100 * qdanger / our_def;
(gdb) bt
#0  0x0000555555787333 in military_advisor_choose_build (ait=0x555555d051e0 <ai_types>, pplayer=0x5555573040a0, pcity=0x555557f5a6f0, mamap=0x555555d22000 <wld>, ul_cb=0x0)
    at ../ai/default/daimilitary.cpp:1544
#1  0x00005555557661d4 in dai_manage_cities (ait=0x555555d051e0 <ai_types>, pplayer=0x5555573040a0) at ../ai/default/daicity.cpp:929
#2  0x00005555557332ec in dai_do_last_activities (ait=0x555555d051e0 <ai_types>, pplayer=0x5555573040a0) at ../ai/default/aihand.cpp:775
#3  0x000055555571c4c2 in cai_do_last_activities (pplayer=0x5555573040a0) at ../ai/classic/classicai.cpp:473
#4  0x0000555555592509 in end_phase () at ../server/srv_main.cpp:1440
#5  0x000055555557f30f in freeciv::server::end_phase (this=0x55555654d7f0) at ../server/server.cpp:702
#6  0x000055555557f69d in freeciv::server::update_game_state (this=0x55555654d7f0) at ../server/server.cpp:810
#7  0x000055555557e98a in freeciv::server::input_on_socket (this=0x55555654d7f0) at ../server/server.cpp:518
```

**Comment by lmoureaux** [comment]
Corbeau's crash on Windows is the same as this issue, so it was not fixed.

**Comment by lmoureaux** [comment]
Going to revert https://github.com/longturn/freeciv21/commit/c67fc6a2058028582ecdaca48d847bfdb4db1112, the quadratic part is already handled in `assess_danger` (`vulnerability` is multiplied by itself) and this makes it a power 4 in total.
