### ISSUE TITLE
Don't short-circuit combat against defensepower 0

### ISSUE THREAD

**Issue by ec429** [longturn/freeciv21#456]
`unit_versus_unit()` has a clause that `if (defensepower == 0) *def_hp = 0;`, to skip running the combat if the defender is guaranteed to lose.
However, if the attacker has a finite `Combat_Rounds`, then without this clause the defender could potentially survive.
It would suit my aims for my ruleset if this clause were removed, so that a zero-defense unit's HP were meaningful.  Is there any reason why we can't?

**Comment by lmoureaux** [comment]
I consider this a bug, the shortcut should only be taken if `Combat_Rounds` isn't finite.

**Comment by ec429** [comment]
In that case, does the shortcut even need to exist at all?  It'd be simpler to just remove it.  (I thought for a moment it might be meant to guard against an infinite loop, but it doesn't even do that — it'd need to be looking at defense _firepower_ to do that.)
