### ISSUE TITLE
Goals of the Documentation Project

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#481]
Top-level issue used to help us determine goals for this effort. We can create discrete issues as ideas are decided upon.

**Comment by jwrober** [comment]
Louis suggests we use Doxygen to create code level documentation; See #480

**Comment by jwrober** [comment]
Should we have a "Release Notes" book that can be used to help us with the `document me` tag we have on issues and PRs?

**Comment by pranavtifr** [comment]
Louis suggests we use sphinx for user documentation. 

> Sphinx can be used to create beautiful and easy to navigate documentation. It could be used to document the game, the rulesets, and even modding formats. Given this wide possible scope, organization of the documentation may be challenging.

**Comment by lmoureaux** [comment]
There are many, many things that can be documented. In no particular order:

* Rulesets
* Internal code
* Administration (e.g. database support)
* UI of the client, modpack installer, ruleset editor
* Server settings
* Ruleset settings
* Tileset format
* Soundset format
* I'm probably missing a few

**Comment by jwrober** [comment]
Would our "User Manual" book replace in game help?

**Comment by jwrober** [comment]
> There are many, many things that can be documented. In no particular order:
> 
> * Rulesets
> * Ruleset settings

Aren't these the same as in game help?

**Comment by lmoureaux** [comment]
> Would our "User Manual" book replace in game help?

No. Internal help can have privileged interaction with the client (e.g., clicking on units in the field) and adjusts to changes in custom rulesets. They should be in sync for our own rulesets, which is a challenge.

>> There are many, many things that can be documented. In no particular order:
>>
>> * Rulesets
>> *  Ruleset settings
>
> Aren't these the same as in game help?

"Rulesets" yes. By rulesets settings I meant documentation for ruleset authors.

**Comment by lmoureaux** [comment]
I don't think keeping this issue open is useful since there is no clear way of resolving it. Suggesting to close.
