### ISSUE TITLE
Setup account for LT on ReadTheDocs.io

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#482]
Suggest a URI as -- longturn-manuals.readthedocs.io

**Comment by lmoureaux** [comment]
Free RTD accounts are only for individuals. I create one in my own name.

**Comment by lmoureaux** [comment]
* Project: https://readthedocs.org/projects/longturn/
* URLs: `longturn.readthedocs.io` and `longturn.rtfd.io`
