### ISSUE TITLE
Choose which of doc/README.* we want to keep

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#485]
Maybe not all of them are worth translating to Sphinx.

**Comment by lmoureaux** [comment]
Quick look:

* `BUGS`: Needs almost a complete rewrite
* `README`: Small parts that can be salvaged, the rest can be thrown away
* `CodingStyle`: Irrelevant, delete
* `HACKING`: Mostly for coders, but some parts may be relevant for tilesets
* `HOWTOPLAY`: Play guide, last updated 2016... relevant
* `README.achievements`: Relevant, for ruleset editors
* `README.actions`: Relevant, for ruleset editors
* `README.agents`: A grand plan that never realized. Relevant for coders (CMA)
* `README.AI`: Internal docs, no idea if still relevant
* `README.AI_modules`: Not supported
* `README.attributes`: Relevant, internal (used by CMA)
* `README.delta`: Relevant, internal (network protocol)
* `README.effects`: Relevant, for ruleset editors
* `README.fcdb`: Only the `database.lua` part is still relevant, for sysadmins
* `README.governor`: Relevant, for players
* `README.graphics`: Relevant, for tileset artists. Reportedly incomplete and insufficient.
* `README.modplack_installer`: Relevant for players, up-to-date
* `README.msys2`: Relevant, devs on Windows
* `README.nations`: Probably relevant. We also have a wiki page about this
* `README.packaging`: I don't know
* `README.rulesets`: Relevant, ruleset authors
* `README.scenarios`: Relevant, devs and very skilled scenario makers
* `README.scorelog`: Relevant, devs
* `README.sound`: Could be reused as an introduction for sound spec docs
* `REAMDE.tilesets`: Relevant, for tileset artists. Reportedly incomplete and insufficient.

In addition, there are (many outdated) translations of some of these and the `man` pages.

**Comment by jwrober** [comment]
PR #579 took care of `HOWTOPLAY`, 'FAQ`, 'README.governor`, and `REAMDE.modpack_installer`.

**Comment by jwrober** [comment]
PR #675 took care of `BUGS`, `CodingStyle`, andh `HACKING`.

**Comment by jwrober** [comment]
PR #679 took care of `README.achievements` and `README.actions`

**Comment by jwrober** [comment]
PR #681 took care of `README.fcdb` and `README.msys2`

**Comment by jwrober** [comment]
@lmoureaux - mind have another look at the `README.ai*` files? I don't think either are useful any longer and think we can delete them.

**Comment by lmoureaux** [comment]
After the first section or two, `README.AI` has info about how the AI works, I'd keep it as code documentation (maybe convert to a md file for Doxygen to parse).

`README.AI_modules` can be trashed.

**Comment by jwrober** [comment]
PR #685 took care of `TODO`, `README.AI`, `README.AI_Modules`, `README.sound`, and `README.scenarios`.
