### ISSUE TITLE
Update cosmetics of the Sphinx docs

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#495]
Ths Sphinx docs are now live at https://longturn.readthedocs.io/en/latest/, but they badly need some customization (and content, but that is handled elsewhere). At the very least we should add the Longturn logo.

**Comment by jwrober** [comment]
Should have a style guide of some kind in CSS kept in the `docs/source/_static` directory.

**Comment by jwrober** [comment]
https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by lmoureaux** [comment]
Here is a svgz version of the logo I made: [Logo.svg.gz](https://github.com/longturn/freeciv21/files/6705632/Logo.svg.gz). It doesn't have all of the gradients but I think it's good enough. It may need to be simplified to be included in the repo.

**Comment by jwrober** [comment]
Closed via PR #572
