### ISSUE TITLE
Client cuts passwords at 47 chars

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#530]
The client uses `MAX_LEN_NAME` (=48) where it ought to be `MAX_LEN_PASSWORD` (=~~256~~ 512):

https://github.com/longturn/freeciv21/blob/673c43d823d60ec5aaf412ad967013051f21798d/client/gui-qt/page_network.cpp#L454
https://github.com/longturn/freeciv21/blob/673c43d823d60ec5aaf412ad967013051f21798d/client/gui-qt/page_network.cpp#L442

Found by panch93

**Comment by DobbyK** [comment]
I found where `MAX_LEN_PASSWORD` is definite and it equals 512?
https://github.com/longturn/freeciv21/blob/80d2c1546a2e3b7398daa7dd677b2ef54f6d1d8c/common/networking/connection.h#L42

Is this the correct place where it was defined and is it a mistake, or did you make a mistake?

**Comment by lmoureaux** [comment]
`MAX_LEN_NAME` in `page_network.cpp` is wrong, it should be `MAX_LEN_PASSWORD`.

**Comment by DobbyK** [comment]
> `MAX_LEN_NAME` in `page_network.cpp` is wrong, it should be `MAX_LEN_PASSWORD`.

I don't think you understood my question, sorry. You said MAX_LEN_PASSWORD = 256, yet where (i assume/believe) it is definied, defines it as 512. Is that a mistake and should that be 256, or did you type it incorrectly?

**Comment by lmoureaux** [comment]
Oh sorry I mistyped, that's what named constants are for :blush: It should be `MAX_LEN_PASSWORD` regardless of its actual value.

**Comment by DobbyK** [comment]
I would suggest that we not have it equal 512 as that is a really long password, and even know if someone wanted it really secure could easily risk not being able to get into the account.

**Comment by lmoureaux** [comment]
A limit at 512 bytes doesn't hurt either... Changing it would break compatibility with existing clients and servers.

**Comment by DobbyK** [comment]
> A limit at 512 bytes doesn't hurt either... Changing it would break compatibility with existing clients and servers.

Makes sense. #531 for fix then.
