### ISSUE TITLE
Problem with installing Freeciv21 client: need admin privileges

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#534]
Normally, one would expect that every more complex game needs admin privileges to be installed on a computer, but I got spoiled by the original Freeciv. So, is there any way to get around it and make it possible to install Fc21 without digging into the important system stuff? I'm guessing I'm not the only one whose main computed is the business one.

**Comment by jwrober** [comment]
Modern Windows 10 requires admin privileges to add files to `C:\Program Files` or `C:\Program Files (x86)`. We don't install anything to `C:\Windows` or `C:\Windows\System32` that would also require admin. Current workaround is to install to an alternate location such as `C:\Games`.

**Comment by jwrober** [comment]
In Discord conversation @Corbeau-1 let me know that you get the UAC prompt right away and no option to install in alternate location. Will need to review settings in NSIS script to correct.
