### ISSUE TITLE
Autoconnecting to a auth-enabled server doesn't show the password prompt

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#540]
Try:
```
$ freeciv21-client -a fc21://louis94@longturn.net:5050
```
This should allow to connect to LTEx24Avi.

What actually happens is that the server asks for the password, but the client fails to recognize it. Hence it doesn't switch to `PAGE_NETWORK` and doesn't enable the password field.

Passing the password on the command line works.

**Comment by 3dsf** [comment]
@lmoureaux 
Could you give me an example of how to pass the password on the command line?

**Comment by lmoureaux** [comment]
Using URL syntax: `freeciv21-client -a fc21://user:password@longturn.net:5555`

**Comment by 3dsf** [comment]
thanks, it's been a while since I command line logged into anything and brain*time=mush.
