### ISSUE TITLE
Include Turn Number and Server time stamp in [ ] brackets for messages in chat window

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#549]
Similar to how it works on legacy freeciv GTK client

**Comment by lmoureaux** [comment]
Blauwal:

> So it’s now working like in the GTK+ client? I’d say that’s not the best solution, but actually quite confusing. Why? Because the times refer to days, not to turns, but it’s turns that are shown. So I’d argue for either date + time or turn number + time within the turn (that is, time passed since turn start).

**Comment by lmoureaux** [comment]
This is a server setting:
```
/set ec_info enabled
```
