### ISSUE TITLE
When a unit is renamed, don't show duplicate information on middle click

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#551]
![image](https://user-images.githubusercontent.com/23037938/126814256-f537972f-7d50-4557-9387-627c26dd33fe.png)

**Comment by lmoureaux** [comment]
If you call a Battleship "Bismark" it will show `Battleship "Bismark"`... the duplication is only because you introduced duplication in the name.

**Comment by jwrober** [comment]
The issue I am trying to point out here is the duplicate information of Location, Native Coordinates, Terrain, F/P/T, and Territory. Nothing wrong with Unit Seabees "Master Seabee" in there. I named the unit Master Seabee, so this is correct.

**Comment by lmoureaux** [comment]
Sorry to have overlooked this, "unit is renamed" pointed to the other duplication in the screenshot :sweat_smile:
