### ISSUE TITLE
Sidebar needs to resize more sensibly.

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#556]
**Describe the bug**
If you reduce the width of the sidebar the formatting is weird. 

**To Reproduce**
1) Option > Interface
2) Reduce side bar size

**Current Behavior**
Icons gets squished, fonts remain the same size and wrap badly. 

**Expected behavior**
The icons should maintain a 1:1 aspect ratio and the fonts should be automatically reduced. The user should not be expected to tweak all the other elements of the interface to get the width right. 

**Screenshots**
Current Sidebar with reduced width. 
![image](https://user-images.githubusercontent.com/30164619/126869931-72a6f74a-9604-4859-9720-7575cf3e5dc9.png)

**Platform and version (please complete the following information):**
 - OS: Linux (Arch)
 - Freeciv21 version: 3.0-alpha3

**Comment by lmoureaux** [comment]
The sidebar code needs a complete overhaul. It's full of manual layout and drawing.
