### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#561]
**What should be documented? Is there something wrong in the documentation?**
`README.md` is stale. Needs a link to read the docs to promote new `docs` as well as some instructions for a newbie to get started quickly.

**Comment by lmoureaux** [comment]
Useful resources:

* https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes
* https://github.com/matiassingers/awesome-readme
