### ISSUE TITLE
Windows: Tilesets with accents in the path cannot be used

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#565]
**Describe the bug**

[According to `kevin551`](https://discord.com/channels/378908274113904641/402213035865014272/869225691273654312), after downloading Aviation using the Modpack installer on Windows the tileset is not found by the client.

**To Reproduce**
1. Start the client, connect to `LTEx24`
2. Install Aviation from the Modpack installer
3. Try to switch to the Aviation tileset

**Expected behavior**

Aviation is visible in every possible tileset selection option.

**Platform and version (please complete the following information):**
 - OS: Windows (10?)
 - Freeciv21 version: 3.0-alpha3
 - Ruleset/Longturn game (if applicable): `LTEx24`

**Comment by jwrober** [comment]
On Windows, the modpack installer places the files into `C:\Users\<UserID>\AppData\Roaming\freeciv21\3.0`. If you are in a game with the client open when you download something with the modpack installer the client is not aware of the change until you exit the game/close the client and then re-open and connect to a game again.

**Comment by lmoureaux** [comment]
If it's not refreshed automatically, we need a refresh button :sweat_smile:

**Comment by jwrober** [comment]
Behavior is the same on Linux so a refresh option makes sense.

**Comment by lmoureaux** [comment]
Tested on Windows, for me everything was up-to-date after installing without restarting the client. Maybe one needs to reopen the settings window.

However, selecting aviation in the settings didn't work and I had to use the "Choose another tileset" menu.

**Comment by lmoureaux** [comment]
> However, selecting aviation in the settings didn't work and I had to use the "Choose another tileset" menu.

--> #740 

This is just about a refresh button, not for beta1

**Comment by lmoureaux** [comment]
This issue happened for the SG2 game. I was able to reproduce it on `wine` with 3.0-patch.2:
```
This is Freeciv21 version 3.0.16116404.2-patch.
Built against Qt 5.15.11, using 5.15.11

This instance of Freeciv21 searches the following directories for data files:

* Z:/home (user)
* Z:/home/louis (does not exist)
* C:/users/louis/Application Data/freeciv21/3.0 (user)
* D:/a/freeciv21/freeciv21/build/install/data (does not exist)
* C:/users/louis/Local Settings/Application Data/freeciv21 (does not exist)
* C:/ProgramData/freeciv21 (does not exist)
* Z:/home/louis/.wine/drive_c/Program Files/Freeciv21 (user)
* Z:/home/louis/.wine/drive_c/Program Files/Freeciv21/data (user)
* Z:/home/louis/.wine/drive_c/Program Files/Freeciv21/data/freeciv21 (does not exist)
```

**Comment by lmoureaux** [comment]
I can reproduce on Wine. The trick is to add a non-ASCII character somewhere in the ruleset path. For instance, a ruleset called `é` won't be found.
