### ISSUE TITLE
fc21 server announces itself as legacy fc

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#578]
**Describe the bug**
When you start a server in the terminal, the output shows freeciv not Freeciv21

**To Reproduce**
1. Open a new terminal
2. Start a new server instance - e.g. `./freeciv21-server`
3. See error

```jwrober@luthien:~/Install/freeciv21-test/bin$ ./freeciv21-server 
This is the server for Freeciv version 3.0.20210721.3-alpha
You can learn a lot about Freeciv at http://www.freeciv.org/
[info] freeciv21-server - Loading rulesets.
[info] freeciv21-server - AI*1 has been added as Easy level AI-controlled player (classic).
[info] freeciv21-server - AI*2 has been added as Easy level AI-controlled player (classic).
[info] freeciv21-server - AI*3 has been added as Easy level AI-controlled player (classic).
[info] freeciv21-server - AI*4 has been added as Easy level AI-controlled player (classic).
[info] freeciv21-server - AI*5 has been added as Easy level AI-controlled player (classic).
[info] freeciv21-server - Now accepting new client connections on port 5556.

For introductory help, type 'help'.
> 
```

**Expected behavior**
Clearly show we are Freeciv21 as well as point the user to either the github page or longturn.net

**Screenshots**
See output example above.

**Platform and version (please complete the following information):**
 - OS: N/A
 - Freeciv21 version: 3.0-alpha3
 - Ruleset/Longturn game (if applicable): N/A

**Comment by jwrober** [comment]
in the FAQ - I changed it to say this `You can learn a lot about Freeciv21 at https://github.com/longturn/freeciv21`

**Comment by lmoureaux** [comment]
Maybe point to the documentation website?
