### ISSUE TITLE
Client becomes slow in the late game on Windows for some users

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#584]
**Describe the bug**

Precision by fizu on issues that seem rather widespread among Windows users:

Qt Win client problems can be clearly seen on a developed game (LT62, T113) when:

1) Connecting to the game
2) Airdropping units
3) Changing research goal (tested just and client froze for 40 seconds :grimacing: )
4) Whenever I try to move a unit, whose UWT has not passed yet (client freezes for a while)
5) Upgrading units

[T]he combat is faster with Gtk
(Qt sometimes freezes or crashes)
(The process dies (sometimes))

**To Reproduce**

1. Unknown. Seems to happen in late game only.

**Expected behavior**

The client is always fast and sleek.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv version: Freeciv 2.6.x
 - Ruleset/Longturn game (if applicable): LT62

**Comment by lmoureaux** [comment]
Windows Event Log after a crash, also provided by fizu:
![image](https://user-images.githubusercontent.com/22327575/128880963-4a8f4876-5c3c-4a0a-9486-68db8dc390b8.png)

Unfortunately not very informative.

**Comment by jwrober** [comment]
A x86_64 (Win64) compile with newer Qt (5.15.2) did not resolve either.

**Comment by lmoureaux** [comment]
I can reproduce the lags in e94970f441e8defc89b097675ec76ca9487d39da when connecting to LTEx24Avi from a Windows VM (the VM itself is very slow, but 100% CPU for seconds is bad).

**Comment by lmoureaux** [comment]
#615 fixed a performance bug that can explain 1/2/3/4/5. Need confirmation from someone on Windows.

**Comment by lmoureaux** [comment]
There were several fixes to the messages widget that plausibly fix this performance issue. Closing as solved; will open a new one if we see this in a fc21 game.
