### ISSUE TITLE
App window does not start centered

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#586]
**Describe the bug**
When you start the game, the game start menu is not centered on the screen. It starts in one of the corners of the screen.

**To Reproduce**
1. Open terminal window
2. Navigate to installed `bin` directory
3. Start the app with `./freeciv21-client`
4. Notice its not centered

**Expected behavior**
The app starts centered on the screen

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Kubuntu 20.04 LTS -- It seems to work on Windows
 - Freeciv21 version: 3.0-alpha3
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by jwrober** [comment]
https://wiki.qt.io/How_to_Center_a_Window_on_the_Screen

**Comment by lmoureaux** [comment]
Following our discussion on Discord:

* The window geometry should be saved automatically. If not, there is a bug.
* The window manager is in charge of the initial positioning of windows. KWin (the window manager used by Kubuntu) doesn't center new windows by default, but this can be changed in `System settings` > `Window management` > `Window behavior` > `Advanced` (translating back from French so the wording may vary).

So I'm not sure this should be considered a bug.

**Comment by jwrober** [comment]
So this makes a lot of sense and is why it's centered on Windows. The system settings path is accurate on my en_US based Kubuntu. You set the `Window Placement` drop down to "Centered" and the client then loads in middle of the screen. This feels like a FAQ entry or something instead of being a bug. I would want to install base Ubuntu (Gnome) and potentially Fedora (also Gnome) to see if there is a setting needed as well there. I also wonder if Linux Mint (Cinnamon) is impacted as well. Cinnamon desktop is based off Gnome 2.

**Comment by lmoureaux** [comment]
I don't think this deserves a FAQ entry since it's at worst a minor annoyance.

**Comment by lmoureaux** [comment]
[Resolved upstream](https://invent.kde.org/plasma/kwin/-/merge_requests/1631)
