### ISSUE TITLE
Bad start game parameters

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#601]
**Describe the bug**
Starting a game without setting any values, sets some bad parameters

- 'set endturn 32767'
- 'set first_timeout 248400'
- 'set fixedlength enabled'
- 'set huts 0'
- 'set timeout 82800'
- 'set unitwaittime 36000'

**To Reproduce**
1. Start the client
2. Click start new game
3. Notice above options are set
4. click start (change nothing)
5. Notice that you can go to the next turn on your own due to timeout value

**Expected behavior**
The above mentioned parameters are not set. The server parameters from the default ruleset (civ2civ3) are applied.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0-alpha4

**Comment by lmoureaux** [comment]
You probably saved server parameters in another game. Does it happen if you clean the configuration (server settings -- reset -- save)?

**Comment by jwrober** [comment]
Ok i see all the settings in a [server] block in my client rc file.
