### ISSUE TITLE
Don't run GitHub actions for non-code commits

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#629]
**Is your feature request related to a problem? Please describe.**
Every commit includes a full compile of the code. That is wasteful, especially for non-code directories such as `doc` or docs`

**Describe the solution you'd like**
Make the actions smarter for our code base and only run checks that matter

**Describe alternatives you've considered**
None. Leaving things as is seems like a waste of time and resources.

**Additional context**
None

**Comment by jwrober** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by lmoureaux** [comment]
Since some files from `doc` are installed, one can't disable checks for that directory

**Comment by lmoureaux** [comment]
Note that I just made *Ubuntu with GCC*, *Ubuntu with clang*, and the `clang-format` checks mandatory. See [here](https://github.com/github/docs/issues/8926) for what to do in that situation.
