### ISSUE TITLE
New game shows legacy freeciv

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#630]
**Describe the bug**
When you start a new game, the client says that you are playing the Qt client for freeciv. Should be freeciv21 and we only have one client.

**To Reproduce**
1. Open/Start the Client
2. Click "Start New Game"
3. See error

**Expected behavior**
We only have one client and we are Freeciv21. Change accordingly.

**Screenshots**
![ksnip_20210909-175803](https://user-images.githubusercontent.com/23037938/132773315-1ac57bc7-efef-4470-8622-bbdd1487410b.png)

**Platform and version (please complete the following information):**
 - OS: All
 - Freeciv21 version: 3.0-alpha4+
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by pranavtifr** [comment]
Lol, Didnt check the client when I did #610

**Comment by jwrober** [comment]
Closed by PR #635
