### ISSUE TITLE
Improve the CMake logic for translations

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#65]
* Ninja recreates translations every time
* File lists could be fetched automatically from the target sources properties instead of hard coding them.
* Maybe extra-cmake-modules has some helpers?

**Comment by mir3x** [comment]
Maybe just create gmo files in translation dir and run travis with FREECIV_ENABLE_NLS=NO ?

**Comment by lmoureaux** [comment]
Closed by #71
