### ISSUE TITLE
City Window right-panel text gets squished

### ISSUE THREAD

**Issue by HansLemurson** [longturn/freeciv21#665]
When a city has a large number of supported units, the "Supported Units" subpanel expands and seems to squish the rest of the contents of its panel.

**To Reproduce**
Home a large number of units to the same city
Open the city window
Look at squished text in the production numbers window.

**Expected behavior**
The text of the numbers for Food, production, science, etc. should maintain their normal legible spacing.

**Screenshots**
![image](https://user-images.githubusercontent.com/10428933/134789082-cea6b6ab-fe41-4cb8-8256-e4c920aa5494.png)

**Platform and version (please complete the following information):**
 - _OS:_ Windows 10
 - _Freeciv21_ version: 3.0-alpha7
 - _Ruleset/Longturn game:_ classic

**Additional context**
Maybe the scroll-bar should go left/right like it does for the improvements?

**Comment by lmoureaux** [comment]
Perfect report, many thanks!

**Comment by lmoureaux** [comment]
...turns out I did not fix it.
