### ISSUE TITLE
Crash when loading scenario (after previously quitting scenario)

### ISSUE THREAD

**Issue by HansLemurson** [longturn/freeciv21#683]
**Describe the bug**
If you load a scenario, then disconnect or otherwise leave the game, when you try to load a scenario again, the program crashes.

**To Reproduce**
1. Click "Start Scenario Game" (this takes a while)
2. Click "Disconnect" after it loads up
3. In the main menu, click "Start Scenario Game" again.
4. Program should now crash after the "starting local server" message appears.

**Expected behavior**
The menu of scenarios should show up a second time, this being the function of the "Start Scenario" button.

**Screenshots**
How do you show a picture of something crashing?
![image](https://user-images.githubusercontent.com/10428933/136729245-2065c577-4f56-4c91-b139-d46ef747853f.png)

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version:  3.0.20210912.6
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
"Start Scenario Game" seems to take a fairly long time to load up the menu showing all the scenarios.  Could this perhaps be related?

**Comment by HansLemurson** [comment]
10 savegames + 50 autosaves.  All of the saves are stored in `C:\Users\username\AppData\Roaming\Freeciv21\saves`.  I haven't touched the `data` folder in the fc21 install directory.

**Comment by lmoureaux** [comment]
The delay when loading the list is most likely related to the server starting in the background.
