### ISSUE TITLE
Can't read lines in spec files longer than 1kB

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#698]
**Describe the bug**
Trying to parse a spec file with lines longer than 1kB fails. ruleup generates such files.

**To Reproduce**
1. Make a spec file with very long lines (for instance edit a help text in `classic/game/ruleset` and make the line super long)
2. Make freeciv21 try to read it (for instance, load the modified ruleset)
3. Watch parse errors in the terminal

**Expected behavior**
These files can be read just fine.

**Platform and version (please complete the following information):**
 - OS: Linux
 - Freeciv21 version: `master`
 - Longturn game: `SIM30Test`

**Additional context**
Starting SIM30, ruleset upgraded by `ruleup` from 3.0 format.
Worked around by increasing the buffer size at `inputfile.cpp:469` to 100kB.

**Comment by lmoureaux** [comment]
Can't reproduce on Arch… issue with an older version of something?

**Comment by lmoureaux** [comment]
I suspect this is an issue in either Qt or KArchive on Debian Buster.

**Comment by lmoureaux** [comment]
Bug confirmed to be absent on the new Debian `stable` (Bullseye).  I suggest we simply stop officially supporting Buster (`oldstable`). @jwrober thoughts?

**Comment by jwrober** [comment]
For Debian with its long term support model for every stable release, I would say we only support current stable release.

**Comment by lmoureaux** [comment]
Then this can be closed. Will need to upgrade the server before the next game…
