### ISSUE TITLE
Changing the zoom level while in a city dialog causes the dialog to close

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#729]
**Describe the bug**
Changing the zoom level while in a city dialog causes the dialog to close

**To Reproduce**
1. Go to default zoom (ctrl-backspace) -- or use the view menu
2. Open a city dialog box
3. Zoom in one level (shift-+) -- or use the view menu
4. Notice the dialog closes and then the map zooms in one level

**Expected behavior**
The map zooms in one level and so does the city center and the city dialog's size shifts to match the new dimensions.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: All
 - Freeciv21 version: 3.0-Alpha9
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by lmoureaux** [comment]
This is because changing the zoom level reloads the tileset, and reloading the tileset closes the city dialog.
