### ISSUE TITLE
Change the minimum HP to which bombardment can reduce a unit

### ISSUE THREAD

**Issue by pranavtifr** [longturn/freeciv21#731]
**Is your feature request related to a problem? Please describe.**
Bombarding always reduces the unit HP to the hardcoded 1hp. It would be good to generalize that. 

**Describe the solution you'd like**
an effect could change the minimum HP. 

**Describe alternatives you've considered**
The minimum HP can either be as a % of health of the unit or an absolute value

**Additional context**
Keeping it as an effect allows ruleset makers to have improvements and techs which defend against bombarding.

**Comment by ec429** [comment]
I've written an implementation of this (`Bombard_Limit_Pct`).  I'll post a PR soon-ish.
