### ISSUE TITLE
Chat area behaviour is confusing

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#737]
**Describe the bug**

We got soo many questions about this:

* How to expand the chat part?
* How to expand the messages part?
* How to resize it?
* How to move it elsewhere?

**To Reproduce**
1. Give fc21 to a LT player
2. Wait until he asks

**Expected behavior**

The UI should be self-explanatory.

**Screenshots**
![image](https://user-images.githubusercontent.com/22327575/142746032-fca303d0-1654-41e8-bc47-f4ce7224c28f.png)

**Platform and version (please complete the following information):**
 - OS: any
 - Freeciv21 version: all versions thus far

**Additional context**

Messages and chat are especially important for multiplayer.

**Comment by pranavtifr** [comment]
Too add to this from discussions on discord. There has been a consensus to separate chat and messages window and an option to hide them both separately.
