### ISSUE TITLE
Large Scenario (Europe 1900) won't open

### ISSUE THREAD

**Issue by HansLemurson** [longturn/freeciv21#746]
**Describe the bug**
I was trying to load up the Europe 1900 scenario, but every time I do so, the server starts with a "random game" instead.

**To Reproduce**
Start Scenario Game
Choose "europe_1900_ww1"
Load scenario
Server will load a random default game
Lots of server messages appear, but it's not obvious when/why the scenario failed to load.

**Expected behavior**
_The chosen scenario should actually load_ 
Or at least give a useful message about its failure.

**Screenshots**
Hard to take a picture of something that didn't happen.  It would just be a screenshot of a server ready to start a random game with a handful of easy AIs.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0-alpha 9
 - Ruleset:  Standard?  Scenario won't load at all.

**Additional context**
Other scenarios can load, but not this one.  No idea whether it's specific to this scenario, or has a more general cause of trying to load a massive map with 30 players.

**Comment by lmoureaux** [comment]
In the chat:
```
Invalid AI type: 'tex'!
Failure loading savegame!
```

**Comment by lmoureaux** [comment]
As a workaround until the next release you can download "fixed" versions of the scenario:
* [from here](https://github.com/lmoureaux/freeciv21/raw/bugfix/load-wwi-scenario/data/scenarios/europe_1900_WWI.sav) until #748 is merged
* [from here](https://github.com/longturn/freeciv21/raw/master/data/scenarios/europe_1900_WWI.sav) afterwards

#748 should also prevent this error from occurring in the future.
