### ISSUE TITLE
Bug? Stack bribing, suspicious incite city cost 

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#767]
In Sim test game (SIM30 ruleset) a player just bribed multiple stacks of enemy units. Stacks consisted of 2-4 "Raider" units, production cost 5, bribing cost rounded down to zero. 

The issue is not that it's zero, it's that stacks were bribed.

Experiment is underway to check if the same will work for units costing 10 or more.

**edit: The above turns out to be a ruleset issue. Still looking into the thing below.**

Also, city inciting just happened that doesn't conform to the formula:

[incite_cost]
; city_incite_cost = total_factor * (city_size) * (base_incite_cost
;                      + (units_cost) * unit_factor
;                      + (improvements_cost) * improvement_factor)
;                    / ((distance to capital) * 100)
; See city_incite_cost() for more details
base_incite_cost = 1000
improvement_factor = 1
unit_factor = 2
total_factor = 2500

The player says he incited cities (small, size 1 and 2) for less than 50 gold. There was no capital so distance is supposedly set to 32.

**Comment by Corbeau-1** [comment]
Turns out half of the above is a ruleset issue. Still looking into the incite cost thing.

**Comment by lmoureaux** [comment]
Can you provide these data and the actual incite cost for the second part?

![image](https://user-images.githubusercontent.com/22327575/145028803-9f235982-ef43-41ad-b5a9-b616a3802e0e.png)

**Comment by Corbeau-1** [comment]
Sorry, the second part has also just been solved. Another ruleset issue. Sorry for wasted time.

**Comment by lmoureaux** [comment]
No problem :)
