### ISSUE TITLE
Allow for tileset-defined number of unit select frames and frame rates

### ISSUE THREAD

**Issue by hugomflavio** [longturn/freeciv21#777]
**Is your feature request related to a problem? Please describe.**
I am attempting to create a smoother animated unit selection ring. However, the client is hard-coded to receive 4 frames (hardcoded [here](https://github.com/longturn/freeciv21/blob/9ee5b788557d7bef798e2191a705a7938dc8d26b/client/tilespec.cpp#L120)) that last 100ms each (hardcoded [here](https://github.com/longturn/freeciv21/blob/9ee5b788557d7bef798e2191a705a7938dc8d26b/client/tilespec.cpp#L5206)). 

**Describe the solution you'd like**
I would like for the client to be able to interpret two new variables provided by the tileset: a variable that determines the number of frames used in the unit selection animation, and a variable that determines the number of ms each frame stays on.

**Describe alternatives you've considered**
This was discussed in the discord channel for project-vectron. The presented solution seems to be the most inclusive.

**Additional context**
none

**Comment by jwrober** [comment]
Additional Context: This will change the TileSpec CapStr to a new version.
