### ISSUE TITLE
Client bug: can't see all specialists in City window (F4), only Entertainers

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#794]
... and those you can see those twice! (See pic)

Reproduce: open City window (F4), right-click to select columns you want to see, check the beginning of the list.

WHat should be there: 
Specialists: Entertainers
Specialists: Scientists
Specialists: Taxman
Specialists: All (E/S/T)

What is there:
![image](https://user-images.githubusercontent.com/25233743/147820585-9f8b63fb-b432-4e58-8c99-a6c8d51799fd.png)

**Comment by lmoureaux** [comment]
I can't reproduce with the `classic` ruleset.

**Comment by Corbeau-1** [comment]
Gh... I'm an idiot. Can we delete this?

**Comment by lmoureaux** [comment]
Closing. For my own education, can you explain the reason?

**Comment by Corbeau-1** [comment]
No.

Delet dis.
