### ISSUE TITLE
CMake incorrectly uses dumpbin instead of objdump with GET_RUNTIME_DEPENDENCIES

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#796]
**Describe the bug**
CMake incorrectly uses dumpbin instead of objdump with GET_RUNTIME_DEPENDENCIES. We want to use objdump, not dumpbin.

**To Reproduce**
This one is really hard to duplicate. It's related to this CMake bug - https://gitlab.kitware.com/cmake/cmake/-/issues/20854 - and was discovered by a Discord community member who wanted to contribute to project-vectron.

**Expected behavior**
A Windows package is built successfully with objdump to capture the dependencies.

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Windows - MSys2
 - Freeciv21 version: Any
 - Ruleset/Longturn game (if applicable): N/A

**Additional context**
None

**Comment by lmoureaux** [comment]
I guess we should report it upstream...
