### ISSUE TITLE
Activating units in city window

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#805]
**In city window:**

Current state:
double-clicking or right-click-"activate" on a unit activates unit and closes city window

Problem: 
If I want to activate more units from the same city, I have to reopen the city window for each unit

Desired behaviour: 
Same as in GTK: have separate commands
"Activate" - activates unit but does not exit city window
"Activate and exit" - what it says

**Comment by jwrober** [comment]
I see this as more of a UI/UX bug.

**Comment by lmoureaux** [comment]
I think the proper solution would be to allow selecting multiple units from the list with the usual Ctrl and Shift shortcuts.

**Comment by Corbeau-1** [comment]
That works, too.
