### ISSUE TITLE
add Rhodesia nation

### ISSUE THREAD

**Issue by Sketlux** [longturn/freeciv21#823]
Add Rhodesia nation

Files contain everything necessary below
![rhodesia svg](https://user-images.githubusercontent.com/54208157/153758827-de598ee5-a3b5-458e-b161-d69b4fb640db.png)

[Rhodesia.zip](https://github.com/longturn/freeciv21/files/7877234/Rhodesia.zip)
.

**Comment by lmoureaux** [comment]
The svg flag is missing

**Comment by Sketlux** [comment]
What is the naming convention for the flags?

**Comment by Sketlux** [comment]
The is already a rhodesia.png (or for any other nation for what it is worth) in the flag folder. Shall I just name them the same?

**Comment by lmoureaux** [comment]
Yes :) Windows hides the part after the dot by default, but it's still there so they will actually have different file names.

**Comment by Sketlux** [comment]
I can add the svg rhodesia.png together with the zip folder but if I try to add the svg rhodesia png in the folder it conflicts with the current non-svg rhodsia.png! 
There are 4 images in each nation folder. 

XXX.png
XXX-large.png
XXX-shield.png
XXX-shield-large.png

svg doesn't appear to me as a format. The supposed svg I upload only has svg in the name.

**Comment by Sketlux** [comment]
https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Rhodesia_%281968%E2%80%931979%29.svg

**Comment by Sketlux** [comment]
Like this?

**Comment by lmoureaux** [comment]
Yes, this one is good :+1: Can you do the same for the other nations?
