### ISSUE TITLE
add German Empire nation

### ISSUE THREAD

**Issue by Sketlux** [longturn/freeciv21#825]
Files contain everything necessary below. 

Please start adding Braunschweig and Rhodesia first since the nationlist.ruleset already contains those nations.
[Germanempire.zip](https://github.com/longturn/freeciv21/files/7877367/Germanempire.zip)

**Comment by Sketlux** [comment]
SVG 

https://commons.wikimedia.org/wiki/File:Flag_of_Germany_(1867%E2%80%931918).svg

**Comment by lmoureaux** [comment]
The description taken from [this Wikipedia page](https://en.wikipedia.org/w/index.php?title=Rhodesia&oldid=730872930) needs to follow the [license requirements](https://en.wikipedia.org/wiki/Wikipedia:Reusing_Wikipedia_content). Here is some info about what Wikipedia considers [compliance](https://en.wikipedia.org/wiki/Wikipedia:CC_BY-SA_Compliance):

1. Approximates [[the Wikipedia] licence](https://en.wikipedia.org/wiki/Wikipedia:Copyrights#Reusers.27_rights_and_obligations); 
2. should mention Wikipedia,
3. should link to original article (or stable equivalent),
4. maintain copyright,
5. license, and
6. warranty (see [Wikipedia:General disclaimer](https://en.wikipedia.org/wiki/Wikipedia:General_disclaimer)) notices
7. and include or link to license.

Number 6 is automatically satisfied by the main `COPYING` file. For 5 we need to play a little to make the content available under CC-BY-SA 4.0 so we can formally use it under GPLv3 through one-way compatibility.

Current wording as a comment in the spec file for the other points:
```ini
; The following description uses material from the Wikipedia article 
; Rhodesia, which is released under the CC-BY-SA 3.0 Unported License (see
; dist/licenses/CC-BY-SA-3.0.txt).
; 
; Original article:
;   https://en.wikipedia.org/w/index.php?title=Rhodesia&oldid=730872930
; History:
;   https://en.wikipedia.org/w/index.php?title=Rhodesia&action=history
;
; The adaptation of this content for Freeciv21 was released under the CC-BY-SA 
; 4.0 Unported License (see dist/licenses/CC-BY-SA-4.0.txt).
```

Not mentioning GPL yet, would need to add so we can mention a [proxy](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility:_GPLv3#Option_to_comply_with_later_versions).

Or maybe I'm pushing too far and we should just cite. Need to think about it.

Easiest option is of course to write some new text based on the Wiki info, then there's no licensing problem.

**Comment by Sketlux** [comment]
I thought most national flags follow simple geometry and are therefore ineligible for copyrights?

**Comment by lmoureaux** [comment]
The flag itself is apparently public domain in the US and UK. This is about the nation description, it's also from Wiki
