### ISSUE TITLE
New interface item: shuffle city worked tiles from main map/screen

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#832]
At the moment, it is possible to view which city works which tiles from the main map/screen by using shift-alt-rightclick. If you switch on multiple cities, it looks something like this:

![image](https://user-images.githubusercontent.com/25233743/149924073-0d5dc375-7804-4a87-906c-e651dcf753ca.png)

The problem happens when you have to switch jurisdiction over one tile, or worse, switch two tiles between cities:
1. enter city 1
2. remove worker from tile A
3. exit city
4. enter city 2
5. reassign worker from tile B to tile A
6. exit city 2
7. enter city 1
8. assign worker to tile B

All this time you need to keep a mental record which tile you are actually switching. 

New feature 1: Allow switching on the main map view for ALL cities at once. At the moment you have to click once for every city. If there are more cities, that may be a lot of clicking and . The new key combination could be shift-alt-**ctrl**-rightclick.This would toggle all-none.

New feature 2, and this one is a bit more complex: allow (re)assigning workers without having to enter the city:
When worked tiles are visible on the main map, make it possible to 
1. un-assign a city worker from the tile by, say, clicking alt-rightclick (I checked, it doesn't seem to do anything at the moment)
2. IF there are available workers, assign one to a tile by alt-rightHOLD-drag-release from the city tile to the working tile, (if "right-hold is possible at all)

====================
ADDITION that may somewhat complicate the previous, or may simplify it:
Add two keys/shortcuts for the MAIN map:
1. Remove all workers from the tiles of a clicked city (turn them all into primary specialists, whatever they are)
2. (Re)distribute all workers to the available tiles for a clicked city, according to the standard criteria

**Comment by Corbeau-1** [comment]
ADDITION added.

**Comment by lmoureaux** [comment]
#899 makes this use case easier. The sequence from the description is reduced to:

1. enter city 1
2. remove worker from tile A
3. enter city 2
4. reassign worker from tile B to tile A
5. enter city 1
6. assign worker to tile B

I'm reluctant to adding shortcuts using more than one modifier key.

**Comment by Corbeau-1** [comment]
> I'm reluctant to adding shortcuts using more than one modifier key.

Well, they already exist, so you would be "adding more on the same branch".

But if modifiers are the problem, maybe use it with less modifiers? FCW has something similar, I think it's only CTRL-click (or something, and it has problems). But I'd avoid that exactly because there is **already** a shift-alt in place.

The problem with your suggestion is that it may happen that the other city is covered by the active city widgets/window so it would again require more clicking.

**Comment by lmoureaux** [comment]
We could also switch city when clicking on the blocked tile, but without more visual clues this might be counterintuitive.

**Comment by Corbeau-1** [comment]
Yes, this would lead to a mess. Misclicks are often in this situation.

Very simple: shift+alt+rightclick already works for showing worked tiles. Make shift+alt+**left**click do the full recall/spread workers toggle (if the worked tile mode is on, don't want this happening by accident). Couldn't be simpler (for the user).

**Comment by lmoureaux** [comment]
> Very simple: shift+alt+rightclick already works for showing worked tiles. Make shift+alt+leftclick do the full recall/spread workers toggle (if the worked tile mode is on, don't want this happening by accident). Couldn't be simpler (for the user).

This shortcut exists and is assigned to Meta+Ctrl+Left click by default. See Game > Shortcuts.

**Comment by Corbeau-1** [comment]
Just curious, I see this issue is closed. Does this mean that it's implemented?

**Comment by lmoureaux** [comment]
See above,
> This shortcut exists and is assigned to Meta+Ctrl+Left click by default. See Game > Shortcuts.

Though I may have missed something because this was a multipart issue.

**Comment by Corbeau-1** [comment]
Out of three things mentioned in the first post, this is roughly half of one thing.

**Comment by lmoureaux** [comment]
Yeah that's the usual problem with jumbo issues, one never knows when they are fixed. I guess I finally understand number 1 now (switch colors for all cities). Should be a keyboard shortcut and with an item in the View menu.

I think number 2 is complete with the shortcut.

The addition would be nice to have, though maybe from the city list instead (next to the governor options we have there).

Feel free to open finer grained issues, it's always easier to handle.

**Comment by Corbeau-1** [comment]
> Yeah that's the usual problem with jumbo issues, one never knows when they are fixed. I guess I finally understand number 1 now (switch colors for all cities). Should be a keyboard shortcut and with an item in the View menu.
> 
> I think number 2 is complete with the shortcut.

Yeah, now my question would be: which one, there are two "number 2s".

I'll open smaller issues. Keep this one closed.
