### ISSUE TITLE
Make it easier to know/see that a diplomatic screen is open

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#843]
**Is your feature request related to a problem? Please describe.**
Right now you have to right-click on the Nations tab to open up an existing diplomatic screen. If you effectively have to "know" that its there. The client does not prompt.

**Describe the solution you'd like**
Add a button or something to the nations tab to open the diplomatic screen. Maybe make it blink or something to draw your eye to it to know that something is there requiring your attention.

**Describe alternatives you've considered**
Its been discussed that we need a client manual of some kind, but RTFM should not be a solution here.

**Additional context**
Trying to reduce the number of hidden features to make the client more intuitive.

**Comment by lmoureaux** [comment]
How would it behave with the top bar we've been discussing in #750 ?

**Comment by jwrober** [comment]
My initial thought is the new top bar would also have an icon or something to draw your eye to.

**Comment by jwrober** [comment]
This was documented in PR #1211 and with implementation of the top bar, it is much easier to see if a diplomatic screen is open. Closing

**Comment by lmoureaux** [comment]
I don't understand how it's easier now :question:

**Comment by jwrober** [comment]
> I don't understand how it's easier now question

Because the button changes from saying "Nations" to saying "<Nation Name"> with the flag of the nation that has an open diplomatic screen. I think that is pretty obvious.

**Comment by lmoureaux** [comment]
Hmmm... I think that was already the case but it was reset easily

**Comment by jwrober** [comment]
I think your implementation of the top bar makes it work great now. I opened this issue before the top bar was done.

**Comment by lmoureaux** [comment]
ok :open_hands:
