### ISSUE TITLE
Server started from Windows Explorer blocks on input

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#850]
**Describe the bug**

Apparently we still have this bug.

**To Reproduce**
1. Start a server from Windows Explorer
2. Start a client, go to network page
3. Don't see your server
4. Go to server window, hit a key
5. Go back to client, see your server listed
6. Try to connect, seems to block
7. Go to server window, hit a key
8. Connect unblocks

**Expected behavior**

Client seamlessly detects the server and connects.

**Platform and version (please complete the following information):**
 - OS: Windows 10
 - Freeciv21 version: 3.0-alpha9

**Additional context**

The server event loop is blocked waiting for input on stdin. Move input to a thread.

**Comment by lmoureaux** [comment]
We don't install such a shortcut, so can't reproduce without additional instructions -> closing.
@Corbeau-1 was it you who reported this on Discord? If you have more info I'll reopen

**Comment by Corbeau-1** [comment]
I can confirm that I have a version of ....1112 that has this bug.

Before hitting enter:

![image](https://user-images.githubusercontent.com/25233743/153731214-d9b0ea96-c75d-4cae-9aa1-82f18f5a3d18.png)

After hitting enter:

![image](https://user-images.githubusercontent.com/25233743/153731237-0b41b5e1-0430-43f9-b7a2-805673242461.png)

**Comment by lmoureaux** [comment]
This looks like the debugging build for #824.

How did you start the server?

**Comment by Corbeau-1** [comment]
I doubleclicked `freeciv21-server.exe`.

**Comment by Corbeau-1** [comment]
> That's why it's better to file issues yourself, I got it wrong and couldn't reproduce 😉

Right, sorry :) I didn't file an issue because I didn't think it was important. But it's probably important for general functioning of the software. I'll keep it in mind for the next time.
