### ISSUE TITLE
Assertion error in utility/rand.cpp

### ISSUE THREAD

**Issue by jwrober** [longturn/freeciv21#861]
**Describe the bug**
[critical] freeciv21-client (../utility/rand.cpp:155) - Assertion seed < 0xFFFFFFFF / (10007) failed

**To Reproduce**
Steps to reproduce the behavior - unsure exactly how to reproduce. Discovered during testing of PR #824.

**Expected behavior**
No critical assertion error

**Screenshots**
N/A

**Platform and version (please complete the following information):**
 - OS: Linux (but assume its on all of them)
 - Freeciv21 version: 3.0-alpha10
 - Ruleset/Longturn game (if applicable): My save used in testing was off Classic rules

**Additional context**
None

**Comment by lmoureaux** [comment]
`fc_randomly` supports seeds (first parameters) up to 429196.

The relevant code calling `fc_randomly` does the following:
```cpp
        const int i =
            fc_randomly(tile_index(ptile) % 32000, info.sprites.size());
```

The only way for the seed to be too large is that `tile_index(ptile)` be negative. In that case the conversion to `unsigned` will yield a large number.

:arrow_right: this assertion appears when rendering a virtual tile, which has index -1
:arrow_right: which is only done in the help dialog
