### ISSUE TITLE
Depiction of worked tiles on the main map is faulty

### ISSUE THREAD

**Issue by Corbeau-1** [longturn/freeciv21#864]
When you shift-alt-rightclick on the main map, you get city tiles coloured if they are worked by a city. However, in one case, I got this:

![image](https://user-images.githubusercontent.com/25233743/152153356-84e5e81a-1523-4b95-8329-e006b78073fe.png)

The real layout is different, there should be definitely more tiles and, as visible in the image, some tiles are only half painted. This could be an issue of city size and map zoom level.

The issue starts fixing itself if I click on surrounding cities.

![image](https://user-images.githubusercontent.com/25233743/152153829-956a2fbf-8491-4d1d-9632-5fbb693c1fa7.png)

More zoom:

![image](https://user-images.githubusercontent.com/25233743/152153993-f25873c1-c431-4f9b-bff4-eedc85fa352c.png)

Less zoom:

![image](https://user-images.githubusercontent.com/25233743/152154047-2f607a30-45b5-456b-8cb3-c553a29e445c.png)

**Comment by lmoureaux** [comment]
I couldn't reproduce with Trident and classic. Does it also happen for normal-sized cities?

**Comment by Corbeau-1** [comment]
Depens on zoom evel. I managed to reproduce it for a small city, but with a huge zoom. 

![image](https://user-images.githubusercontent.com/25233743/152685914-622c3c9a-38ad-4b4c-b41c-6c0b2711d3c6.png)

First I thought it's about pixels, the area always having the same AxB in dots, but it's not. The one linked here has 554x554 (!?), while other, large cities with a more moderate zoom, went down to roughly 400x400.

**Comment by Corbeau-1** [comment]
Classic ruleset:

![image](https://user-images.githubusercontent.com/25233743/152686466-a5d1556b-0490-4ff6-935e-7adf531af68b.png)

**Comment by lmoureaux** [comment]
Works for me even for super large zoom levels…
![image](https://user-images.githubusercontent.com/22327575/152690347-9d2e3e18-7b78-42a8-a8c5-968cfe1a8c20.png)

**Comment by Corbeau-1** [comment]
The image above doesn't really say anything about this issue. What matters is where the shaded area stops.

**Comment by lmoureaux** [comment]
With this extreme zoom level (twice yours) I would expect to see a broken rectangle.
I closed this issue because #870 overhauled zoom handling and from what you write this is related to zoom. We can reopen if the new zoom also breaks...

**Comment by Corbeau-1** [comment]
Techically, the rectangle grows with zoom level so at this level it may take up the whole screen. But ok, let's see what happens with the new version.
