### ISSUE TITLE
Support vision_subs_sq on units

### ISSUE THREAD

**Issue by ec429** [longturn/freeciv21#893]
**Is your feature request related to a problem? Please describe.**
Bases can grant vision of submarine units at range, with `vision_subs_sq`; but units can't have the same thing.

**Describe the solution you'd like**
Add a unittype field `vision_subs_sq` that sets the unit's vision range for `vision_layer = "Subsurface"` units.

**Describe alternatives you've considered**
Could add a `vision_layer` req to the `Unit_Vision_Radius_Sq` effect; but this would require ruleset compat to add `"Vision Layer", "Surface", "Local", TRUE` to all existing instances of the effect.

**Additional context**
I'm fairly sure upstream freeciv has unit.vision_subs_sq as of 3.1.

**Comment by lmoureaux** [comment]
No trace of this feature in https://github.com/freeciv/freeciv (or it's called differently).

**Comment by ec429** [comment]
Given that I apparently hallucinated the existence of this upstream and that there's thus not an existing feature to be compatible with, I'm leaning in favour of the Effect-based approach.  It's more flexible, and extends smoothly if we add more layers in the future.  And I can see roughly how to implement it, so I'll rustle up a PR.
