### ISSUE TITLE
Merge all client code into client/

### ISSUE THREAD

**Issue by lmoureaux** [longturn/freeciv21#915]
**Is your feature request related to a problem? Please describe.**

The client code is currently scattered across two directories:
```
client/
client/gui-qt/
```

While the separation was logical when there were several clients, it is no longer the case. It would be more logical to split based on functionality (e.g. `network`, `tileset`, `mapview`, `help`, …). As a first step before isolating functional blocks, I want to move all `gui-qt` files to `client`.

**Comment by lmoureaux** [comment]
It's actually not so trivial because `civmanual` depends on client functions

**Comment by lmoureaux** [comment]
> It's actually not so trivial because `civmanual` depends on client functions

This is tackled in #926.

**Comment by jwrober** [comment]
Closed via PR #1021
