### ISSUE TITLE
Mouseup events count as clicks in city view

### ISSUE THREAD

**Issue by ec429** [longturn/freeciv21#933]
**Describe the bug**
When clicking on tiles in the city view to move citizens from one tile to another, both the mouse-down and mouse-up events are treated as clicks, meaning that the worker is removed and then immediately re-added.

**To Reproduce**
1. Start a game
2. Build a city
3. Click on a worked tile
4. Citizen isn't removed from the tile

**Expected behavior**
Only the mouse-down event should register; clicking on a worked tile should turn the citizen into a specialist.

**Platform and version (please complete the following information):**
 - OS: Linux (Debian testing)
 - Freeciv21 version: `ddec022d5c` (tip of `master`)
 - Ruleset/Longturn game (if applicable): `aviation` (but presumably happens elsewhere too)

**Additional context**
As a workaround, clicking and dragging from one tile to another moves citizens, and dragging outside of the city radius allows to add/remove specialists.

**Comment by lmoureaux** [comment]
Likely 55c47e9b5c1576487b4629b1459d7ff186b8b39e
