### ISSUE TITLE
Client renders terrain specials that aren't there

### ISSUE THREAD

**Issue by ec429** [longturn/freeciv21#974]
**Describe the bug**
If there are more than a certain number of extras defined in the ruleset, the client renders some of them with a special overlaid.  In the case of the current Aviation ruleset, this consists of Gold on rails and Iron on rivers.

**To Reproduce**
Download the latest Aviation ruleset from http://jttlov.no-ip.org/fc-aviation-latest/aviation.json
Start a game.
Observe the terrain.  There will be iron bars drawn on all tiles with rivers, despite these tiles not having the Iron special.

**Expected behavior**
Specials should only appear on tiles that actually have them.

**Screenshots**
![fcgold](https://user-images.githubusercontent.com/287956/160986397-38f43586-b4cd-4f39-a10c-062adc637f04.png)
![fcgoldbug](https://user-images.githubusercontent.com/287956/160986406-c42c2cde-81f0-4def-b6ab-347fdef08807.png)
Example of a tile with rails, showing nonexistent gold.

**Platform and version (please complete the following information):**
 - OS: Linux (Debian testing)
 - Freeciv21 version: `e9f5b020e9`
 - Ruleset/Longturn game (if applicable): Aviation `8afef23`

**Additional Context**
The bug first appeared when I added the Spotted extras to `terrain.ruleset` and `aviation.tilespec`.

**Comment by jwrober** [comment]
It happens with the hexemplio tiles and the experimental rules that come with the standard distribution as well

![image](https://user-images.githubusercontent.com/23037938/162059232-b6833671-826e-417d-b395-502f5495d39e.png)

**Comment by lmoureaux** [comment]
I was able to repro once with `experimental`, and then it disappeared. Is it 100% reproducible for you?

**Comment by ec429** [comment]
Yes, 100%.  Every game with latest `aviation`, and always the exact same pattern (gold rails and iron rivers).

I haven't tried with any more recent client version than in the original report though.

**Comment by lmoureaux** [comment]
Private chat: it appears when the ruleset is changed but the tileset is not, e.g. when loading a game with a non-default ruleset.

**Comment by ec429** [comment]
I can confirm that #1027 fixes this for me.  :partying_face:
